# test_jump_simulation_adversarial.gd
#
# Adversarial extension of the jump simulation test suite.
# Generated by Test Breaker Agent — 2026-03-01.
#
# This file targets boundary conditions, mutation scenarios, edge-case
# configurations, and spec gaps NOT covered by the 49-test primary suite in
# tests/test_jump_simulation.gd. Every test includes a comment explaining the
# specific vulnerability it probes.
#
# Spec coverage targeted:
#   SPEC-15 — State immutability for new fields under adversarial call patterns
#   SPEC-16 — Config boundary values (zero, negative, nonsensical)
#   SPEC-17 — Simultaneous jump_just_pressed + jump_pressed edge combinations
#   SPEC-18 — Jump impulse: jump_height=0, jump_height<0, gravity=0+height=0
#   SPEC-19 — Coyote timer boundary: exactly==delta, barely above, very large delta,
#              coyote_time=0.0 departure frame, multi-frame sequences
#   SPEC-20 — Jump cut: jump_cut_velocity=0.0, jump_cut_velocity positive,
#              jump cut on same frame as jump (simultaneous fire + no button hold)
#   SPEC-21 — Double-jump prevention: second consecutive just_pressed frame blocked,
#              landing detection on consumed=true, consumed state multi-step sequences
#   SPEC-24 — Frame-rate independence under very large delta for coyote timer
#
# Checkpoint log (see CHECKPOINTS.md for full text):
#   [M1-002] Test Breaker — TB-J-001: simultaneous just_pressed=true + pressed=false
#   [M1-002] Test Breaker — TB-J-002: coyote_timer exactly equal to delta
#   [M1-002] Test Breaker — TB-J-003: very large delta eating full coyote window
#   [M1-002] Test Breaker — TB-J-004: jump_height = 0.0 impulse formula
#   [M1-002] Test Breaker — TB-J-005: jump_height negative NaN risk
#   [M1-002] Test Breaker — TB-J-006: gravity=0.0 + jump_height=0.0 dual-zero case
#   [M1-002] Test Breaker — TB-J-007: coyote_time=0.0 — departure frame reset behavior
#   [M1-002] Test Breaker — TB-J-008: jump_cut_velocity=0.0 clamp behavior
#   [M1-002] Test Breaker — TB-J-009: jump_cut_velocity positive (nonsensical config)
#   [M1-002] Test Breaker — TB-J-010: consecutive simulate() calls with just_pressed=true
#   [M1-002] Test Breaker — TB-J-011: landing detection resets jump_consumed on transition frame
#   [M1-002] Test Breaker — TB-J-012: prior_state immutability under multiple adversarial patterns

class_name JumpSimulationAdversarialTests
extends "res://tests/utils/test_utils.gd"

const EPSILON: float = 1e-4

var _pass_count: int = 0
var _fail_count: int = 0


func _make_state_with(vx: float, vy: float, on_floor: bool) -> MovementSimulation.MovementState:
	var s: MovementSimulation.MovementState = MovementSimulation.MovementState.new()
	s.velocity = Vector2(vx, vy)
	s.is_on_floor = on_floor
	return s


# ---------------------------------------------------------------------------
# [M1-002] TB-J-001 — Simultaneous jump_just_pressed=true AND jump_pressed=false
#
# VULNERABILITY: The spec notes (SPEC-17 constraints) that jump_just_pressed=true
# with jump_pressed=false is not a valid runtime state — the engine guarantees
# just_pressed can only be true when pressed is also true. However, a test
# passing this combination directly to simulate() exercises a hidden code path:
# the jump eligibility check fires (just_pressed=true) but immediately after,
# the jump cut condition (NOT jump_pressed AND velocity.y < jump_cut_velocity)
# is also evaluated. If the implementation evaluates jump cut on the same frame
# as the jump fires, and jump_pressed=false is observed, the result may be
# clamped immediately to jump_cut_velocity — a "zero-height" jump on the same
# frame. This mutation tests whether the implementation is order-sensitive to
# jump_pressed vs jump_just_pressed when they disagree.
# CHECKPOINT
# ---------------------------------------------------------------------------

# Single-frame tap with jump_just_pressed=true but jump_pressed=false.
# Jump eligibility condition: just_pressed=true, on_floor=true, not consumed → jump fires.
# Jump cut condition (after gravity): NOT jump_pressed(=false) AND result.vy < -200.0 → clamp.
# Expected result: jump fires, then jump cut clamps velocity.y to jump_cut_velocity (-200.0).
# If implementation does not apply jump cut on jump frame: velocity.y = impulse + gravity*delta ≈ -469.29
# If implementation correctly applies jump cut after impulse+gravity: velocity.y = -200.0
# The spec (SPEC-20) states jump cut applies "after all vertical velocity computation (impulse + gravity)"
# and conditions on "jump_pressed == false". On this frame jump_pressed IS false, so clamp fires.
func test_j001_simultaneous_just_pressed_true_pressed_false_jump_then_cut() -> void:
	# CHECKPOINT
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	# jump_just_pressed=true (trigger), jump_pressed=false (not held this frame)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, true, false, 0.0, [false, false], 0.016)
	# Jump fires: impulse + gravity*delta = -sqrt(235200) + 15.68 ≈ -469.29
	# Jump cut: jump_pressed=false AND -469.29 < -200.0 → clamp to -200.0
	_assert_approx(result.velocity.y, -200.0,
		"TB-J-001 — just_pressed=true + pressed=false: jump fires then cut clamps to -200.0")
	# jump_consumed should still be set true because a jump did fire
	_assert_true(result.jump_consumed == true,
		"TB-J-001 — just_pressed=true + pressed=false: jump_consumed=true (jump did fire)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-002 — Normal hold: jump_just_pressed=true AND jump_pressed=true
#
# VULNERABILITY: This is the canonical correct call pattern. The adversarial
# concern is that an implementation might accidentally apply jump cut even when
# jump_pressed=true (e.g., by checking jump_just_pressed instead of jump_pressed
# for the cut condition). This test confirms no cut occurs on the jump frame
# when the button is held, and that the full impulse is reflected in the output.
# ---------------------------------------------------------------------------

func test_j002_normal_hold_jump_pressed_and_just_pressed_both_true_no_cut() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	# Canonical jump: both pressed=true and just_pressed=true
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	var expected: float = -sqrt(2.0 * 980.0 * 120.0) + 980.0 * 0.016
	# jump_pressed=true → jump cut condition (NOT jump_pressed) is false → no clamp
	_assert_approx(result.velocity.y, expected,
		"TB-J-002 — both pressed=true + just_pressed=true: full impulse, no jump cut on jump frame")
	_assert_true(result.jump_consumed == true,
		"TB-J-002 — both pressed=true + just_pressed=true: jump_consumed=true")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-002b — jump_just_pressed=true with jump_pressed=false at
# coyote_cut_velocity boundary: verify cut clamps to exactly cut value.
#
# VULNERABILITY: Extends TB-J-001 with a custom jump_cut_velocity=-100.0
# to confirm the cut uses self.jump_cut_velocity, not a hardcoded -200.0.
# ---------------------------------------------------------------------------

func test_j002b_single_frame_tap_custom_cut_velocity_clamps_correctly() -> void:
	# CHECKPOINT
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_cut_velocity = -100.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	# just_pressed=true, pressed=false → jump fires then cut clamps at -100.0
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, true, false, 0.0, [false, false], 0.016)
	# impulse ≈ -484.97, +gravity ≈ -469.29; -469.29 < -100.0 → clamp to -100.0
	_assert_approx(result.velocity.y, -100.0,
		"TB-J-002b — custom cut_vel=-100: single-frame tap clamps to -100.0 not -200.0")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-003 — coyote_timer exactly equal to delta
#
# VULNERABILITY: When prior_state.coyote_timer == delta exactly, the decrement
# produces max(0.0, coyote_timer - delta) = 0.0. But the eligibility check uses
# prior_state.coyote_timer (which is delta > 0.0), so the jump must still fire.
# An off-by-one implementation that uses result.coyote_timer instead of
# prior_state.coyote_timer for the eligibility check would see 0.0 and block
# the jump. This is the exact boundary the spec calls out in SPEC-19.
# ---------------------------------------------------------------------------

func test_j003_coyote_timer_exactly_equals_delta_jump_still_fires() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var delta: float = 0.016
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	# coyote_timer == delta exactly. After decrement: max(0, 0.016 - 0.016) = 0.0.
	# But prior.coyote_timer = 0.016 > 0.0 → eligibility check should allow jump.
	prior.coyote_timer = delta
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], delta)
	# Jump must fire because prior.coyote_timer=0.016 > 0
	var expected_vy: float = -sqrt(2.0 * 980.0 * 120.0) + 980.0 * delta
	_assert_approx(result.velocity.y, expected_vy,
		"TB-J-003 — coyote_timer==delta (prior=0.016>0): jump fires (eligibility uses prior)")
	# After jump: result.coyote_timer should be decremented to 0.0
	_assert_approx(result.coyote_timer, 0.0,
		"TB-J-003 — result.coyote_timer decremented to 0.0 (0.016-0.016=0)")
	_assert_true(result.jump_consumed == true,
		"TB-J-003 — jump_consumed=true after coyote-timer-boundary jump")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-003b — coyote_timer slightly above delta (barely eligible)
#
# VULNERABILITY: A precision issue where the implementation might use strict
# less-than vs less-than-or-equal in the decrement clamp. If coyote_timer is
# delta+EPSILON, after decrement it should be EPSILON (still > 0). This
# separate scenario ensures no rounding swallows the positive residual.
# ---------------------------------------------------------------------------

func test_j003b_coyote_timer_slightly_above_delta_timer_decrements_to_positive() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var delta: float = 0.016
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	# coyote_timer = delta + 0.001 → after decrement = 0.001 (positive, not zero)
	prior.coyote_timer = delta + 0.001
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], delta)
	_assert_approx(result.coyote_timer, 0.001,
		"TB-J-003b — coyote_timer=delta+0.001: decrements to 0.001, not clamped to zero")
	_assert_true(result.coyote_timer > 0.0,
		"TB-J-003b — result.coyote_timer > 0.0 (still positive residual)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-003c — coyote_timer slightly below delta (should reach exactly 0.0)
#
# VULNERABILITY: When coyote_timer < delta, max(0, timer - delta) should produce
# exactly 0.0 (not a small negative). Confirms clamping is working.
# ---------------------------------------------------------------------------

func test_j003c_coyote_timer_slightly_below_delta_clamped_to_zero() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var delta: float = 0.016
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	# coyote_timer = delta - 0.001 = 0.015. After decrement: max(0, 0.015-0.016) = max(0,-0.001) = 0.0
	prior.coyote_timer = delta - 0.001
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], delta)
	_assert_approx(result.coyote_timer, 0.0,
		"TB-J-003c — coyote_timer=delta-0.001: decrements and clamps to 0.0 (no negative)")
	_assert_false(result.coyote_timer < 0.0,
		"TB-J-003c — result.coyote_timer is not negative (clamp enforced)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-004 — Very large delta eating the entire coyote window at once
#
# VULNERABILITY: A very large delta (e.g., 1.0 second, a stutter frame or
# test scenario) should exhaust the coyote window in one step via the
# max(0.0, coyote_timer - delta) clamp. If the implementation uses unguarded
# subtraction without the clamp, result.coyote_timer goes negative. This also
# validates that jump_just_pressed=true on the same large-delta frame with a
# timer of 0.1 still fires (prior.coyote_timer=0.1 > 0 even if delta=1.0).
# ---------------------------------------------------------------------------

func test_j004a_very_large_delta_clamps_coyote_timer_to_zero() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.coyote_timer = 0.1
	# delta=1.0: max(0, 0.1 - 1.0) = 0.0
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 1.0)
	_assert_approx(result.coyote_timer, 0.0,
		"TB-J-004a — delta=1.0 eats coyote window: result.coyote_timer = 0.0 (clamped)")
	_assert_false(result.coyote_timer < 0.0,
		"TB-J-004a — result.coyote_timer is not negative even with very large delta")


func test_j004b_very_large_delta_jump_still_fires_from_prior_positive_coyote_timer() -> void:
	# CHECKPOINT
	# prior.coyote_timer=0.1 > 0 → eligible even with delta=1.0.
	# Eligibility uses prior_state.coyote_timer, not result.coyote_timer.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.coyote_timer = 0.1
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 1.0)
	# Impulse fires (prior.coyote_timer=0.1 > 0), gravity adds 980.0 * 1.0 = 980.0
	var expected_vy: float = -sqrt(2.0 * 980.0 * 120.0) + 980.0 * 1.0
	_assert_approx(result.velocity.y, expected_vy,
		"TB-J-004b — large delta=1.0, prior coyote_timer=0.1>0: jump fires (eligibility from prior)")
	_assert_approx(result.coyote_timer, 0.0,
		"TB-J-004b — result.coyote_timer clamped to 0.0 after large delta decrement")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-005 — jump_height = 0.0 (sqrt of zero)
#
# VULNERABILITY: jump_height=0.0 produces impulse = -sqrt(0.0) = 0.0.
# This is numerically valid in GDScript (sqrt(0) = 0, no NaN). The jump fires
# (conditions met) but the impulse is zero, so the only velocity change on the
# jump frame is from gravity. An implementation that special-cases jump_height=0
# or hardcodes a minimum impulse would fail. Tests confirm: finite, not NaN,
# and equals exactly gravity*delta (impulse=0 means prior.vy + gravity*delta).
# ---------------------------------------------------------------------------

func test_j005a_jump_height_zero_produces_zero_impulse_not_nan() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_height = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_true(not is_nan(result.velocity.y),
		"TB-J-005a — jump_height=0: velocity.y is not NaN")
	_assert_true(is_finite(result.velocity.y),
		"TB-J-005a — jump_height=0: velocity.y is finite")


func test_j005b_jump_height_zero_velocity_equals_gravity_only() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_height = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# impulse = -sqrt(2.0 * 980.0 * 0.0) = 0.0; gravity adds 15.68; result = 0.0 + 15.68 = 15.68
	# But jump cut: result.vy = 15.68, which is NOT < -200.0 → no clamp.
	_assert_approx(result.velocity.y, 980.0 * 0.016,
		"TB-J-005b — jump_height=0: result.vy = 0 (impulse) + gravity*delta = 15.68")


func test_j005c_jump_height_zero_jump_consumed_still_set_true() -> void:
	# CHECKPOINT: Does the implementation set jump_consumed=true even when impulse=0?
	# The spec says jump_consumed is set when "a jump is applied" — if the eligibility
	# condition is met and impulse is computed (even if 0.0), consumed should be set.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_height = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_true(result.jump_consumed == true,
		"TB-J-005c — jump_height=0: jump_consumed=true even though impulse was zero")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-006 — jump_height negative (sqrt of negative → NaN risk)
#
# VULNERABILITY: Negative jump_height is undefined behavior per SPEC-16
# ("undefined behavior is defined for: negative jump_height"). The spec states
# it must not produce NaN, Inf, or crashes. In GDScript, sqrt(-1.0) returns NaN
# on some platforms and may produce -inf on others. An implementation using
# the formula directly without guarding against negative inputs will propagate
# NaN into result.velocity.y, corrupting all subsequent simulation state.
# This test asserts only finiteness — not a specific value — since negative
# jump_height is undefined behavior. The test would FAIL on an implementation
# that passes sqrt(-1.0) directly through as NaN.
# CHECKPOINT
# ---------------------------------------------------------------------------

func test_j006_negative_jump_height_velocity_y_is_finite_not_nan() -> void:
	# CHECKPOINT
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_height = -10.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_true(not is_nan(result.velocity.y),
		"TB-J-006 — jump_height=-10: velocity.y must not be NaN (undefined but must not crash)")
	_assert_true(is_finite(result.velocity.y),
		"TB-J-006 — jump_height=-10: velocity.y must be finite (undefined but must not crash)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-007 — gravity=0.0 AND jump_height=0.0 (dual-zero case)
#
# VULNERABILITY: Both inputs to sqrt() multiply to zero: sqrt(0*0*0) = sqrt(0)=0.
# This is a valid path (no NaN). But implementations that branch on "gravity > 0"
# before computing impulse may skip the jump entirely or return an incorrect value.
# Tests confirm finiteness and that the result is exactly 0.0.
# ---------------------------------------------------------------------------

func test_j007_gravity_zero_and_jump_height_zero_both_produce_zero_velocity_y() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.gravity = 0.0
	sim.jump_height = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_true(not is_nan(result.velocity.y),
		"TB-J-007 — gravity=0 + jump_height=0: velocity.y is not NaN")
	_assert_true(is_finite(result.velocity.y),
		"TB-J-007 — gravity=0 + jump_height=0: velocity.y is finite")
	_assert_approx(result.velocity.y, 0.0,
		"TB-J-007 — gravity=0 + jump_height=0: velocity.y == 0.0 (sqrt(0)+0=0)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-008 — coyote_time=0.0: departure frame behavior
#
# VULNERABILITY: With coyote_time=0.0, on the departure frame (prior.is_on_floor=true),
# the timer reset rule sets result.coyote_timer = coyote_time = 0.0. On the very
# next frame (first airborne frame), prior.coyote_timer=0.0 which is NOT > 0.0,
# so coyote jumps are impossible. SPEC-16 risk R-16.3 documents this explicitly.
# An implementation that resets to a hardcoded 0.1 instead of self.coyote_time
# would incorrectly grant a coyote window even with coyote_time=0.0.
# ---------------------------------------------------------------------------

func test_j008a_coyote_time_zero_departure_frame_timer_resets_to_zero() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.coyote_time = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.coyote_timer = 0.0
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	# On floor → reset to coyote_time = 0.0
	_assert_approx(result.coyote_timer, 0.0,
		"TB-J-008a — coyote_time=0.0, on floor: result.coyote_timer = 0.0 (not 0.1)")


func test_j008b_coyote_time_zero_first_airborne_frame_no_coyote_jump() -> void:
	# CHECKPOINT
	var sim: MovementSimulation = MovementSimulation.new()
	sim.coyote_time = 0.0
	# Simulate the first airborne frame: prior.coyote_timer=0.0 (set to coyote_time=0 on departure)
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.coyote_timer = 0.0
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# coyote_timer=0.0, not > 0.0 → no coyote jump. is_on_floor=false → no floor jump.
	var expected_vy: float = 0.0 + 980.0 * 0.016
	_assert_approx(result.velocity.y, expected_vy,
		"TB-J-008b — coyote_time=0.0, first airborne frame: no coyote jump (timer==0.0 not >0)")
	_assert_false(result.jump_consumed,
		"TB-J-008b — coyote_time=0.0, no jump fired: jump_consumed stays false")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-009 — jump_cut_velocity=0.0: all ascending velocity cut to exactly 0
#
# VULNERABILITY: With jump_cut_velocity=0.0, the jump cut condition becomes:
# "NOT jump_pressed AND result.velocity.y < 0.0" — any upward motion is cut.
# This is AC-20.7's scenario and is covered in the primary suite, but the
# adversarial angle is: what if the velocity is exactly 0.0 after gravity?
# The strict less-than means result.vy == 0.0 is NOT clamped (not < 0.0).
# Also: what about very small negative values like -0.001 — they must be clamped.
# ---------------------------------------------------------------------------

func test_j009a_jump_cut_velocity_zero_small_negative_vy_clamped() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_cut_velocity = 0.0
	# Set vy so that after gravity it is a small negative: need vy + gravity*delta < 0
	# vy = -0.1, delta=0.016: -0.1 + 15.68 = 15.58 > 0 → not clamped.
	# Try vy = -20.0, delta=0.016: -20 + 15.68 = -4.32 < 0.0 → clamped to 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -20.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.y, 0.0,
		"TB-J-009a — jump_cut_velocity=0.0, vy=-20: after gravity=-4.32 < 0.0 → clamped to 0.0")


func test_j009b_jump_cut_velocity_zero_positive_vy_not_clamped() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_cut_velocity = 0.0
	# vy = 50.0: after gravity = 50 + 15.68 = 65.68 > 0.0 → NOT < 0.0 → no clamp
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 50.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.y, 65.68,
		"TB-J-009b — jump_cut_velocity=0.0, falling vy=50: 65.68 > 0.0, no clamp")


func test_j009c_jump_cut_velocity_zero_exact_zero_after_gravity_not_clamped() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_cut_velocity = 0.0
	# We need vy such that vy + gravity*delta == 0.0 exactly.
	# vy + 980.0 * 0.016 = 0.0 → vy = -15.68
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -15.68, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	# -15.68 + 15.68 = 0.0. 0.0 < 0.0 is false → no clamp. result.vy == 0.0
	_assert_approx(result.velocity.y, 0.0,
		"TB-J-009c — jump_cut_velocity=0.0, exact boundary vy=-15.68: 0.0 is NOT < 0.0, no clamp")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-010 — jump_cut_velocity positive (nonsensical config)
#
# VULNERABILITY: A positive jump_cut_velocity (e.g., 50.0) means the cut
# condition "result.vy < 50.0" is true for ALL downward velocities (positive
# y values in screen space) and some upward velocities. This is a nonsensical
# configuration that the spec acknowledges produces wrong gameplay but must
# not produce NaN, Inf, or crash. An implementation that does not guard the
# clamp assignment against the sign could produce unexpected results but must
# remain numerically finite.
# CHECKPOINT
# ---------------------------------------------------------------------------

func test_j010_jump_cut_velocity_positive_result_is_finite_not_nan() -> void:
	# CHECKPOINT
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_cut_velocity = 50.0  # nonsensical: positive cut velocity
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -100.0, false)
	# After gravity: -100 + 15.68 = -84.32. -84.32 < 50.0 is TRUE → clamp to 50.0
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(not is_nan(result.velocity.y),
		"TB-J-010 — positive jump_cut_velocity=50: result.vy is not NaN")
	_assert_true(is_finite(result.velocity.y),
		"TB-J-010 — positive jump_cut_velocity=50: result.vy is finite")
	# The clamp should apply: result.vy == 50.0 (since -84.32 < 50.0)
	_assert_approx(result.velocity.y, 50.0,
		"TB-J-010 — positive jump_cut_velocity=50: -84.32 < 50.0 → clamped to 50.0")


func test_j010b_jump_cut_velocity_positive_falling_character_also_clamped() -> void:
	# With positive cut velocity, even a falling character (vy > 0) gets clamped if vy < cut.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.jump_cut_velocity = 200.0  # nonsensical large positive
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 100.0, false)
	# After gravity: 100 + 15.68 = 115.68. 115.68 < 200.0 → TRUE → clamp to 200.0
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result.velocity.y),
		"TB-J-010b — positive cut_vel=200, falling vy=100: result.vy is finite")
	_assert_approx(result.velocity.y, 200.0,
		"TB-J-010b — positive cut_vel=200: 115.68 < 200.0 → clamped to 200.0")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-011 — Multiple consecutive simulate() calls with
# jump_just_pressed=true: only the first frame fires
#
# VULNERABILITY: In a real engine scenario, jump_just_pressed is only true for
# exactly one frame. However, if a test (or buggy controller) passes
# jump_just_pressed=true on multiple consecutive calls, the simulation's own
# state machine (jump_consumed) must block the second jump. This multi-frame
# sequence test validates the temporal logic of the consumed flag.
# ---------------------------------------------------------------------------

func test_j011_second_consecutive_just_pressed_blocked_by_consumed() -> void:
	var sim: MovementSimulation = MovementSimulation.new()

	# Frame 1: on floor, jump fires
	var state0: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	state0.jump_consumed = false
	state0.coyote_timer = 0.0
	var state1: MovementSimulation.MovementState = sim.simulate(state0, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# Jump fires: state1.jump_consumed == true, state1.is_on_floor == true (pass-through)

	# Frame 2: still appears "on floor" (pass-through), jump_just_pressed=true again.
	# state1.jump_consumed=true. Step 5: on_floor=true → result.jump_consumed=false (reset).
	# Step 6: eligibility reads prior_state.jump_consumed (which is TRUE) → NOT eligible.
	# Jump does NOT fire. This confirms SPEC-18 eligibility uses prior_state.jump_consumed,
	# not result.jump_consumed — so the step 5 reset does not enable a same-frame re-jump.
	var state2: MovementSimulation.MovementState = sim.simulate(state1, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# SPEC-18 uses prior_state.jump_consumed for eligibility — not result.jump_consumed.
	# state1.jump_consumed=true → step 6 sees NOT true = false → jump blocked.
	# result.velocity.y = state1.velocity.y + gravity*delta (gravity only, no impulse).
	# result.jump_consumed = false (step 5 reset by on_floor=true, step 6 not overriding).
	var expected_vy: float = state1.velocity.y + 980.0 * 0.016
	_assert_approx(state2.velocity.y, expected_vy,
		"TB-J-011 — frame2: prior consumed=true blocks re-jump even after on_floor reset")
	_assert_true(state2.jump_consumed == false,
		"TB-J-011 — frame2: jump_consumed=false (on_floor reset, no new jump fired)")


func test_j011b_second_just_pressed_while_airborne_blocked_by_consumed() -> void:
	var sim: MovementSimulation = MovementSimulation.new()

	# Frame 1: floor jump fires, player is now airborne (is_on_floor was true)
	var state0: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	state0.jump_consumed = false
	var state1: MovementSimulation.MovementState = sim.simulate(state0, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# state1: jump_consumed=true, is_on_floor=true (pass-through of prior), vy ≈ -469.29

	# Frame 2: player is now airborne (simulate with is_on_floor=false),
	# but test passes jump_just_pressed=true again (simulating a stuck key or buggy controller).
	var state1_airborne: MovementSimulation.MovementState = _make_state_with(0.0, state1.velocity.y, false)
	state1_airborne.jump_consumed = state1.jump_consumed  # true
	state1_airborne.coyote_timer = 0.0  # expired, no coyote
	var state2: MovementSimulation.MovementState = sim.simulate(state1_airborne, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# consumed=true, airborne, coyote=0 → no jump. velocity.y = prior.vy + gravity*delta
	var expected_vy: float = state1.velocity.y + 980.0 * 0.016
	_assert_approx(state2.velocity.y, expected_vy,
		"TB-J-011b — 2nd just_pressed airborne + consumed=true: no double jump")
	_assert_true(state2.jump_consumed == true,
		"TB-J-011b — consumed stays true while airborne with no new jump")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-012 — Landing detection: is_on_floor transition false→true
# resets jump_consumed on the LANDING FRAME
#
# VULNERABILITY: The spec (AC-21.3) says landing resets jump_consumed=false.
# The "landing frame" is the frame where prior_state.is_on_floor=true.
# In the engine, this means the controller set _current_state.is_on_floor=true
# after move_and_slide() on the previous physics step.
# The adversarial concern: does consumed reset on the landing frame even if
# jump_just_pressed=false? And does it reset even when consumed=true came from
# a coyote jump (not a floor jump)?
# ---------------------------------------------------------------------------

func test_j012a_landing_frame_with_just_pressed_false_resets_consumed() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 5.0, true)
	prior.jump_consumed = true  # Was airborne and jumped
	# Landing frame: on_floor=true, no jump input
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_false(result.jump_consumed,
		"TB-J-012a — landing frame (no input): jump_consumed resets to false")


func test_j012b_landing_frame_resets_consumed_even_after_coyote_jump() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# Simulate: player used a coyote jump, now consumed=true, then lands
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = true  # from a prior coyote jump
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_false(result.jump_consumed,
		"TB-J-012b — landing after coyote jump: consumed resets to false on floor frame")


func test_j012c_landing_frame_consumed_reset_then_immediate_jump_blocked() -> void:
	# CHECKPOINT (corrected): Sequence correctness — on a frame where prior.is_on_floor=true
	# AND prior.jump_consumed=true AND jump_just_pressed=true:
	# Step 5: jump_consumed resets to false (on floor) in RESULT.
	# Step 6: eligibility reads prior_state.jump_consumed (TRUE) → NOT eligible.
	# Jump does NOT fire. The on-floor reset enables jumping on the NEXT frame, not this one.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = true
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# No jump: result.vy = prior.vy + gravity*delta = 0.0 + 15.68 = 15.68
	var expected_vy: float = prior.velocity.y + 980.0 * 0.016
	_assert_approx(result.velocity.y, expected_vy,
		"TB-J-012c — landing + just_pressed=true: consumed reset then new jump fires")
	_assert_true(result.jump_consumed == false,
		"TB-J-012c — after immediate re-jump on landing frame: consumed=true again")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-013 — State immutability: prior_state fields not mutated
# under adversarial patterns
#
# VULNERABILITY: The primary suite tests immutability for specific scenarios.
# The adversarial suite tests it under edge cases that might trigger
# in-place mutation: coyote jump frame, large delta, jump cut, zero height.
# ---------------------------------------------------------------------------

func test_j013a_prior_state_coyote_timer_not_mutated_on_coyote_jump_frame() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.coyote_timer = 0.05
	prior.jump_consumed = false
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_approx(prior.coyote_timer, 0.05,
		"TB-J-013a — prior.coyote_timer not mutated on coyote jump frame")


func test_j013b_prior_state_jump_consumed_not_mutated_after_landing_reset() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = true
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	# Result resets consumed to false, but prior must still be true
	_assert_true(prior.jump_consumed == true,
		"TB-J-013b — prior.jump_consumed not mutated even when result resets it to false")


func test_j013c_prior_state_velocity_not_mutated_on_jump_frame() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var original_vy: float = prior.velocity.y
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_approx(prior.velocity.y, original_vy,
		"TB-J-013c — prior.velocity.y not mutated by jump impulse in simulate()")


func test_j013d_prior_state_is_on_floor_not_mutated_during_jump_processing() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior.jump_consumed = false
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_true(prior.is_on_floor == true,
		"TB-J-013d — prior.is_on_floor not mutated by simulate() even on jump frame")


func test_j013e_prior_state_not_mutated_with_very_large_delta() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(100.0, -300.0, false)
	prior.coyote_timer = 0.08
	prior.jump_consumed = false
	var original_ct: float = prior.coyote_timer
	var original_vy: float = prior.velocity.y
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, true, false, false, 0.0, [false, false], 10.0)
	_assert_approx(prior.coyote_timer, original_ct,
		"TB-J-013e — prior.coyote_timer not mutated with large delta=10.0")
	_assert_approx(prior.velocity.y, original_vy,
		"TB-J-013e — prior.velocity.y not mutated with large delta=10.0")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-014 — coyote_timer expires over multiple frames: jump blocked
# after window exhausted
#
# VULNERABILITY: This sequence test simulates a player walking off a ledge,
# then pressing jump after the coyote window expires. The multi-step scenario
# ensures the timer correctly drains across frames and the jump is blocked on
# the frame where the window has just closed.
# ---------------------------------------------------------------------------

func test_j014_coyote_window_expires_over_frames_jump_then_blocked() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# sim.coyote_time = 0.1 (default). We'll use delta=0.016 per frame.
	# Frame 0: departure — prior.is_on_floor=true → result.coyote_timer=0.1
	var s0: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	s0.jump_consumed = false
	var s1: MovementSimulation.MovementState = sim.simulate(s0, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(s1.coyote_timer, 0.1,
		"TB-J-014 — departure frame: coyote_timer reset to 0.1")

	# Frames 1–6: airborne, no jump. Each frame decrements by 0.016.
	# After 6 frames: 0.1 - 6*0.016 = 0.1 - 0.096 = 0.004 (still > 0, barely eligible)
	var current: MovementSimulation.MovementState = _make_state_with(0.0, s1.velocity.y, false)
	current.coyote_timer = s1.coyote_timer
	current.jump_consumed = s1.jump_consumed
	for i in range(6):
		var next: MovementSimulation.MovementState = sim.simulate(current, 0.0, false, false, false, 0.0, [false, false], 0.016)
		current = _make_state_with(0.0, next.velocity.y, false)
		current.coyote_timer = next.coyote_timer
		current.jump_consumed = next.jump_consumed

	# After 6 frames: coyote_timer ≈ 0.004 (still > 0, so jump should fire)
	_assert_true(current.coyote_timer > 0.0,
		"TB-J-014 — after 6 frames: coyote_timer > 0 (barely eligible)")
	var result_eligible: MovementSimulation.MovementState = sim.simulate(current, 0.0, true, true, false, 0.0, [false, false], 0.016)
	var expected_vy: float = -sqrt(2.0 * 980.0 * 120.0) + 980.0 * 0.016
	_assert_approx(result_eligible.velocity.y, expected_vy,
		"TB-J-014 — coyote jump fires when timer barely > 0 after 6 airborne frames")

	# Now simulate until coyote_timer reaches exactly 0
	# From 0.004 with delta=0.016: max(0, 0.004 - 0.016) = 0.0
	var s_expired: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	s_expired.coyote_timer = 0.004
	s_expired.jump_consumed = false
	var s_after_expiry: MovementSimulation.MovementState = sim.simulate(s_expired, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(s_after_expiry.coyote_timer, 0.0,
		"TB-J-014 — timer expires (0.004 - 0.016 = 0.0 clamped)")

	# Jump attempt with expired timer: must be blocked
	var s_blocked: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	s_blocked.coyote_timer = 0.0
	s_blocked.jump_consumed = false
	var result_blocked: MovementSimulation.MovementState = sim.simulate(s_blocked, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_approx(result_blocked.velocity.y, 0.0 + 980.0 * 0.016,
		"TB-J-014 — jump blocked when coyote_timer=0.0 (expired window)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-015 — Config mutation between calls (coyote_time and jump_height)
#
# VULNERABILITY: Changing sim.coyote_time or sim.jump_height between calls must
# take effect immediately on the next call. An implementation that caches these
# values at initialization time (e.g., stored in a local variable in _init())
# would miss the mutation. This mirrors the existing M1-001 TB-008 pattern.
# ---------------------------------------------------------------------------

func test_j015a_coyote_time_mutation_takes_effect_immediately() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# First call: default coyote_time=0.1 → on floor, timer resets to 0.1
	var prior1: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var result1: MovementSimulation.MovementState = sim.simulate(prior1, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result1.coyote_timer, 0.1,
		"TB-J-015a — before mutation: on-floor reset gives coyote_timer=0.1")

	# Mutate coyote_time after first call
	sim.coyote_time = 0.25
	var prior2: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var result2: MovementSimulation.MovementState = sim.simulate(prior2, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result2.coyote_timer, 0.25,
		"TB-J-015a — after mutation to 0.25: on-floor reset gives coyote_timer=0.25")


func test_j015b_jump_height_mutation_takes_effect_immediately() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# First jump with default height
	var prior1: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior1.jump_consumed = false
	var result1: MovementSimulation.MovementState = sim.simulate(prior1, 0.0, true, true, false, 0.0, [false, false], 0.0)
	var impulse1: float = result1.velocity.y  # delta=0 isolates impulse

	# Mutate jump_height
	sim.jump_height = 30.0
	var prior2: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior2.jump_consumed = false
	var result2: MovementSimulation.MovementState = sim.simulate(prior2, 0.0, true, true, false, 0.0, [false, false], 0.0)
	var impulse2: float = result2.velocity.y
	var expected_impulse2: float = -sqrt(2.0 * 980.0 * 30.0)

	_assert_approx(impulse2, expected_impulse2,
		"TB-J-015b — jump_height mutated to 30.0: new impulse = -sqrt(2*980*30)")
	_assert_true(impulse1 != impulse2,
		"TB-J-015b — mutated jump_height produces different impulse than original")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-016 — Coyote jump sets jump_consumed=true, preventing immediate
# re-jump even from coyote eligibility on the next frame
#
# VULNERABILITY: After a coyote jump fires, jump_consumed=true. On the next
# airborne frame, even if coyote_timer was not yet fully decremented (still
# residually > 0 in prior result), the consumed flag must block a second
# coyote jump. An implementation that forgets to check jump_consumed when
# is_on_floor=false would allow a double-coyote-jump.
# ---------------------------------------------------------------------------

func test_j016_coyote_jump_sets_consumed_blocks_second_coyote_attempt() -> void:
	var sim: MovementSimulation = MovementSimulation.new()

	# Frame 1: coyote jump fires
	var s0: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	s0.coyote_timer = 0.05
	s0.jump_consumed = false
	var s1: MovementSimulation.MovementState = sim.simulate(s0, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# Jump fires: s1.jump_consumed=true, s1.coyote_timer = max(0, 0.05-0.016) = 0.034
	_assert_true(s1.jump_consumed == true,
		"TB-J-016 — coyote jump frame: jump_consumed=true")
	_assert_approx(s1.coyote_timer, 0.034,
		"TB-J-016 — coyote jump frame: coyote_timer decremented to 0.034")

	# Frame 2: still airborne, coyote_timer=0.034>0, but consumed=true → must block
	var s1_carry: MovementSimulation.MovementState = _make_state_with(0.0, s1.velocity.y, false)
	s1_carry.coyote_timer = s1.coyote_timer  # 0.034 > 0
	s1_carry.jump_consumed = s1.jump_consumed  # true
	var s2: MovementSimulation.MovementState = sim.simulate(s1_carry, 0.0, true, true, false, 0.0, [false, false], 0.016)
	# consumed=true blocks jump even with coyote_timer=0.034>0
	var expected_vy: float = s1.velocity.y + 980.0 * 0.016
	_assert_approx(s2.velocity.y, expected_vy,
		"TB-J-016 — frame after coyote jump: consumed=true blocks second coyote attempt")
	_assert_true(s2.jump_consumed == true,
		"TB-J-016 — consumed remains true in air after blocked second coyote attempt")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-017 — Determinism: identical adversarial inputs produce
# identical outputs across multiple calls
#
# VULNERABILITY: Confirms the simulation has no hidden mutable internal state
# that would cause different results for identical inputs called sequentially.
# Especially relevant if any implementation accidentally stores frame-specific
# scratch variables as instance fields.
# ---------------------------------------------------------------------------

func test_j017_determinism_coyote_jump_scenario() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.coyote_timer = 0.05
	prior.jump_consumed = false

	var result_a: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)
	var result_b: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, false, 0.0, [false, false], 0.016)

	_assert_approx(result_a.velocity.y, result_b.velocity.y,
		"TB-J-017 — determinism: coyote jump produces identical velocity.y on repeat calls")
	_assert_approx(result_a.coyote_timer, result_b.coyote_timer,
		"TB-J-017 — determinism: coyote jump produces identical coyote_timer on repeat calls")
	_assert_true(result_a.jump_consumed == result_b.jump_consumed,
		"TB-J-017 — determinism: jump_consumed identical across repeat calls")


func test_j017b_determinism_jump_cut_scenario() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -450.0, false)
	prior.jump_consumed = true

	var result_a: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	var result_b: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)

	_assert_approx(result_a.velocity.y, result_b.velocity.y,
		"TB-J-017b — determinism: jump cut produces identical velocity.y on repeat calls")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-018 — Negative coyote_time config: timer behavior
#
# VULNERABILITY: negative coyote_time is undefined behavior per spec. On the
# floor frame, result.coyote_timer = self.coyote_time = negative value, which
# is never > 0.0, so no coyote jumps are possible. The result must be finite
# and not NaN. Also: with a negative coyote_time reset, the airborne decrement
# max(0.0, negative - delta) = 0.0, so it clamps immediately.
# CHECKPOINT
# ---------------------------------------------------------------------------

func test_j018_negative_coyote_time_produces_finite_timer_no_coyote_window() -> void:
	# CHECKPOINT
	var sim: MovementSimulation = MovementSimulation.new()
	sim.coyote_time = -0.1  # negative: undefined behavior but must not crash
	var prior_floor: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	prior_floor.jump_consumed = false
	var result_floor: MovementSimulation.MovementState = sim.simulate(prior_floor, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result_floor.coyote_timer),
		"TB-J-018 — negative coyote_time: result.coyote_timer is finite on floor frame")
	# result.coyote_timer = coyote_time = -0.1 (negative). Not > 0.0 → no coyote window.
	_assert_false(result_floor.coyote_timer > 0.0,
		"TB-J-018 — negative coyote_time: timer not > 0.0 (no coyote window)")

	# Airborne frame with negative prior coyote_timer: max(0, -0.1 - delta) = 0.0
	var prior_air: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior_air.coyote_timer = -0.1
	prior_air.jump_consumed = false
	var result_air: MovementSimulation.MovementState = sim.simulate(prior_air, 0.0, true, true, false, 0.0, [false, false], 0.016)
	_assert_approx(result_air.coyote_timer, 0.0,
		"TB-J-018 — negative timer, airborne: max(0, -0.1 - 0.016) = 0.0 (clamped)")
	# No coyote jump: prior.coyote_timer = -0.1, which is NOT > 0.0
	var expected_vy: float = 0.0 + 980.0 * 0.016
	_assert_approx(result_air.velocity.y, expected_vy,
		"TB-J-018 — negative coyote_timer in prior: no coyote jump (not > 0.0)")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-019 — Jump with horizontal movement simultaneously
#
# VULNERABILITY: Confirms jump impulse is applied only to velocity.y and does
# not accidentally interact with the horizontal velocity calculation. An
# implementation that erroneously applies some impulse component to velocity.x
# (e.g., from a copy-paste bug) would fail this test.
# ---------------------------------------------------------------------------

func test_j019_horizontal_velocity_independent_of_jump_impulse() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# Player moving right at max speed while jumping
	var prior: MovementSimulation.MovementState = _make_state_with(200.0, 0.0, true)
	prior.jump_consumed = false
	# Full right input, jump held
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, true, true, false, 0.0, [false, false], 0.016)
	# Horizontal: on_floor + input_axis=1.0, max_speed=200.0, acceleration=800.0
	# step = acceleration * delta = 800 * 0.016 = 12.8. move_toward(200, 200, 12.8) = 200.0
	_assert_approx(result.velocity.x, 200.0,
		"TB-J-019 — horizontal at max_speed unaffected by simultaneous jump impulse")
	# Vertical: jump impulse applied
	var expected_vy: float = -sqrt(2.0 * 980.0 * 120.0) + 980.0 * 0.016
	_assert_approx(result.velocity.y, expected_vy,
		"TB-J-019 — vertical jump impulse unaffected by horizontal movement")


# ---------------------------------------------------------------------------
# [M1-002] TB-J-020 — Jump cut does not apply to horizontal velocity
#
# VULNERABILITY: The jump cut condition clamps result.velocity.y only. An
# implementation with a copy-paste error might accidentally clamp velocity.x
# using the same condition. This test confirms velocity.x is unchanged by
# jump cut logic.
# ---------------------------------------------------------------------------

func test_j020_jump_cut_does_not_affect_velocity_x() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# Ascending fast horizontally — jump cut should only touch velocity.y
	var prior: MovementSimulation.MovementState = _make_state_with(180.0, -450.0, false)
	prior.jump_consumed = true
	# jump_pressed=false → cut condition: -450+15.68=-434.32 < -200 → clamp vy to -200
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	# Horizontal: airborne + input=1.0, air_decel=0.0, accel=800: step=12.8, target=200.0
	# move_toward(180, 200, 12.8) = 192.8
	_assert_approx(result.velocity.x, 192.8,
		"TB-J-020 — jump cut does not affect velocity.x (horizontal = 192.8 from accel)")
	_assert_approx(result.velocity.y, -200.0,
		"TB-J-020 — jump cut clamps velocity.y to -200.0 as expected")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

func run_all() -> int:
	print("--- test_jump_simulation_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	# TB-J-001: simultaneous just_pressed=true + pressed=false
	test_j001_simultaneous_just_pressed_true_pressed_false_jump_then_cut()
	test_j002_normal_hold_jump_pressed_and_just_pressed_both_true_no_cut()
	test_j002b_single_frame_tap_custom_cut_velocity_clamps_correctly()

	# TB-J-003: coyote_timer boundary vs. delta
	test_j003_coyote_timer_exactly_equals_delta_jump_still_fires()
	test_j003b_coyote_timer_slightly_above_delta_timer_decrements_to_positive()
	test_j003c_coyote_timer_slightly_below_delta_clamped_to_zero()

	# TB-J-004: very large delta
	test_j004a_very_large_delta_clamps_coyote_timer_to_zero()
	test_j004b_very_large_delta_jump_still_fires_from_prior_positive_coyote_timer()

	# TB-J-005: jump_height = 0.0
	test_j005a_jump_height_zero_produces_zero_impulse_not_nan()
	test_j005b_jump_height_zero_velocity_equals_gravity_only()
	test_j005c_jump_height_zero_jump_consumed_still_set_true()

	# TB-J-006: jump_height negative
	test_j006_negative_jump_height_velocity_y_is_finite_not_nan()

	# TB-J-007: gravity=0 + jump_height=0 dual zero
	test_j007_gravity_zero_and_jump_height_zero_both_produce_zero_velocity_y()

	# TB-J-008: coyote_time=0.0 departure and first airborne frame
	test_j008a_coyote_time_zero_departure_frame_timer_resets_to_zero()
	test_j008b_coyote_time_zero_first_airborne_frame_no_coyote_jump()

	# TB-J-009: jump_cut_velocity=0.0
	test_j009a_jump_cut_velocity_zero_small_negative_vy_clamped()
	test_j009b_jump_cut_velocity_zero_positive_vy_not_clamped()
	test_j009c_jump_cut_velocity_zero_exact_zero_after_gravity_not_clamped()

	# TB-J-010: jump_cut_velocity positive (nonsensical)
	test_j010_jump_cut_velocity_positive_result_is_finite_not_nan()
	test_j010b_jump_cut_velocity_positive_falling_character_also_clamped()

	# TB-J-011: consecutive just_pressed calls
	test_j011_second_consecutive_just_pressed_blocked_by_consumed()
	test_j011b_second_just_pressed_while_airborne_blocked_by_consumed()

	# TB-J-012: landing detection resets consumed
	test_j012a_landing_frame_with_just_pressed_false_resets_consumed()
	test_j012b_landing_frame_resets_consumed_even_after_coyote_jump()
	test_j012c_landing_frame_consumed_reset_then_immediate_jump_blocked()

	# TB-J-013: state immutability under adversarial patterns
	test_j013a_prior_state_coyote_timer_not_mutated_on_coyote_jump_frame()
	test_j013b_prior_state_jump_consumed_not_mutated_after_landing_reset()
	test_j013c_prior_state_velocity_not_mutated_on_jump_frame()
	test_j013d_prior_state_is_on_floor_not_mutated_during_jump_processing()
	test_j013e_prior_state_not_mutated_with_very_large_delta()

	# TB-J-014: coyote window expiration multi-frame sequence
	test_j014_coyote_window_expires_over_frames_jump_then_blocked()

	# TB-J-015: config mutation takes effect immediately
	test_j015a_coyote_time_mutation_takes_effect_immediately()
	test_j015b_jump_height_mutation_takes_effect_immediately()

	# TB-J-016: coyote jump blocks immediate second coyote attempt
	test_j016_coyote_jump_sets_consumed_blocks_second_coyote_attempt()

	# TB-J-017: determinism
	test_j017_determinism_coyote_jump_scenario()
	test_j017b_determinism_jump_cut_scenario()

	# TB-J-018: negative coyote_time config
	test_j018_negative_coyote_time_produces_finite_timer_no_coyote_window()

	# TB-J-019: horizontal independence from jump impulse
	test_j019_horizontal_velocity_independent_of_jump_impulse()

	# TB-J-020: jump cut does not affect horizontal velocity
	test_j020_jump_cut_does_not_affect_velocity_x()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count
