# test_movement_simulation_adversarial.gd
#
# Adversarial extension of the movement simulation test suite.
# Generated by Test Breaker Agent — 2026-02-28.
#
# This file targets gaps, blind spots, and boundary conditions NOT covered by
# the 46-test baseline in test_movement_simulation.gd. Every test includes a
# comment explaining the specific vulnerability it probes.
#
# Spec coverage targeted:
#   SPEC-3  — Config parameter boundary values (zero, negative)
#   SPEC-4  — simulate() API: negative delta, NaN/Inf inputs, prior_state immutability
#   SPEC-5  — Horizontal movement: sign flipping, velocity beyond max_speed, steady-state
#   SPEC-6  — Vertical movement: negative vy (jump arc), gravity=0.0
#   SPEC-12 — Frame-rate independence: very large delta, exact-step boundary
#
# Checkpoint log:
#   [M1-001] TB-001 — NaN/Inf input_axis handling
#   [M1-001] TB-002 — Negative delta behavior
#   [M1-001] TB-003 — Zero config parameters (max_speed, acceleration, friction, gravity)
#   [M1-001] TB-004 — Prior state is_on_floor field not mutated by simulate()
#   [M1-001] TB-005 — Velocity exceeding max_speed as prior state (deceleration direction)
#   [M1-001] TB-006 — Sign reversal in a single frame (full-speed right → full-input left)
#   [M1-001] TB-007 — Negative velocity.y (upward motion) gravity accumulation
#   [M1-001] TB-008 — Config mutation between simulate() calls takes effect immediately
#   [M1-001] TB-009 — Steady-state at max_speed with continuous input
#   [M1-001] TB-010 — Air deceleration with negative velocity.x
#   [M1-001] TB-011 — Very large delta does not overshoot beyond target (move_toward cap)
#   [M1-001] TB-012 — Exact-step boundary: acceleration step equals remaining distance
#   [M1-001] TB-013 — Negative config values produce reversed/unexpected but non-crashing behavior
#   TB-014–018 — test_movement_simulation_adversarial_2.gd (file size split)

class_name MovementSimulationAdversarialTests
extends "res://tests/utils/test_utils.gd"

const EPSILON: float = 1e-4

var _pass_count: int = 0
var _fail_count: int = 0


func _make_state_with(vx: float, vy: float, on_floor: bool) -> MovementSimulation.MovementState:
	var s: MovementSimulation.MovementState = MovementSimulation.MovementState.new()
	s.velocity = Vector2(vx, vy)
	s.is_on_floor = on_floor
	return s


# ---------------------------------------------------------------------------
# [M1-001] TB-001 — NaN / Inf input_axis handling
#
# VULNERABILITY: The spec says input_axis behavior is only defined for [-1.0,
# 1.0]. If an implementation passes NaN or Inf directly into move_toward()
# without clamping, GDScript propagates NaN/Inf through arithmetic and the
# resulting velocity.x becomes NaN/Inf. This silently corrupts all future
# simulation state. These tests expose an implementation that does not sanitize
# input_axis before use.
#
# CHECKPOINT [M1-001] TB-001 — NaN/Inf input_axis handling
# Would have asked: Should simulate() silently clamp input_axis to [-1, 1],
# or should NaN/Inf produce deterministic (but possibly wrong) output, or
# should it be treated as 0.0 (safest default)?
# Assumption made: The conservative safe behavior is that NaN/Inf input_axis
# must NOT produce NaN/Inf in the output velocity. The spec guarantees the
# simulation is only called with valid input from the controller, so this is
# a robustness / defensive-programming test. We encode the assumption that
# NaN/Inf input must not propagate into output velocity.
# Confidence: Medium
# ---------------------------------------------------------------------------

func test_tb001_nan_input_axis_does_not_produce_nan_velocity_x() -> void:
	# CHECKPOINT: see TB-001 above
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var nan_axis: float = 0.0 / 0.0  # GDScript produces NaN
	var result: MovementSimulation.MovementState = sim.simulate(prior, nan_axis, false, false, false, 0.0, [false, false], 0.016)
	# A robust implementation clamps or guards input_axis so velocity.x is finite.
	# If this fails, the implementation blindly passes NaN into move_toward().
	_assert_true(not is_nan(result.velocity.x),
		"tb001 — NaN input_axis must not produce NaN velocity.x")


func test_tb001_inf_input_axis_does_not_produce_inf_velocity_x() -> void:
	# CHECKPOINT: see TB-001 above
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var inf_axis: float = INF
	var result: MovementSimulation.MovementState = sim.simulate(prior, inf_axis, false, false, false, 0.0, [false, false], 0.016)
	# move_toward(0.0, INF * 200.0, 12.8) = 12.8 in GDScript (move_toward step-limits).
	# However, a naive impl that sets target = INF * max_speed may produce INF.
	_assert_true(is_finite(result.velocity.x),
		"tb001 — INF input_axis must not produce INF velocity.x")


func test_tb001_negative_inf_input_axis_does_not_produce_neg_inf_velocity_x() -> void:
	# CHECKPOINT: see TB-001 above
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var neg_inf_axis: float = -INF
	var result: MovementSimulation.MovementState = sim.simulate(prior, neg_inf_axis, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result.velocity.x),
		"tb001 — -INF input_axis must not produce -INF velocity.x")


# ---------------------------------------------------------------------------
# [M1-001] TB-002 — Negative delta behavior
#
# VULNERABILITY: The spec explicitly states delta=0.0 is valid and must not
# cause errors, but it says nothing about negative delta. A naive impl passes
# `rate * delta` (negative) to move_toward(), which causes move_toward to
# move AWAY from the target (since GDScript move_toward treats the step as an
# absolute magnitude, but a negative step is clamped to 0 by move_toward in
# Godot 4 — this is unverified behavior). The velocity.y case is more
# dangerous: `gravity * negative_delta` subtracts from vy, effectively
# reversing gravity for one frame.
#
# CHECKPOINT [M1-001] TB-002 — Negative delta behavior
# Would have asked: Is negative delta explicitly undefined behavior and
# therefore untested, or should simulate() guard against it?
# Assumption made: Negative delta is undefined per the spec. The conservative
# assumption is that it must not corrupt state worse than zero delta — i.e.,
# velocity should not become more extreme (further from target) than prior
# state. We test that negative delta produces velocity changes no larger in
# magnitude than zero delta. This is a robustness gate, not a correctness gate.
# Confidence: Low
# ---------------------------------------------------------------------------

func test_tb002_negative_delta_does_not_move_velocity_x_away_from_target() -> void:
	# CHECKPOINT: see TB-002 above
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	# With positive input (target = 200.0), a negative delta should not produce
	# a negative velocity.x (moving away from 200.0 past zero).
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], -0.016)
	# Conservative: result.velocity.x should be between prior (0.0) and target (200.0),
	# or at least not be MORE negative than prior.velocity.x.
	_assert_true(result.velocity.x >= -EPSILON,
		"tb002 — negative delta with positive input should not produce negative velocity.x")


func test_tb002_negative_delta_does_not_add_upward_gravity() -> void:
	# CHECKPOINT: see TB-002 above
	# gravity * (-delta) subtracts from vy, which would mean "anti-gravity" for one frame.
	# From vy=0.0 and gravity=980.0, a negative delta of -0.016 gives vy = -15.68
	# (upward impulse). This should not happen — velocity.y should not decrease
	# from its prior value due to a negative delta physics step.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], -0.016)
	_assert_true(result.velocity.y >= prior.velocity.y - EPSILON,
		"tb002 — negative delta must not produce upward (negative) gravity contribution")


# ---------------------------------------------------------------------------
# [M1-001] TB-003 — Zero config parameter boundaries
#
# VULNERABILITY: The spec says all parameters must be non-negative and notes
# negative values are undefined behavior. Zero is the boundary and IS defined
# behavior. No existing test covers zero values for max_speed, acceleration,
# friction, or gravity.
# ---------------------------------------------------------------------------

func test_tb003_max_speed_zero_keeps_velocity_x_at_zero_from_rest() -> void:
	# With max_speed=0.0, the target velocity is always 0.0 * input_axis = 0.0.
	# From rest, applying acceleration toward target=0.0 should keep vx at 0.0.
	# VULNERABILITY: An impl using `clamp(result, -max_speed, max_speed)` would
	# correctly produce 0.0. An impl relying solely on move_toward capping at target
	# also produces 0.0. Both are correct. This test verifies zero max_speed.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_speed = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, 0.0,
		"tb003 — max_speed=0.0: velocity.x from rest stays 0.0 despite positive input")


func test_tb003_max_speed_zero_decelerates_existing_velocity_to_zero() -> void:
	# If max_speed=0.0 and velocity.x=100.0 (perhaps carried from a previous frame
	# before the parameter was changed), the target is 0.0 and acceleration
	# moves velocity TOWARD zero. This tests that the simulation does not freeze
	# at the existing velocity when max_speed is set to zero.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_speed = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(100.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	# target = 1.0 * 0.0 = 0.0; step = 800 * 0.016 = 12.8
	# move_toward(100.0, 0.0, 12.8) = 87.2
	_assert_approx(result.velocity.x, 87.2,
		"tb003 — max_speed=0.0: positive velocity decelerates toward 0.0 at acceleration rate")


func test_tb003_acceleration_zero_keeps_velocity_x_unchanged_grounded_input() -> void:
	# acceleration=0.0 means step=0.0 → move_toward returns from unchanged.
	# A common bug: dividing by acceleration or treating 0 specially could break this.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.acceleration = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(75.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, 75.0,
		"tb003 — acceleration=0.0: velocity.x unchanged when grounded with input")


func test_tb003_acceleration_zero_keeps_velocity_x_unchanged_airborne_input() -> void:
	# Same zero-acceleration test but airborne. This uses the same formula path as
	# grounded-with-input (AC-5.3), but some impls may use a different air_acceleration
	# variable incorrectly.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.acceleration = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(50.0, 0.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, 50.0,
		"tb003 — acceleration=0.0: velocity.x unchanged when airborne with input")


func test_tb003_friction_zero_keeps_velocity_x_unchanged_grounded_no_input() -> void:
	# friction=0.0 means step=0.0 → velocity preserved. A subtle bug: if an impl
	# applies air_deceleration on floor when friction is zero (guard logic error),
	# the velocity would wrongly change.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.friction = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(80.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, 80.0,
		"tb003 — friction=0.0: velocity.x preserved when grounded with no input")


func test_tb003_gravity_zero_keeps_velocity_y_unchanged() -> void:
	# gravity=0.0 means vy stays constant each frame. A hardcoded constant in the
	# gravity formula (e.g., `vy += 980.0 * delta` instead of `vy += gravity * delta`)
	# would fail this test because the formula would use the default 980.0 even when
	# gravity is set to 0.0.
	# VULNERABILITY: This directly catches implementations that hardcode the gravity
	# constant instead of reading from the exported parameter.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.gravity = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 50.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.y, 50.0,
		"tb003 — gravity=0.0: velocity.y unchanged (gravity param used, not hardcoded 980)")


# ---------------------------------------------------------------------------
# [M1-001] TB-004 — Prior state is_on_floor field not mutated by simulate()
#
# VULNERABILITY: The existing tests verify that velocity fields of prior_state
# are not mutated (test_spec4_prior_state_velocity_x_not_mutated and
# test_spec4_prior_state_velocity_y_not_mutated). However, NO existing test
# verifies that prior_state.is_on_floor is not mutated. The SPEC-8 design
# intentionally mutates _current_state.is_on_floor in the controller layer —
# a confused implementer might put that mutation inside simulate() instead,
# causing prior_state.is_on_floor to be modified as a side effect.
# ---------------------------------------------------------------------------

func test_tb004_prior_state_is_on_floor_not_mutated_when_passed_true() -> void:
	# VULNERABILITY: simulate() could write result.is_on_floor back to prior_state
	# (e.g., a mistake like `prior_state.is_on_floor = result.is_on_floor`).
	# Passing is_on_floor=true and checking it remains true after simulate() only
	# catches the case where simulate() unconditionally zeroes the field. We need
	# to also test the case where simulate() could flip it.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(prior.is_on_floor == true,
		"tb004 — prior_state.is_on_floor=true not mutated by simulate()")


func test_tb004_prior_state_is_on_floor_not_mutated_when_passed_false() -> void:
	# A simulate() that mistakenly writes is_on_floor=true to prior_state
	# would fail this test.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(prior.is_on_floor == false,
		"tb004 — prior_state.is_on_floor=false not mutated by simulate()")


# ---------------------------------------------------------------------------
# [M1-001] TB-005 — Velocity.x exceeding max_speed as prior state
#
# VULNERABILITY: The spec guarantees abs(velocity.x) never exceeds max_speed
# AFTER simulate(), but it does not explicitly say what happens when the PRIOR
# state's velocity.x already exceeds max_speed (e.g., because a previous frame
# used a higher max_speed, or because the controller set velocity directly).
#
# With grounded + input: the target is input_axis * max_speed. If prior vx
# exceeds max_speed positively and input is positive, move_toward moves FROM
# the high positive value TOWARD the (lower) positive target. This is correct
# deceleration behavior.
#
# CHECKPOINT [M1-001] TB-005 — velocity beyond max_speed as prior state
# Would have asked: When prior velocity.x > max_speed and input direction
# matches velocity direction, should simulate() accelerate further or decelerate
# toward max_speed?
# Assumption made: move_toward behavior is the only mechanism. If vx=300.0,
# max_speed=DEFAULT_MAX_SPEED, and input_axis=1.0, target=DEFAULT_MAX_SPEED and move_toward moves
# toward target (decelerating). This is the natural and correct behavior.
# Confidence: High
# ---------------------------------------------------------------------------

func test_tb005_velocity_x_above_max_speed_decelerates_with_positive_input() -> void:
	# Prior vx = 300.0 (exceeds sim.max_speed / DEFAULT_MAX_SPEED), input_axis=1.0, grounded.
	var sim: MovementSimulation = MovementSimulation.new()
	var step: float = sim.acceleration * 0.016
	var prior_vx: float = 300.0
	var prior: MovementSimulation.MovementState = _make_state_with(prior_vx, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, prior_vx - step,
		"tb005 — vx>max_speed with positive input: decelerates toward max_speed")


func test_tb005_velocity_x_above_max_speed_does_not_exceed_prior_when_input_matches() -> void:
	# Critical invariant: if vx already exceeds max_speed in the input direction,
	# a single simulate() frame should not make it MORE extreme.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(300.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(result.velocity.x <= prior.velocity.x + EPSILON,
		"tb005 — vx>max_speed with matching input: result.vx must not exceed prior.vx")


func test_tb005_velocity_x_far_below_neg_max_speed_decelerates_with_negative_input() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var step: float = sim.acceleration * 0.016
	var prior_vx: float = -300.0
	var prior: MovementSimulation.MovementState = _make_state_with(prior_vx, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, prior_vx + step,
		"tb005 — vx<-max_speed with negative input: decelerates toward -max_speed")


# ---------------------------------------------------------------------------
# [M1-001] TB-006 — Sign reversal (full-speed right, then full-input left)
#
# VULNERABILITY: The most common movement feel bug is incorrect behavior when
# reversing direction. At vx=DEFAULT_MAX_SPEED (max speed right), applying input_axis=-1.0:
# target = -max_speed. Step = acceleration * delta.
# This should NOT overshoot through zero or produce positive velocity.
# ---------------------------------------------------------------------------

func test_tb006_full_speed_right_then_left_input_decelerates_correctly() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var ms: float = sim.max_speed
	var step: float = sim.acceleration * 0.016
	var prior: MovementSimulation.MovementState = _make_state_with(ms, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, ms - step,
		"tb006 — reverse input at max speed: decelerates by one accel step, does not jump to negative")


func test_tb006_sign_reversal_does_not_overshoot_zero_in_one_frame() -> void:
	# At vx=5.0 (near zero) with input_axis=-1.0, step=12.8 > remaining=205.0.
	# Wait — remaining from 5.0 to -200.0 is 205.0, step=12.8 — no overshoot.
	# A more dangerous case: vx=5.0, friction step exceeds vx.
	# But here we test the acceleration (directional input) case.
	# move_toward(5.0, -200.0, 12.8) = -7.8 — crosses zero in one step.
	# This is correct behavior for move_toward. The test ensures the crossing
	# is numerically correct and does not produce an unexpected positive value.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(5.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, false, 0.0, [false, false], 0.016)
	# move_toward(5.0, -200.0, 12.8) = 5.0 - 12.8 = -7.8
	_assert_approx(result.velocity.x, -7.8,
		"tb006 — sign reversal crosses zero correctly: vx=5 with -input → -7.8")


func test_tb006_sign_reversal_stays_within_max_speed_after_crossing_zero() -> void:
	# After sign reversal, velocity should remain bounded by max_speed.
	# Run 200 frames of full left input starting from max speed right.
	var sim: MovementSimulation = MovementSimulation.new()
	var state: MovementSimulation.MovementState = _make_state_with(sim.max_speed, 0.0, true)
	for _i: int in range(200):
		state = sim.simulate(state, -1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(state.velocity.x >= -sim.max_speed - EPSILON,
		"tb006 — after sign reversal + 200 frames: velocity.x stays >= -max_speed")


# ---------------------------------------------------------------------------
# [M1-001] TB-007 — Negative velocity.y (upward jump arc) gravity accumulation
#
# VULNERABILITY: The spec says velocity.y is positive downward. A previous jump
# sets velocity.y to a large negative value (e.g., -500.0). Gravity must add
# positively each frame, reducing the magnitude of the upward velocity. An impl
# that accidentally SUBTRACTS gravity (e.g., `vy -= gravity * delta` thinking
# "down is negative") would make a jump arc forever-rising.
# ---------------------------------------------------------------------------

func test_tb007_negative_vy_increases_toward_zero_with_gravity() -> void:
	# Starting vy = -300.0 (upward motion). gravity=980, delta=0.016.
	# result.vy = -300.0 + 980.0 * 0.016 = -300.0 + 15.68 = -284.32
	# (Less negative = decelerating upward motion.)
	# jump_pressed=true to suppress jump cut, which would otherwise clamp -284.32
	# to jump_cut_velocity=-200.0 — this test is about gravity only, not jump cut.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -300.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.y, -284.32,
		"tb007 — vy=-300 (upward): gravity adds +15.68, result=-284.32 (decelerating upward)")


func test_tb007_negative_vy_never_decreases_with_positive_gravity() -> void:
	# With positive gravity, vy must always be >= prior vy (it only increases or stays same).
	# A bug where gravity is subtracted would make vy more negative (wrong).
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -500.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(result.velocity.y >= prior.velocity.y - EPSILON,
		"tb007 — vy=-500 with positive gravity: result.vy must be >= prior.vy")


func test_tb007_negative_vy_eventually_becomes_positive_after_many_frames() -> void:
	# A jump that sets vy=-200.0 must eventually cross zero (peak) and become positive
	# (falling) after enough frames. This tests the full arc direction.
	# Frames to cross zero: 200.0 / (980.0 * 0.016) ≈ 12.76 frames → ~13 frames.
	var sim: MovementSimulation = MovementSimulation.new()
	var state: MovementSimulation.MovementState = _make_state_with(0.0, -200.0, false)
	for _i: int in range(20):
		state = sim.simulate(state, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(state.velocity.y > 0.0,
		"tb007 — jump arc: vy=-200 becomes positive (falling) after 20 frames of gravity")


# ---------------------------------------------------------------------------
# [M1-001] TB-008 — Config mutation between simulate() calls takes effect immediately
#
# VULNERABILITY: An implementation that caches or snapshots config parameters
# during construction (instead of reading @export vars at call time) would fail
# this test. The spec defines these as @export vars with no caching, so they
# should be read on each simulate() call.
# ---------------------------------------------------------------------------

func test_tb008_max_speed_change_takes_effect_on_next_call() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	# First frame with default max_speed: vx goes from 0 to accel*delta.
	var state: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	state = sim.simulate(state, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(state.velocity.x, 12.8,
		"tb008 — pre-change frame: velocity.x = 12.8 (baseline)")
	# Now change max_speed to 50.0. Next simulate() call should target 50.0, not DEFAULT_MAX_SPEED.
	sim.max_speed = 50.0
	state = sim.simulate(state, 1.0, false, false, false, 0.0, [false, false], 0.016)
	# move_toward(12.8, 50.0, 12.8) = 25.6 (still approaching lower target).
	# If impl cached default max_speed at construction incorrectly, discriminating tests below still catch it.
	# Use a more discriminating config: set max_speed BELOW current velocity.
	sim.max_speed = 5.0
	state = _make_state_with(50.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(state, 1.0, false, false, false, 0.0, [false, false], 0.016)
	# target = 1.0 * 5.0 = 5.0; move_toward(50.0, 5.0, 12.8) = 37.2
	_assert_approx(result.velocity.x, 37.2,
		"tb008 — max_speed changed to 5.0: target is now 5.0, vx moves from 50.0 to 37.2")


func test_tb008_gravity_change_takes_effect_on_next_call() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	# First frame: vy = 0 + 980 * 0.016 = 15.68 (default gravity).
	var result1: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result1.velocity.y, 15.68,
		"tb008 — pre-change gravity frame: vy = 15.68")
	# Change gravity to 200.0.
	sim.gravity = 200.0
	var prior2: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	var result2: MovementSimulation.MovementState = sim.simulate(prior2, 0.0, false, false, false, 0.0, [false, false], 0.016)
	# vy = 0 + 200.0 * 0.016 = 3.2
	_assert_approx(result2.velocity.y, 3.2,
		"tb008 — gravity changed to 200.0: vy = 200*0.016 = 3.2 (not 15.68)")


# ---------------------------------------------------------------------------
# [M1-001] TB-009 — Steady-state: velocity.x equals max_speed with continuous input
#
# VULNERABILITY: After enough frames of positive input, velocity.x should
# converge to EXACTLY max_speed (not slightly over, not slightly under due to
# floating-point drift). The existing test checks abs(vx) <= max_speed + EPSILON
# but does not verify the lower bound (i.e., that we actually reach max_speed,
# not just stay near it due to a clamping bug that prevents full convergence).
# ---------------------------------------------------------------------------

func test_tb009_velocity_x_converges_to_max_speed_after_sufficient_frames() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var state: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	for _i: int in range(100):
		state = sim.simulate(state, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(state.velocity.x, sim.max_speed,
		"tb009 — after 100 frames of positive input: velocity.x converges to sim.max_speed")


func test_tb009_velocity_x_converges_to_neg_max_speed_with_negative_input() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var state: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	for _i: int in range(100):
		state = sim.simulate(state, -1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(state.velocity.x, -sim.max_speed,
		"tb009 — after 100 frames of negative input: velocity.x converges to -sim.max_speed")


func test_tb009_velocity_x_reaches_zero_from_rest_after_friction_drains_it() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var state: MovementSimulation.MovementState = _make_state_with(sim.max_speed, 0.0, true)
	for _i: int in range(50):
		state = sim.simulate(state, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(state.velocity.x, 0.0,
		"tb009 — after 50 friction frames from vx=max_speed: velocity.x converges to 0.0")


# ---------------------------------------------------------------------------
# [M1-001] TB-010 — Air deceleration with negative velocity.x
#
# VULNERABILITY: The existing air_deceleration tests only cover positive vx
# (test_spec5_case4_airborne_no_input_with_air_decel uses vx=100.0). With
# air_decel > 0 and vx=-100.0, move_toward(-100.0, 0.0, step) should produce
# -93.6 (moving toward zero from the negative side). An impl that uses
# abs(vx) incorrectly or applies decel as a subtraction rather than
# move_toward would produce the wrong result.
# ---------------------------------------------------------------------------

func test_tb010_air_decel_decelerates_negative_velocity_toward_zero() -> void:
	# air_decel=400.0, vx=-100.0, delta=0.016: step=6.4.
	# move_toward(-100.0, 0.0, 6.4) = -93.6
	var sim: MovementSimulation = MovementSimulation.new()
	sim.air_deceleration = 400.0
	var prior: MovementSimulation.MovementState = _make_state_with(-100.0, 0.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, -93.6,
		"tb010 — air decel with vx=-100: move_toward(-100, 0, 6.4) = -93.6")


func test_tb010_air_decel_does_not_overshoot_zero_with_negative_velocity() -> void:
	# vx=-5.0, step=6.4 > remaining=5.0: move_toward(-5.0, 0.0, 6.4) = 0.0 (clamps).
	# A subtraction-based impl would produce -5.0 - 6.4 = -11.4 (overshoots!).
	var sim: MovementSimulation = MovementSimulation.new()
	sim.air_deceleration = 400.0
	var prior: MovementSimulation.MovementState = _make_state_with(-5.0, 0.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, 0.0,
		"tb010 — air decel with vx=-5 and step>remaining: clamps at 0.0, does not overshoot negative")


# ---------------------------------------------------------------------------
# [M1-001] TB-011 — Very large delta (stress test)
#
# VULNERABILITY: A delta of e.g. 10.0 seconds (as if the game froze for 10s)
# should not cause velocity.x to exceed max_speed in either direction, and
# velocity.y should accumulate gravity linearly without overflow for reasonable
# gravity values. The move_toward cap guarantees velocity.x safety, but an
# impl that applies a manual lerp or direct multiplication could overshoot.
# ---------------------------------------------------------------------------

func test_tb011_very_large_delta_velocity_x_does_not_exceed_max_speed() -> void:
	# delta=10.0 seconds. Step >> target distance to sim.max_speed.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 10.0)
	_assert_true(abs(result.velocity.x) <= sim.max_speed + EPSILON,
		"tb011 — very large delta (10s): velocity.x capped at max_speed by move_toward")


func test_tb011_very_large_delta_velocity_x_reaches_max_speed_in_one_step() -> void:
	# Confirms that with large delta the simulation converges immediately (not over-accelerates).
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 10.0)
	_assert_approx(result.velocity.x, sim.max_speed,
		"tb011 — very large delta: velocity.x = sim.max_speed in one frame")


func test_tb011_very_large_delta_velocity_y_is_gravity_times_delta() -> void:
	# gravity is purely additive: vy = 0 + 980.0 * 10.0 = 9800.0.
	# No clamping on vy, so this is the correct result.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 10.0)
	_assert_approx(result.velocity.y, 9800.0,
		"tb011 — very large delta (10s): velocity.y = gravity * delta = 9800.0")


func test_tb011_very_large_delta_friction_stops_at_zero() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(sim.max_speed, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 10.0)
	_assert_approx(result.velocity.x, 0.0,
		"tb011 — very large delta friction: stops exactly at 0.0, does not overshoot negative")


# ---------------------------------------------------------------------------
# [M1-001] TB-012 — Exact-step boundary: acceleration step equals remaining distance
#
# VULNERABILITY: When the acceleration step size exactly equals the distance
# to the target, the result should be exactly the target. Floating-point
# rounding could cause a tiny overshoot or undershoot. This is a classic
# boundary condition that implementations must handle correctly.
# ---------------------------------------------------------------------------

func test_tb012_acceleration_step_equals_remaining_distance_reaches_target_exactly() -> void:
	var sim: MovementSimulation = MovementSimulation.new()
	var ms: float = sim.max_speed
	var step: float = sim.acceleration * 0.016
	var prior_vx: float = ms - step
	var prior: MovementSimulation.MovementState = _make_state_with(prior_vx, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, ms,
		"tb012 — step == remaining distance: result reaches sim.max_speed exactly")


func test_tb012_friction_step_equals_remaining_distance_reaches_zero_exactly() -> void:
	# vx = 19.2, step = 1200.0 * 0.016 = 19.2. Exactly equal.
	# move_toward(19.2, 0.0, 19.2) = 0.0 exactly.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(19.2, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.x, 0.0,
		"tb012 — friction step == remaining distance: reaches 0.0 exactly")


func test_tb012_gravity_step_equals_remaining_distance_to_zero() -> void:
	# vy = -15.68 (upward), step = 980 * 0.016 = 15.68.
	# vy = -15.68 + 15.68 = 0.0 exactly (peak of arc).
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, -15.68, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_approx(result.velocity.y, 0.0,
		"tb012 — gravity step exactly cancels upward velocity: vy = 0.0 at arc peak")


# ---------------------------------------------------------------------------
# [M1-001] TB-013 — Negative config parameter values
#
# VULNERABILITY: The spec states negative parameter values are "undefined
# behavior" but does NOT say the simulation should clamp or error. A
# well-written implementation using only move_toward and arithmetic will
# produce deterministic (if strange) results. This test documents what
# SHOULD NOT happen: the simulation must not crash or produce NaN/Inf.
#
# CHECKPOINT [M1-001] TB-013 — Negative config values
# Would have asked: Should the simulation silently clamp negative parameters
# to zero at runtime, or is it purely the caller's responsibility to pass
# valid values (undefined behavior is acceptable)?
# Assumption made: Conservative assumption is that negative parameters must
# not cause NaN, Inf, or crashes — the result may be "wrong" from a gameplay
# perspective but must be numerically finite. We test for finiteness only,
# not for specific values.
# Confidence: Low
# ---------------------------------------------------------------------------

func test_tb013_negative_max_speed_does_not_crash_or_produce_nan() -> void:
	# CHECKPOINT: see TB-013 above
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_speed = -100.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result.velocity.x),
		"tb013 — negative max_speed: result.velocity.x is finite (no NaN/Inf)")


func test_tb013_negative_acceleration_does_not_crash_or_produce_nan() -> void:
	# CHECKPOINT: see TB-013 above
	# negative acceleration means move_toward step is negative.
	# move_toward(0.0, 200.0, -12.8) in Godot 4 clamps negative step to 0,
	# so result should equal prior vx. If this behavior assumption is wrong,
	# the test catches it.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.acceleration = -800.0
	var prior: MovementSimulation.MovementState = _make_state_with(50.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result.velocity.x),
		"tb013 — negative acceleration: result.velocity.x is finite (no NaN/Inf)")


func test_tb013_negative_gravity_does_not_crash_or_produce_nan() -> void:
	# CHECKPOINT: see TB-013 above
	# negative gravity would produce upward force (vy decreases each frame).
	# This is "anti-gravity" — weird but should not crash.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.gravity = -980.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result.velocity.y),
		"tb013 — negative gravity: result.velocity.y is finite (no NaN/Inf)")


func test_tb013_negative_friction_does_not_crash_or_produce_nan() -> void:
	# CHECKPOINT: see TB-013 above
	var sim: MovementSimulation = MovementSimulation.new()
	sim.friction = -1200.0
	var prior: MovementSimulation.MovementState = _make_state_with(100.0, 0.0, true)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, false, false, false, 0.0, [false, false], 0.016)
	_assert_true(is_finite(result.velocity.x),
		"tb013 — negative friction: result.velocity.x is finite (no NaN/Inf)")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

func run_all() -> int:
	print("--- test_movement_simulation_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	# TB-001: NaN/Inf input_axis
	test_tb001_nan_input_axis_does_not_produce_nan_velocity_x()
	test_tb001_inf_input_axis_does_not_produce_inf_velocity_x()
	test_tb001_negative_inf_input_axis_does_not_produce_neg_inf_velocity_x()

	# TB-002: Negative delta
	test_tb002_negative_delta_does_not_move_velocity_x_away_from_target()
	test_tb002_negative_delta_does_not_add_upward_gravity()

	# TB-003: Zero config parameter boundaries
	test_tb003_max_speed_zero_keeps_velocity_x_at_zero_from_rest()
	test_tb003_max_speed_zero_decelerates_existing_velocity_to_zero()
	test_tb003_acceleration_zero_keeps_velocity_x_unchanged_grounded_input()
	test_tb003_acceleration_zero_keeps_velocity_x_unchanged_airborne_input()
	test_tb003_friction_zero_keeps_velocity_x_unchanged_grounded_no_input()
	test_tb003_gravity_zero_keeps_velocity_y_unchanged()

	# TB-004: Prior state is_on_floor not mutated
	test_tb004_prior_state_is_on_floor_not_mutated_when_passed_true()
	test_tb004_prior_state_is_on_floor_not_mutated_when_passed_false()

	# TB-005: Velocity exceeding max_speed as prior state
	test_tb005_velocity_x_above_max_speed_decelerates_with_positive_input()
	test_tb005_velocity_x_above_max_speed_does_not_exceed_prior_when_input_matches()
	test_tb005_velocity_x_far_below_neg_max_speed_decelerates_with_negative_input()

	# TB-006: Sign reversal
	test_tb006_full_speed_right_then_left_input_decelerates_correctly()
	test_tb006_sign_reversal_does_not_overshoot_zero_in_one_frame()
	test_tb006_sign_reversal_stays_within_max_speed_after_crossing_zero()

	# TB-007: Negative velocity.y (upward jump arc)
	test_tb007_negative_vy_increases_toward_zero_with_gravity()
	test_tb007_negative_vy_never_decreases_with_positive_gravity()
	test_tb007_negative_vy_eventually_becomes_positive_after_many_frames()

	# TB-008: Config mutation between calls
	test_tb008_max_speed_change_takes_effect_on_next_call()
	test_tb008_gravity_change_takes_effect_on_next_call()

	# TB-009: Steady-state convergence
	test_tb009_velocity_x_converges_to_max_speed_after_sufficient_frames()
	test_tb009_velocity_x_converges_to_neg_max_speed_with_negative_input()
	test_tb009_velocity_x_reaches_zero_from_rest_after_friction_drains_it()

	# TB-010: Air deceleration with negative velocity
	test_tb010_air_decel_decelerates_negative_velocity_toward_zero()
	test_tb010_air_decel_does_not_overshoot_zero_with_negative_velocity()

	# TB-011: Very large delta stress test
	test_tb011_very_large_delta_velocity_x_does_not_exceed_max_speed()
	test_tb011_very_large_delta_velocity_x_reaches_max_speed_in_one_step()
	test_tb011_very_large_delta_velocity_y_is_gravity_times_delta()
	test_tb011_very_large_delta_friction_stops_at_zero()

	# TB-012: Exact-step boundary
	test_tb012_acceleration_step_equals_remaining_distance_reaches_target_exactly()
	test_tb012_friction_step_equals_remaining_distance_reaches_zero_exactly()
	test_tb012_gravity_step_equals_remaining_distance_to_zero()

	# TB-013: Negative config parameter values
	test_tb013_negative_max_speed_does_not_crash_or_produce_nan()
	test_tb013_negative_acceleration_does_not_crash_or_produce_nan()
	test_tb013_negative_gravity_does_not_crash_or_produce_nan()
	test_tb013_negative_friction_does_not_crash_or_produce_nan()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count
