#
# test_enemy_animation_controller_adversarial.gd
#
# Adversarial extension of the EnemyAnimationController test suite.
# Generated by Test Breaker Agent — 2026-03-31.
#
# This file targets gaps, blind spots, and boundary conditions NOT covered by
# the primary behavioral tests in tests/scripts/enemy/test_enemy_animation_controller.gd.
# Every test documents the specific vulnerability it probes.
#
# Ticket: project_board/7_milestone_7_enemy_animation_wiring/in_progress/animation_controller_script.md
# Requirements: ACS-3, ACS-4, ACS-5, ACS-6, ACS-7, ACS-NF1
#
# Test IDs: ADV-EAC-01 through ADV-EAC-16
#
# Checkpoint: project_board/checkpoints/M7-ACS/run-2026-04-01-testbreak.md
#
# IMPLEMENTATION NOTE: All tests use dynamic loading of the controller script so
# this file parses and runs (recording failures) even before implementation exists.
# When the implementation is absent, all tests fail with a clear diagnostic.
#

class_name EnemyAnimationControllerAdversarialTests
extends "res://tests/utils/test_utils.gd"


const _CONTROLLER_PATH: String = "res://scripts/enemies/enemy_animation_controller.gd"


# ---------------------------------------------------------------------------
# Stub: AnimationPlayer — mirrors the ACS-8 contract from the primary suite.
# Defined here independently so this file is self-contained.
# ---------------------------------------------------------------------------

class StubAnimationPlayer:
	extends Object

	var current_animation: String = ""
	var speed_scale: float = 1.0
	var last_played_name: String = ""
	var last_played_blend: float = -999.0
	var play_call_count: int = 0
	var stop_call_count: int = 0
	var _is_playing: bool = false

	func play(anim_name: String, blend_time: float = -1.0) -> void:
		last_played_name = anim_name
		last_played_blend = blend_time
		current_animation = anim_name
		_is_playing = true
		play_call_count += 1

	func stop() -> void:
		_is_playing = false
		stop_call_count += 1

	func is_playing() -> bool:
		return _is_playing

	func simulate_clip_end() -> void:
		_is_playing = false


# ---------------------------------------------------------------------------
# Stub: State machine
# ---------------------------------------------------------------------------

class StubStateMachine:
	extends Object

	var _state: String = "idle"

	func get_state() -> String:
		return _state


# ---------------------------------------------------------------------------
# Stub: Parent node (CharacterBody3D surrogate)
# ---------------------------------------------------------------------------

class StubParent:
	extends Node

	var velocity: Vector3 = Vector3.ZERO


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

var _pass_count: int = 0
var _fail_count: int = 0

var _controller_script: GDScript = null
var _load_attempted: bool = false


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

func _load_script() -> bool:
	if _load_attempted:
		return _controller_script != null
	_load_attempted = true
	_controller_script = load(_CONTROLLER_PATH) as GDScript
	return _controller_script != null


func _new_controller(test_name: String) -> Object:
	if not _load_script():
		_fail(test_name, "implementation not found at " + _CONTROLLER_PATH)
		return null
	return _controller_script.new()


# ---------------------------------------------------------------------------
# Factory helper — mirrors the primary suite pattern.
# Returns [controller, anim_stub, sm_stub, parent] or [] if script missing.
# ---------------------------------------------------------------------------

func _make_controller(test_name: String, state: String = "idle", vel: Vector3 = Vector3.ZERO) -> Array:
	var controller = _new_controller(test_name)
	if controller == null:
		return []

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = state

	var parent := StubParent.new()
	parent.velocity = vel

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	controller._ready()

	return [controller, anim_stub, sm_stub, parent]


func _tick(controller: Object) -> void:
	controller._physics_process(0.016)


# ===========================================================================
# ADV-EAC-01 — Empty string from get_state() falls through to Idle fallback.
#
# VULNERABILITY: The primary suite does not test get_state() == "". An
# implementation that uses `match state:` without an explicit `_:` catch-all,
# or that only checks known state strings with `if/elif` without a final `else`,
# could crash or produce undefined behavior (e.g., no play() call, leaving
# animation frozen from a previous state). An empty string is a valid return
# value if the state machine has not been initialized.
#
# AC-4.8 extends to the empty string case by the same "any other state string"
# rule. Confirmed in checkpoint run-2026-04-01-testbreak.md.
# ===========================================================================

func test_adv_eac_01_empty_state_string_falls_to_idle_fallback() -> void:
	var arr := _make_controller("ADV-EAC-01", "", Vector3.ZERO)
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var parent: StubParent = arr[3]

	_tick(controller)

	_assert_eq_string(
		"Idle",
		anim_stub.last_played_name,
		"ADV-EAC-01: empty state string '' → fallback play('Idle', ...); no crash"
	)
	_assert_eq_float(
		0.15,
		anim_stub.last_played_blend,
		"ADV-EAC-01: empty state string → blend_time is still 0.15"
	)
	_assert_eq_float(
		1.0,
		anim_stub.speed_scale,
		"ADV-EAC-01: empty state string → speed_scale = 1.0 (fallback speed)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-02 — blend_time mutated AFTER _ready() takes effect on next transition.
#
# VULNERABILITY: An implementation that reads `blend_time` once in `_ready()`
# and stores it in a local copy will not reflect post-ready mutations. The export
# contract (ACS-5 AC-5.4, AC-5.5) requires the live export value to be used.
# Primary EAC-20 sets blend_time BEFORE _ready(); this test sets it AFTER.
#
# If the implementation caches blend_time in _ready(), this test will fail
# because the play() call will still use 0.15 (cached) instead of 0.0 (mutated).
# ===========================================================================

func test_adv_eac_02_blend_time_mutated_after_ready_takes_effect() -> void:
	var controller = _new_controller("ADV-EAC-02")
	if controller == null:
		return

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = "idle"

	var parent := StubParent.new()
	parent.velocity = Vector3.ZERO

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	# _ready() runs with default blend_time = 0.15
	controller._ready()

	# First tick primes the internal state.
	_tick(controller)

	# Now change blend_time AFTER _ready() and AFTER first tick.
	# Force a new transition by changing state.
	sm_stub._state = "active"
	controller.blend_time = 0.0

	# Trigger the transition by ticking.
	_tick(controller)

	_assert_eq_float(
		0.0,
		anim_stub.last_played_blend,
		"ADV-EAC-02: blend_time mutated to 0.0 after _ready() — subsequent play() uses new value 0.0"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-03 — _physics_process() called before _ready() is a no-op.
#
# VULNERABILITY: The spec mandates _ready_ok: bool = false as the default
# (AC-3.5). An implementation that initializes _ready_ok to true by default,
# or that checks animation_player != null directly in _physics_process without
# relying on _ready_ok, could execute animation calls before initialization is
# confirmed. This would crash if animation_player or state_machine are null at
# that point.
#
# Since _ready_ok defaults to false (per spec), _physics_process must be
# entirely dormant before _ready() is ever called.
# ===========================================================================

func test_adv_eac_03_physics_process_before_ready_is_noop() -> void:
	var controller = _new_controller("ADV-EAC-03")
	if controller == null:
		return

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = "active"

	var parent := StubParent.new()
	parent.velocity = Vector3(0.5, 0.0, 0.0)

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	# Intentionally do NOT call _ready() here.

	_tick(controller)

	_assert_eq_int(
		0,
		anim_stub.play_call_count,
		"ADV-EAC-03: _physics_process before _ready() must call play() zero times (_ready_ok defaults to false)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-04 — trigger_hit_animation() called before first _physics_process tick.
#
# VULNERABILITY: Primary suite always primes the controller with one tick before
# calling trigger_hit_animation(). Calling it before any tick means _current_clip
# is still "" (initial value per AC-5.6). The hit path must not crash even when
# _current_clip is uninitialized. On Hit completion, re-evaluation of live state
# (AC-6.6) must work correctly regardless of _prior_clip being "".
# ===========================================================================

func test_adv_eac_04_trigger_hit_before_first_tick_does_not_crash() -> void:
	var arr := _make_controller("ADV-EAC-04", "active", Vector3.ZERO)
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var parent: StubParent = arr[3]

	# Do NOT call _tick() first. Call trigger_hit_animation() immediately after _ready().
	controller.trigger_hit_animation()

	_assert_eq_string(
		"Hit",
		anim_stub.last_played_name,
		"ADV-EAC-04: trigger_hit_animation() before any tick → play('Hit', 0.0) called; no crash"
	)
	_assert_eq_float(
		0.0,
		anim_stub.last_played_blend,
		"ADV-EAC-04: trigger_hit before first tick → blend_time 0.0"
	)
	_assert_true(
		controller._hit_active,
		"ADV-EAC-04: trigger_hit before first tick → _hit_active = true"
	)

	# Simulate hit completion; controller must resume state correctly.
	anim_stub.simulate_clip_end()
	anim_stub.play_call_count = 0
	_tick(controller)

	_assert_false(
		controller._hit_active,
		"ADV-EAC-04: after hit completion from zero-tick start, _hit_active = false"
	)
	_assert_eq_string(
		"Idle",
		anim_stub.last_played_name,
		"ADV-EAC-04: after hit completion, resumes resolved state (Idle for active+still)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-05 — Death latch does not allow speed_scale to change afterward.
#
# VULNERABILITY: AC-7.3 says "no play(), stop(), or speed_scale call" after
# death is latched. The primary suite (EAC-11) only asserts play_call_count
# does not increase. It does not verify that speed_scale remains unmodified.
# An implementation might check the latch only for play() but still execute a
# speed_scale assignment elsewhere (e.g., in the weakened branch that runs
# before the death check in a naive if/elif chain).
#
# This test drives through weakened (speed_scale=0.5), then through dead (which
# resets speed_scale=1.0), latches, then verifies a subsequent tick does NOT
# change speed_scale.
# ===========================================================================

func test_adv_eac_05_death_latch_prevents_speed_scale_changes() -> void:
	var controller = _new_controller("ADV-EAC-05")
	if controller == null:
		return

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = "weakened"

	var parent := StubParent.new()
	parent.velocity = Vector3.ZERO

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	controller._ready()

	# Tick in weakened state to establish speed_scale = 0.5.
	_tick(controller)
	_assert_eq_float(
		0.5,
		anim_stub.speed_scale,
		"ADV-EAC-05: precondition — weakened tick sets speed_scale = 0.5"
	)

	# Transition to dead.
	sm_stub._state = "dead"
	_tick(controller)
	_assert_true(
		controller._death_latched,
		"ADV-EAC-05: precondition — _death_latched = true after dead tick"
	)
	_assert_eq_float(
		1.0,
		anim_stub.speed_scale,
		"ADV-EAC-05: death tick restores speed_scale = 1.0 (AC-7.5)"
	)

	# Record speed_scale after death latch.
	var speed_after_latch: float = anim_stub.speed_scale

	# Tick again — must not mutate speed_scale.
	_tick(controller)
	_assert_eq_float(
		speed_after_latch,
		anim_stub.speed_scale,
		"ADV-EAC-05: subsequent tick after death latch must not change speed_scale"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-06 — AnimationPlayer current_animation "" while _hit_active triggers exit.
#
# VULNERABILITY: The spec says hit completion is detected when is_playing() == false
# OR current_animation != "Hit". If current_animation is reset to "" externally
# (e.g., by another system calling stop()), the check `current_animation != "Hit"`
# evaluates to true while is_playing() might still be true. An implementation that
# only checks is_playing() and ignores current_animation would NOT exit hit mode
# in this scenario. An implementation that checks both (OR logic) would correctly
# exit hit mode.
#
# This test probes which condition the implementation actually uses by simulating
# the case where current_animation is cleared to "" while is_playing() remains true.
# ===========================================================================

func test_adv_eac_06_hit_exits_when_current_animation_cleared_to_empty() -> void:
	var arr := _make_controller("ADV-EAC-06", "active", Vector3.ZERO)
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var parent: StubParent = arr[3]

	_tick(controller)
	controller.trigger_hit_animation()

	# Verify hit is active.
	_assert_true(
		controller._hit_active,
		"ADV-EAC-06: precondition — _hit_active = true after trigger_hit_animation()"
	)

	# Externally clear current_animation while is_playing() remains true.
	# This simulates an external system calling stop() or resetting animation state.
	anim_stub.current_animation = ""
	# is_playing() is still true (not called simulate_clip_end).

	anim_stub.play_call_count = 0
	_tick(controller)

	# If the controller checks current_animation != "Hit" as a completion condition,
	# it should now exit hit mode (current_animation "" != "Hit" is true).
	# The test documents the expected behavior: exit hit when current_animation != "Hit".
	_assert_false(
		controller._hit_active,
		"ADV-EAC-06: current_animation cleared to '' while _hit_active — controller exits hit mode (current_animation != 'Hit' satisfies completion condition)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-07 — Velocity exactly at move_threshold resolves to Walk (boundary).
#
# VULNERABILITY: Primary suite tests velocity clearly above threshold (0.5) and
# clearly below (0.0). No test verifies the exact boundary value. An
# implementation using `>` instead of `>=` would fail at exactly the threshold.
# The spec (AC-4.4) says `>= move_threshold` → Walk.
# ===========================================================================

func test_adv_eac_07_velocity_exactly_at_threshold_resolves_to_walk() -> void:
	# Default move_threshold is 0.1. Use velocity of exactly (0.1, 0.0, 0.0),
	# length == 0.1 == threshold.
	var arr := _make_controller("ADV-EAC-07", "active", Vector3(0.1, 0.0, 0.0))
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var parent: StubParent = arr[3]

	_tick(controller)

	_assert_eq_string(
		"Walk",
		anim_stub.last_played_name,
		"ADV-EAC-07: velocity.length() == move_threshold (0.1) → play('Walk', ...) (boundary is inclusive >=)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-08 — Weakened-to-active transition restores speed_scale to 1.0.
#
# VULNERABILITY: Primary suite only checks initial-state speed_scale (starts at 1.0
# default). It never tests that the controller actively SETS speed_scale = 1.0
# when transitioning FROM a state that had a different speed. An implementation
# that only sets speed_scale when it changes from the default (1.0) could fail
# to restore speed after weakened, if it uses a "only write if different from last"
# optimization but forgets to track the last speed value correctly.
# ===========================================================================

func test_adv_eac_08_weakened_to_active_restores_speed_scale() -> void:
	var controller = _new_controller("ADV-EAC-08")
	if controller == null:
		return

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = "weakened"

	var parent := StubParent.new()
	parent.velocity = Vector3.ZERO

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	controller._ready()

	# First tick: establish weakened state (speed_scale = 0.5).
	_tick(controller)
	_assert_eq_float(
		0.5,
		anim_stub.speed_scale,
		"ADV-EAC-08: precondition — weakened tick sets speed_scale = 0.5"
	)

	# Transition to active with non-zero velocity → Walk at speed 1.0.
	sm_stub._state = "active"
	parent.velocity = Vector3(0.5, 0.0, 0.0)
	_tick(controller)

	_assert_eq_float(
		1.0,
		anim_stub.speed_scale,
		"ADV-EAC-08: after weakened→active transition, speed_scale restored to 1.0"
	)
	_assert_eq_string(
		"Walk",
		anim_stub.last_played_name,
		"ADV-EAC-08: after weakened→active with velocity, play('Walk', ...) called"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-09 — Both exports null simultaneously — _ready_ok = false, no crash.
#
# VULNERABILITY: Spec edge case (ACS-3 section 3): "Both exports null
# simultaneously — both warnings must fire, not just the first." A short-circuit
# implementation (e.g., `if animation_player == null: ... return`) would skip
# the state_machine null check. The observable test consequence is _ready_ok = false
# (which both-null and single-null produce), BUT the real risk is that a crash
# occurs if the implementation guards one but not the other and the non-guarded
# one is accessed later. This test calls _physics_process after both-null _ready()
# to confirm zero crashes and zero stub calls.
# ===========================================================================

func test_adv_eac_09_both_exports_null_sets_ready_ok_false_and_noop_physics() -> void:
	var controller = _new_controller("ADV-EAC-09")
	if controller == null:
		return

	var parent := StubParent.new()
	parent.add_child(controller)
	# Both animation_player AND state_machine intentionally left null.
	controller._ready()

	_assert_false(
		controller._ready_ok,
		"ADV-EAC-09: both exports null → _ready_ok = false"
	)

	# _physics_process must not crash with both exports null.
	# We cannot stub play calls since animation_player is null, so we just
	# verify no engine error is raised by calling _tick directly.
	_tick(controller)
	# If we reach here without crash, the test passes.
	_pass("ADV-EAC-09: _physics_process with both exports null does not crash")
	parent.free()


# ===========================================================================
# ADV-EAC-10 — Multiple controller instances are isolated (no shared static state).
#
# VULNERABILITY: An implementation using a `static var` for _death_latched,
# _hit_active, or _current_clip would contaminate sibling controller instances.
# This test creates two controllers on separate stub parents, drives one to death
# and the other to idle, then verifies each has its own independent state.
# ===========================================================================

func test_adv_eac_10_two_instances_are_isolated() -> void:
	# Controller A: will be driven to dead.
	var arr_a := _make_controller("ADV-EAC-10-A", "idle", Vector3.ZERO)
	if arr_a.is_empty():
		return
	# Controller B: will stay in idle.
	var arr_b := _make_controller("ADV-EAC-10-B", "idle", Vector3.ZERO)
	if arr_b.is_empty():
		arr_a[3].free()
		return

	var ctrl_a = arr_a[0]
	var sm_a: StubStateMachine = arr_a[2]
	var parent_a: StubParent = arr_a[3]

	var ctrl_b = arr_b[0]
	var anim_b: StubAnimationPlayer = arr_b[1]
	var parent_b: StubParent = arr_b[3]

	# Drive A to dead.
	sm_a._state = "dead"
	_tick(ctrl_a)
	_assert_true(
		ctrl_a._death_latched,
		"ADV-EAC-10: controller A is death-latched after dead state tick"
	)

	# Drive B with a normal tick.
	_tick(ctrl_b)
	_assert_false(
		ctrl_b._death_latched,
		"ADV-EAC-10: controller B _death_latched is NOT affected by controller A's death latch"
	)
	_assert_false(
		ctrl_b._hit_active,
		"ADV-EAC-10: controller B _hit_active is NOT contaminated by controller A"
	)
	_assert_eq_string(
		"Idle",
		anim_b.last_played_name,
		"ADV-EAC-10: controller B plays Idle independently (unaffected by A's death)"
	)

	parent_a.free()
	parent_b.free()


# ===========================================================================
# ADV-EAC-11 — trigger_hit_animation() when _ready_ok == false is a no-op.
#
# VULNERABILITY: AC-7.4 covers Death suppressing Hit. But if _ready_ok == false
# (null guard fired), calling trigger_hit_animation() with a null animation_player
# would crash on the play() call. The method must guard _ready_ok (or null-check
# animation_player) before acting. Primary suite never tests this path.
# ===========================================================================

func test_adv_eac_11_trigger_hit_when_not_ready_is_noop() -> void:
	var controller = _new_controller("ADV-EAC-11")
	if controller == null:
		return

	var parent := StubParent.new()
	parent.add_child(controller)

	# Only assign animation_player — leave state_machine null to trigger null guard.
	var anim_stub := StubAnimationPlayer.new()
	controller.animation_player = anim_stub
	controller._ready()

	_assert_false(
		controller._ready_ok,
		"ADV-EAC-11: precondition — _ready_ok = false (null state_machine)"
	)

	anim_stub.play_call_count = 0
	controller.trigger_hit_animation()

	_assert_eq_int(
		0,
		anim_stub.play_call_count,
		"ADV-EAC-11: trigger_hit_animation() with _ready_ok=false → zero play() calls (no crash)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-12 — State becomes dead during hit active window (pre-clip-end) —
#              Death must NOT trigger while hit clip is still playing.
#
# VULNERABILITY: EAC-16 tests that after the Hit clip FINISHES, Death triggers
# correctly. But no test verifies the scenario where the enemy dies DURING the
# hit (is_playing() still true). AC-6.4 says the state dispatch is suppressed
# while _hit_active is true. This must include the Death branch — Death should
# not be triggered until hit completes.
#
# An implementation with separate early-exit for death in _physics_process
# (before the _hit_active check) would violate this by triggering Death
# mid-hit.
# ===========================================================================

func test_adv_eac_12_dead_during_hit_active_window_does_not_trigger_death() -> void:
	var arr := _make_controller("ADV-EAC-12", "active", Vector3.ZERO)
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var sm_stub: StubStateMachine = arr[2]
	var parent: StubParent = arr[3]

	_tick(controller)
	controller.trigger_hit_animation()

	_assert_true(
		controller._hit_active,
		"ADV-EAC-12: precondition — _hit_active = true after trigger_hit_animation()"
	)

	# Enemy dies while hit is still playing (is_playing() remains true).
	sm_stub._state = "dead"
	# Do NOT simulate_clip_end — hit is still active.
	anim_stub.play_call_count = 0

	_tick(controller)

	# Death must NOT be triggered mid-hit.
	_assert_false(
		controller._death_latched,
		"ADV-EAC-12: state becomes 'dead' during active hit (clip still playing) — _death_latched must remain false"
	)
	_assert_eq_int(
		0,
		anim_stub.play_call_count,
		"ADV-EAC-12: no play() call while hit clip is still playing even when state is 'dead'"
	)
	_assert_true(
		controller._hit_active,
		"ADV-EAC-12: _hit_active remains true while hit clip is still playing"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-13 — Wrong-case state string falls through to Idle fallback.
#
# VULNERABILITY: Primary suite only tests lowercase canonical states. The spec
# says state string matching is case-sensitive (the resolution table uses exact
# lowercase literals). An implementation using case-insensitive comparison
# (e.g., state.to_lower() == "active") would not expose this bug. The correct
# behavior is that "ACTIVE" or "Active" are unknown states and fall through to
# the Idle fallback at speed 1.0 — even with non-zero velocity.
# ===========================================================================

func test_adv_eac_13_uppercase_state_string_falls_to_idle_fallback() -> void:
	# "ACTIVE" is not a canonical state; velocity is set above threshold.
	# Correct: Idle (fallback) at speed 1.0.
	# Wrong (case-insensitive bug): Walk at speed 1.0.
	var arr := _make_controller("ADV-EAC-13", "ACTIVE", Vector3(0.5, 0.0, 0.0))
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var parent: StubParent = arr[3]

	_tick(controller)

	_assert_eq_string(
		"Idle",
		anim_stub.last_played_name,
		"ADV-EAC-13: state 'ACTIVE' (wrong casing) → fallback 'Idle', not 'Walk' (case-sensitive matching)"
	)
	_assert_eq_float(
		1.0,
		anim_stub.speed_scale,
		"ADV-EAC-13: state 'ACTIVE' fallback → speed_scale = 1.0"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-14 — Large velocity value does not crash or produce wrong result.
#
# VULNERABILITY: velocity.length() uses a square root. For extreme values like
# Vector3(1000, 1000, 1000), length ≈ 1732. This is far above any threshold.
# A naive integer-overflow bug or unexpected branching at extreme magnitudes
# could cause the controller to fall through to Idle instead of Walk.
# ===========================================================================

func test_adv_eac_14_large_velocity_resolves_to_walk() -> void:
	var arr := _make_controller("ADV-EAC-14", "active", Vector3(1000.0, 1000.0, 1000.0))
	if arr.is_empty():
		return
	var controller = arr[0]
	var anim_stub: StubAnimationPlayer = arr[1]
	var parent: StubParent = arr[3]

	_tick(controller)

	_assert_eq_string(
		"Walk",
		anim_stub.last_played_name,
		"ADV-EAC-14: velocity Vector3(1000,1000,1000) with state 'active' → play('Walk', ...) (no overflow)"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-15 — 60-tick simulation with state change at tick 30 produces
#              exactly 2 play() calls total (one on tick 1, one on tick 30).
#
# VULNERABILITY: Primary EAC-NF1 only tests a constant state for 60 ticks
# (1 play call). No test verifies that a single state change mid-simulation
# produces exactly 2 play calls. An implementation that is either too eager
# (calls play() every frame) or too lazy (misses the state-change transition)
# would be caught here.
#
# Scenario: ticks 1–29 idle+still=Idle (1 play on tick 1), ticks 30–60
# active+moving=Walk (1 play on tick 30). Total: 2 play() calls.
# ===========================================================================

func test_adv_eac_15_single_state_change_mid_simulation_produces_two_play_calls() -> void:
	var controller = _new_controller("ADV-EAC-15")
	if controller == null:
		return

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = "idle"

	var parent := StubParent.new()
	parent.velocity = Vector3.ZERO

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	controller._ready()

	# Ticks 1–29: idle, still → Idle.
	for _i in 29:
		_tick(controller)

	var count_before_change: int = anim_stub.play_call_count
	_assert_eq_int(
		1,
		count_before_change,
		"ADV-EAC-15: after 29 ticks of constant idle+still → exactly 1 play() call"
	)

	# Transition: active + moving → Walk.
	sm_stub._state = "active"
	parent.velocity = Vector3(0.5, 0.0, 0.0)

	# Ticks 30–60: active, moving → Walk.
	for _i in 31:
		_tick(controller)

	_assert_eq_int(
		2,
		anim_stub.play_call_count,
		"ADV-EAC-15: 60 ticks with one state change at tick 30 → exactly 2 play() calls total"
	)
	_assert_eq_string(
		"Walk",
		anim_stub.last_played_name,
		"ADV-EAC-15: final clip after state change is 'Walk'"
	)
	parent.free()


# ===========================================================================
# ADV-EAC-16 — Negative blend_time passed verbatim to play().
#
# VULNERABILITY: The spec says blend_time export value is used for transitions.
# An implementation that clamps negative values to 0.0 diverges from the spec's
# verbatim pass-through intent. In Godot 4, AnimationPlayer.play() with a
# negative blend_time uses the AnimationPlayer's own default blend. While either
# behavior could be considered valid, the test documents the expected contract:
# verbatim pass-through (no clamping). If the Implementation Agent clamps,
# this test will fail — exposing the divergence so the spec can be clarified.
# ===========================================================================

func test_adv_eac_16_negative_blend_time_passed_verbatim_to_play() -> void:
	var controller = _new_controller("ADV-EAC-16")
	if controller == null:
		return

	var anim_stub := StubAnimationPlayer.new()
	var sm_stub := StubStateMachine.new()
	sm_stub._state = "idle"

	var parent := StubParent.new()
	parent.velocity = Vector3.ZERO

	parent.add_child(controller)
	controller.animation_player = anim_stub
	controller.state_machine = sm_stub
	controller.blend_time = -1.0
	controller._ready()

	_tick(controller)

	_assert_eq_float(
		-1.0,
		anim_stub.last_played_blend,
		"ADV-EAC-16: blend_time = -1.0 passed verbatim to play() — no clamping per spec"
	)
	parent.free()


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

func run_all() -> int:
	print("--- test_enemy_animation_controller_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	test_adv_eac_01_empty_state_string_falls_to_idle_fallback()
	test_adv_eac_02_blend_time_mutated_after_ready_takes_effect()
	test_adv_eac_03_physics_process_before_ready_is_noop()
	test_adv_eac_04_trigger_hit_before_first_tick_does_not_crash()
	test_adv_eac_05_death_latch_prevents_speed_scale_changes()
	test_adv_eac_06_hit_exits_when_current_animation_cleared_to_empty()
	test_adv_eac_07_velocity_exactly_at_threshold_resolves_to_walk()
	test_adv_eac_08_weakened_to_active_restores_speed_scale()
	test_adv_eac_09_both_exports_null_sets_ready_ok_false_and_noop_physics()
	test_adv_eac_10_two_instances_are_isolated()
	test_adv_eac_11_trigger_hit_when_not_ready_is_noop()
	test_adv_eac_12_dead_during_hit_active_window_does_not_trigger_death()
	test_adv_eac_13_uppercase_state_string_falls_to_idle_fallback()
	test_adv_eac_14_large_velocity_resolves_to_walk()
	test_adv_eac_15_single_state_change_mid_simulation_produces_two_play_calls()
	test_adv_eac_16_negative_blend_time_passed_verbatim_to_play()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count
