# run_tests.gd
#
# Top-level headless test runner for the blobert project.
#
# Usage:
#   godot --headless --path /Users/jacobbrandt/workspace/blobert -s tests/run_tests.gd
#
# This script extends SceneTree so Godot executes it directly via the -s flag.
# It instantiates each Object-subclass test suite, calls run_all(), accumulates
# the failure count, and exits with code 0 (all pass) or 1 (any failure).
#
# Exit codes:
#   0  — all test suites passed (fail_count == 0)
#   1  — one or more tests failed (fail_count > 0)
#
# Adding a new suite:
#   1. Create tests/test_<name>.gd as "class_name <Name>Tests extends Object"
#      with a "func run_all() -> int:" entry point.
#   2. Add a load/new/run_all block below, identically to the existing pattern.

extends SceneTree


func _initialize() -> void:
	print("=== blobert headless test runner ===")
	print("")

	var total_failures: int = 0

	# ------------------------------------------------------------------
	# Suite: MovementSimulation
	# Spec coverage: SPEC-1 through SPEC-6, SPEC-12 through SPEC-14
	# ------------------------------------------------------------------
	var movement_suite_script: GDScript = load("res://tests/test_movement_simulation.gd")
	if movement_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_movement_simulation.gd")
		quit(1)
		return

	var movement_suite: MovementSimulationTests = movement_suite_script.new()
	var movement_failures: int = movement_suite.run_all()
	total_failures += movement_failures

	# ------------------------------------------------------------------
	# Suite: MovementSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-02-28
	# Spec coverage: edge cases, boundary values, mutation testing, stress
	# scenarios targeting gaps in SPEC-3 through SPEC-6, SPEC-12.
	# ------------------------------------------------------------------
	var adversarial_suite_script: GDScript = load("res://tests/test_movement_simulation_adversarial.gd")
	if adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_movement_simulation_adversarial.gd")
		quit(1)
		return

	var adversarial_suite: MovementSimulationAdversarialTests = adversarial_suite_script.new()
	var adversarial_failures: int = adversarial_suite.run_all()
	total_failures += adversarial_failures

	# ------------------------------------------------------------------
	# Suite: JumpSimulation
	# Spec coverage: SPEC-15 through SPEC-21, SPEC-24
	# ------------------------------------------------------------------
	var jump_suite_script: GDScript = load("res://tests/test_jump_simulation.gd")
	if jump_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_jump_simulation.gd")
		quit(1)
		return

	var jump_suite: JumpSimulationTests = jump_suite_script.new()
	var jump_failures: int = jump_suite.run_all()
	total_failures += jump_failures

	# ------------------------------------------------------------------
	# Suite: JumpSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-03-01
	# Spec coverage: boundary, mutation, stress, and edge-case tests targeting
	# gaps in SPEC-15 through SPEC-21, SPEC-24.
	# ------------------------------------------------------------------
	var jump_adversarial_suite_script: GDScript = load("res://tests/test_jump_simulation_adversarial.gd")
	if jump_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_jump_simulation_adversarial.gd")
		quit(1)
		return

	var jump_adversarial_suite: JumpSimulationAdversarialTests = jump_adversarial_suite_script.new()
	var jump_adversarial_failures: int = jump_adversarial_suite.run_all()
	total_failures += jump_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: WallClingSimulation
	# Spec coverage: SPEC-25 through SPEC-34, SPEC-36
	# ------------------------------------------------------------------
	var wall_cling_suite_script: GDScript = load("res://tests/test_wall_cling_simulation.gd")
	if wall_cling_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_wall_cling_simulation.gd")
		quit(1)
		return

	var wall_cling_suite: WallClingSimulationTests = wall_cling_suite_script.new()
	var wall_cling_failures: int = wall_cling_suite.run_all()
	total_failures += wall_cling_failures

	# ------------------------------------------------------------------
	# Suite: WallClingSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-03-01
	# Spec coverage: boundary, mutation, stress, and edge-case tests targeting
	# gaps in SPEC-25 through SPEC-34, SPEC-36 not covered by primary suite.
	# ------------------------------------------------------------------
	var wall_cling_adversarial_suite_script: GDScript = load("res://tests/test_wall_cling_simulation_adversarial.gd")
	if wall_cling_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_wall_cling_simulation_adversarial.gd")
		quit(1)
		return

	var wall_cling_adversarial_suite: WallClingSimulationAdversarialTests = wall_cling_adversarial_suite_script.new()
	var wall_cling_adversarial_failures: int = wall_cling_adversarial_suite.run_all()
	total_failures += wall_cling_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: CameraFollow
	# Spec coverage: SPEC-37 through SPEC-42, SPEC-45 (headless-verifiable ACs)
	# Manual ACs (MAN-01 through MAN-06) are listed in camera_follow_spec.md
	# and are not included here — they require in-editor verification (Task 6).
	# ------------------------------------------------------------------
	var camera_follow_suite_script: GDScript = load("res://tests/test_camera_follow.gd")
	if camera_follow_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_camera_follow.gd")
		quit(1)
		return

	var camera_follow_suite: CameraFollowTests = camera_follow_suite_script.new()
	var camera_follow_failures: int = camera_follow_suite.run_all()
	total_failures += camera_follow_failures

	# ------------------------------------------------------------------
	# Summary
	# ------------------------------------------------------------------
	print("")
	if total_failures == 0:
		print("=== ALL TESTS PASSED ===")
	else:
		print("=== FAILURES: " + str(total_failures) + " test(s) failed ===")

	quit(1 if total_failures > 0 else 0)
