# run_tests.gd
#
# Top-level headless test runner for the blobert project.
#
# Usage:
#   godot --headless --path /Users/jacobbrandt/workspace/blobert -s tests/run_tests.gd
#
# This script extends SceneTree so Godot executes it directly via the -s flag.
# It instantiates each Object-subclass test suite, calls run_all(), accumulates
# the failure count, and exits with code 0 (all pass) or 1 (any failure).
#
# Exit codes:
#   0  — all test suites passed (fail_count == 0)
#   1  — one or more tests failed (fail_count > 0)
#
# Adding a new suite:
#   1. Create tests/test_<name>.gd as "class_name <Name>Tests extends Object"
#      with a "func run_all() -> int:" entry point.
#   2. Add a load/new/run_all block below, identically to the existing pattern.

extends SceneTree


func _initialize() -> void:
	print("=== blobert headless test runner ===")
	print("")

	var total_failures: int = 0

	# ------------------------------------------------------------------
	# Suite: MovementSimulation
	# Spec coverage: SPEC-1 through SPEC-6, SPEC-12 through SPEC-14
	# ------------------------------------------------------------------
	var movement_suite_script: GDScript = load("res://tests/test_movement_simulation.gd")
	if movement_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_movement_simulation.gd")
		quit(1)
		return

	var movement_suite: MovementSimulationTests = movement_suite_script.new()
	var movement_failures: int = movement_suite.run_all()
	total_failures += movement_failures

	# ------------------------------------------------------------------
	# Suite: MovementSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-02-28
	# Spec coverage: edge cases, boundary values, mutation testing, stress
	# scenarios targeting gaps in SPEC-3 through SPEC-6, SPEC-12.
	# ------------------------------------------------------------------
	var adversarial_suite_script: GDScript = load("res://tests/test_movement_simulation_adversarial.gd")
	if adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_movement_simulation_adversarial.gd")
		quit(1)
		return

	var adversarial_suite: MovementSimulationAdversarialTests = adversarial_suite_script.new()
	var adversarial_failures: int = adversarial_suite.run_all()
	total_failures += adversarial_failures

	# ------------------------------------------------------------------
	# Suite: JumpSimulation
	# Spec coverage: SPEC-15 through SPEC-21, SPEC-24
	# ------------------------------------------------------------------
	var jump_suite_script: GDScript = load("res://tests/test_jump_simulation.gd")
	if jump_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_jump_simulation.gd")
		quit(1)
		return

	var jump_suite: JumpSimulationTests = jump_suite_script.new()
	var jump_failures: int = jump_suite.run_all()
	total_failures += jump_failures

	# ------------------------------------------------------------------
	# Suite: JumpSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-03-01
	# Spec coverage: boundary, mutation, stress, and edge-case tests targeting
	# gaps in SPEC-15 through SPEC-21, SPEC-24.
	# ------------------------------------------------------------------
	var jump_adversarial_suite_script: GDScript = load("res://tests/test_jump_simulation_adversarial.gd")
	if jump_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_jump_simulation_adversarial.gd")
		quit(1)
		return

	var jump_adversarial_suite: JumpSimulationAdversarialTests = jump_adversarial_suite_script.new()
	var jump_adversarial_failures: int = jump_adversarial_suite.run_all()
	total_failures += jump_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: WallClingSimulation
	# Spec coverage: SPEC-25 through SPEC-34, SPEC-36
	# ------------------------------------------------------------------
	var wall_cling_suite_script: GDScript = load("res://tests/test_wall_cling_simulation.gd")
	if wall_cling_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_wall_cling_simulation.gd")
		quit(1)
		return

	var wall_cling_suite: WallClingSimulationTests = wall_cling_suite_script.new()
	var wall_cling_failures: int = wall_cling_suite.run_all()
	total_failures += wall_cling_failures

	# ------------------------------------------------------------------
	# Suite: WallClingSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-03-01
	# Spec coverage: boundary, mutation, stress, and edge-case tests targeting
	# gaps in SPEC-25 through SPEC-34, SPEC-36 not covered by primary suite.
	# ------------------------------------------------------------------
	var wall_cling_adversarial_suite_script: GDScript = load("res://tests/test_wall_cling_simulation_adversarial.gd")
	if wall_cling_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_wall_cling_simulation_adversarial.gd")
		quit(1)
		return

	var wall_cling_adversarial_suite: WallClingSimulationAdversarialTests = wall_cling_adversarial_suite_script.new()
	var wall_cling_adversarial_failures: int = wall_cling_adversarial_suite.run_all()
	total_failures += wall_cling_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: CameraFollow
	# Spec coverage: SPEC-37 through SPEC-42, SPEC-45 (headless-verifiable ACs)
	# Manual ACs (MAN-01 through MAN-06) are listed in camera_follow_spec.md
	# and are not included here — they require in-editor verification (Task 6).
	# ------------------------------------------------------------------
	var camera_follow_suite_script: GDScript = load("res://tests/test_camera_follow.gd")
	if camera_follow_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_camera_follow.gd")
		quit(1)
		return

	var camera_follow_suite: CameraFollowTests = camera_follow_suite_script.new()
	var camera_follow_failures: int = camera_follow_suite.run_all()
	total_failures += camera_follow_failures

	# ------------------------------------------------------------------
	# Suite: CameraFollow Adversarial
	# Generated by Test Breaker Agent — 2026-03-01
	# Spec coverage: edge-case and adversarial tests for SPEC-38, SPEC-39,
	# SPEC-40, SPEC-41, SPEC-42 targeting: zero/negative/INF smoothing_speed,
	# smoothing_enabled=false, degenerate limit boxes, inverted limits,
	# INT32 boundary limits, out-of-range drag margins, idempotency and
	# override behavior of _ready() on repeated calls.
	# ------------------------------------------------------------------
	var camera_follow_adversarial_suite_script: GDScript = load("res://tests/test_camera_follow_adversarial.gd")
	if camera_follow_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_camera_follow_adversarial.gd")
		quit(1)
		return

	var camera_follow_adversarial_suite: CameraFollowAdversarialTests = camera_follow_adversarial_suite_script.new()
	var camera_follow_adversarial_failures: int = camera_follow_adversarial_suite.run_all()
	total_failures += camera_follow_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: ChunkDetachSimulation
	# Spec coverage: SPEC-46 through SPEC-50, SPEC-53 (headless-verifiable ACs)
	# SPEC-51 (project.godot input action) and SPEC-52 (engine integration /
	# player_controller.gd + chunk.tscn) are not covered here — they require
	# in-editor or controller-level verification (Tasks 6 and 7).
	# ------------------------------------------------------------------
	var chunk_detach_suite_script: GDScript = load("res://tests/test_chunk_detach_simulation.gd")
	if chunk_detach_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_chunk_detach_simulation.gd")
		quit(1)
		return

	var chunk_detach_suite: ChunkDetachSimulationTests = chunk_detach_suite_script.new()
	var chunk_detach_failures: int = chunk_detach_suite.run_all()
	total_failures += chunk_detach_failures

	# ------------------------------------------------------------------
	# Suite: ChunkDetachSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-03-01
	# Spec coverage: adversarial boundary, mutation, stress, and edge-case
	# tests for SPEC-46 through SPEC-50, SPEC-53 not covered by the 37-test
	# primary suite. Targets: detach+jump same frame (all 7 fields), detach+
	# wall jump, detach on landing, rapid no-op detach, delta=0.0 (all
	# fields), large delta, 7-field state immutability, config mutation
	# isolation, two-instance isolation, 100-iteration no-op stability,
	# normal movement unaffected, coyote window, jump_consumed=true, active
	# cling carry-forward, and sequential detach press stability.
	# ------------------------------------------------------------------
	var chunk_detach_adversarial_suite_script: GDScript = load("res://tests/test_chunk_detach_simulation_adversarial.gd")
	if chunk_detach_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_chunk_detach_simulation_adversarial.gd")
		quit(1)
		return

	var chunk_detach_adversarial_suite: ChunkDetachSimulationAdversarialTests = chunk_detach_adversarial_suite_script.new()
	var chunk_detach_adversarial_failures: int = chunk_detach_adversarial_suite.run_all()
	total_failures += chunk_detach_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: HpReductionSimulation
	# Spec coverage: SPEC-54 through SPEC-60 (primary behavioral cases)
	# AC-56.1 through AC-57.6, AC-58.1 through AC-58.4, AC-59.1,
	# AC-60.4, NFR-61.C (prior_state immutability).
	# ------------------------------------------------------------------
	var hp_reduction_suite_script: GDScript = load("res://tests/test_hp_reduction_simulation.gd")
	if hp_reduction_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_hp_reduction_simulation.gd")
		quit(1)
		return

	var hp_reduction_suite: HpReductionSimulationTests = hp_reduction_suite_script.new()
	var hp_reduction_failures: int = hp_reduction_suite.run_all()
	total_failures += hp_reduction_failures

	# ------------------------------------------------------------------
	# Suite: ChunkRecallSimulation
	# Ticket coverage: FEAT-20260302-chunk-recall-core
	# Scope: controller-level chunk recall behavior including valid/invalid
	# recall input routing, main body and chunk state transitions,
	# non-blocking input behavior at the simulation level, and basic HP
	# restoration behavior under the assumed recall HP formula.
	# ------------------------------------------------------------------
	var chunk_recall_suite_script: GDScript = load("res://tests/test_chunk_recall_simulation.gd")
	if chunk_recall_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_chunk_recall_simulation.gd")
		quit(1)
		return

	var chunk_recall_suite: ChunkRecallSimulationTests = chunk_recall_suite_script.new()
	var chunk_recall_failures: int = chunk_recall_suite.run_all()
	total_failures += chunk_recall_failures

	# ------------------------------------------------------------------
	# Suite: ChunkRecallSimulation Adversarial
	# Generated by Test Breaker Agent — 2026-03-02
	# Scope: adversarial and edge-case tests for FEAT-20260302-chunk-recall-core,
	# targeting rapid repeated detach/recall input, airborne recall behavior,
	# large-delta homing/reabsorption ordering, null/no-op recall when no chunk
	# exists or is destroyed mid-flight, and controller-level determinism of
	# HP/has_chunk given identical input sequences.
	# ------------------------------------------------------------------
	var chunk_recall_adversarial_suite_script: GDScript = load("res://tests/test_chunk_recall_simulation_adversarial.gd")
	if chunk_recall_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_chunk_recall_simulation_adversarial.gd")
		quit(1)
		return

	var chunk_recall_adversarial_suite: ChunkRecallSimulationAdversarialTests = chunk_recall_adversarial_suite_script.new()
	var chunk_recall_adversarial_failures: int = chunk_recall_adversarial_suite.run_all()
	total_failures += chunk_recall_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: HumanPlayableCore
	# Ticket coverage: FEAT-20260302-human-playable-core
	# Scope: scene composition (player/ground/chunk visuals), camera framing
	# configuration in test_movement.tscn, minimal UI hints, and encoded
	# human-playability checklist metadata plus smoke test.
	# ------------------------------------------------------------------
	var human_playable_core_suite_script: GDScript = load("res://tests/test_human_playable_core.gd")
	if human_playable_core_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_human_playable_core.gd")
		quit(1)
		return

	var human_playable_core_suite: HumanPlayableCoreTests = human_playable_core_suite_script.new()
	var human_playable_core_failures: int = human_playable_core_suite.run_all()
	total_failures += human_playable_core_failures

	# ------------------------------------------------------------------
	# Suite: HumanPlayableCore Adversarial
	# Generated by Test Breaker Agent — 2026-03-02
	# Scope: adversarial and edge-case tests targeting:
	#   - invisible/tiny visuals and layering issues for player/floor/chunk
	#   - unconfigured/default CameraFollow limits and inverted limit boxes
	#   - UI hint visibility/readability and off-screen placement
	#   - human-playability metadata ID uniqueness and per-step integrity.
	# ------------------------------------------------------------------
	var human_playable_core_adversarial_suite_script: GDScript = load("res://tests/test_human_playable_core_adversarial.gd")
	if human_playable_core_adversarial_suite_script == null:
		push_error("RUNNER ERROR: could not load res://tests/test_human_playable_core_adversarial.gd")
		quit(1)
		return

	var human_playable_core_adversarial_suite: HumanPlayableCoreAdversarialTests = human_playable_core_adversarial_suite_script.new()
	var human_playable_core_adversarial_failures: int = human_playable_core_adversarial_suite.run_all()
	total_failures += human_playable_core_adversarial_failures

	# ------------------------------------------------------------------
	# Suite: HpReductionSimulation Adversarial
	# TODO (Task 3 — Test Breaker Agent): Uncomment when
	# tests/test_hp_reduction_simulation_adversarial.gd is written.
	# ------------------------------------------------------------------
	# var hp_reduction_adversarial_suite_script: GDScript = load("res://tests/test_hp_reduction_simulation_adversarial.gd")
	# if hp_reduction_adversarial_suite_script == null:
	# 	push_error("RUNNER ERROR: could not load res://tests/test_hp_reduction_simulation_adversarial.gd")
	# 	quit(1)
	# 	return
	# var hp_reduction_adversarial_suite: HpReductionSimulationAdversarialTests = hp_reduction_adversarial_suite_script.new()
	# var hp_reduction_adversarial_failures: int = hp_reduction_adversarial_suite.run_all()
	# total_failures += hp_reduction_adversarial_failures

	# ------------------------------------------------------------------
	# Summary
	# ------------------------------------------------------------------
	print("")
	if total_failures == 0:
		print("=== ALL TESTS PASSED ===")
	else:
		print("=== FAILURES: " + str(total_failures) + " test(s) failed ===")

	quit(1 if total_failures > 0 else 0)
