#
# test_human_playable_core_adversarial.gd
#
# Adversarial / edge-case tests for the "human-playable core movement prototype"
# slice. Generated by Test Breaker Agent.
#
# Scope:
#   - Additional structural assertions on visuals (player, floor, chunk) to
#     catch invisible or tiny-but-present sprites and layering issues.
#   - Scene-level camera configuration checks that detect unconfigured defaults
#     and inverted/degenerate limit boxes for CameraFollow in test_movement.tscn.
#   - UI hint robustness checks for visibility/readability beyond mere presence.
#   - Human-playability metadata checks for ID uniqueness and per-step integrity.
#
# All tests are deterministic and purely structural/configurational. They do not
# simulate a running gameplay session; runtime behavior is already covered by
# movement, camera_follow, and chunk_detach suites.
#

class_name HumanPlayableCoreAdversarialTests
extends Object

const EPSILON: float = 1e-4

var _pass_count: int = 0
var _fail_count: int = 0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

func _approx_eq(a: float, b: float) -> bool:
	return abs(a - b) < EPSILON


func _pass(test_name: String) -> void:
	_pass_count += 1
	print("  PASS: " + test_name)


func _fail(test_name: String, message: String) -> void:
	_fail_count += 1
	print("  FAIL: " + test_name + " — " + message)


func _assert_true(condition: bool, test_name: String) -> void:
	if condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected true, got false")


func _assert_false(condition: bool, test_name: String) -> void:
	if not condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected false, got true")


func _assert_vec2_approx(a: Vector2, b: Vector2, test_name: String) -> void:
	if _approx_eq(a.x, b.x) and _approx_eq(a.y, b.y):
		_pass(test_name)
	else:
		_fail(test_name, "got " + str(a) + " expected " + str(b))


func _load_main_scene() -> Node:
	var packed: PackedScene = load("res://scenes/test_movement.tscn") as PackedScene
	if packed == null:
		_fail("adv_scene_load_main", "could not load res://scenes/test_movement.tscn")
		return null
	var inst: Node = packed.instantiate()
	if inst == null:
		_fail("adv_scene_instantiate_main", "instantiate() returned null for test_movement.tscn")
		return null
	return inst


func _find_player(root: Node) -> CharacterBody2D:
	if root == null:
		return null
	var player: CharacterBody2D = root.get_node_or_null("Player") as CharacterBody2D
	return player


func _find_floor(root: Node) -> StaticBody2D:
	if root == null:
		return null
	var floor: StaticBody2D = root.get_node_or_null("Floor") as StaticBody2D
	return floor


func _find_camera(root: Node) -> Camera2D:
	var player: CharacterBody2D = _find_player(root)
	if player == null:
		return null
	var camera: Camera2D = player.get_node_or_null("Camera") as Camera2D
	return camera


func _find_visual_child_2d(parent: Node) -> Node2D:
	if parent == null:
		return null
	for child in parent.get_children():
		var node2d := child as Node2D
		if node2d == null:
			continue
		if child is CollisionShape2D:
			continue
		# Accept Sprite2D, ColorRect (via Node2D subclasses), or any other Node2D
		# that is not purely a collision node as a "visual".
		return node2d
	return null


func _labels_with_text(root: Node, needle: String) -> Array:
	var matches: Array = []
	if root == null:
		return matches
	var lower_needle: String = needle.to_lower()
	for child in root.find_children("*", "Label", true, false):
		var label := child as Label
		if label == null:
			continue
		if lower_needle in label.text.to_lower():
			matches.append(label)
	return matches


func _central_play_area_bounds(root: Node) -> Rect2:
	var player: CharacterBody2D = _find_player(root)
	var floor: StaticBody2D = _find_floor(root)
	if player == null or floor == null:
		# Fallback: generic box around origin.
		return Rect2(Vector2(-200, -200), Vector2(400, 400))

	var floor_shape: CollisionShape2D = floor.get_node_or_null("FloorShape") as CollisionShape2D
	var half_width: float = 200.0
	if floor_shape != null and floor_shape.shape is RectangleShape2D:
		var rect: RectangleShape2D = floor_shape.shape as RectangleShape2D
		half_width = rect.size.x * 0.5

	var player_pos: Vector2 = player.global_position
	var floor_pos: Vector2 = floor.global_position

	var left: float = min(player_pos.x - 200.0, floor_pos.x - half_width)
	var right: float = max(player_pos.x + 200.0, floor_pos.x + half_width)
	var top: float = min(player_pos.y - 200.0, floor_pos.y - 200.0)
	var bottom: float = max(player_pos.y + 200.0, floor_pos.y + 200.0)

	return Rect2(Vector2(left, top), Vector2(right - left, bottom - top))


func _point_inside_rect(p: Vector2, r: Rect2) -> bool:
	return r.has_point(p)


func _assert_visual_not_invisible_or_tiny(parent: Node, id_suffix: String) -> void:
	var visual: Node2D = _find_visual_child_2d(parent)
	_assert_true(visual != null,
		"adv_visual_%s_child_present — node has at least one non-collision Node2D child as visual" % id_suffix)

	if visual == null:
		return

	var canvas_item := visual as CanvasItem
	var alpha_ok: bool = canvas_item.modulate.a > 0.0
	_assert_true(alpha_ok,
		"adv_visual_%s_alpha_non_zero — visual modulate alpha is > 0 (not fully transparent)" % id_suffix)

	var scale: Vector2 = visual.scale
	var min_abs_scale: float = 0.1
	var not_tiny: bool = abs(scale.x) >= min_abs_scale and abs(scale.y) >= min_abs_scale
	_assert_true(not_tiny,
		"adv_visual_%s_scale_not_tiny — visual scale is not effectively zero on either axis" % id_suffix)


func _collect_hint_labels(root: Node) -> Array:
	var move_labels: Array = _labels_with_text(root, "move")
	var jump_labels: Array = _labels_with_text(root, "jump")
	var detach_labels: Array = _labels_with_text(root, "detach")

	var all_labels: Array = []
	all_labels.append_array(move_labels)
	all_labels.append_array(jump_labels)
	all_labels.append_array(detach_labels)
	return all_labels


# ---------------------------------------------------------------------------
# Visuals: invisibility, tiny sprites, and layering issues
# ---------------------------------------------------------------------------

func test_player_and_floor_visuals_not_invisible_or_tiny() -> void:
	var root: Node = _load_main_scene()
	if root == null:
		return

	var player: CharacterBody2D = _find_player(root)
	var floor: StaticBody2D = _find_floor(root)

	if player == null:
		_fail("adv_visual_player_exists", "Player node not found in test_movement.tscn")
		root.free()
		return

	if floor == null:
		_fail("adv_visual_floor_exists", "Floor node not found in test_movement.tscn")
		root.free()
		return

	_assert_visual_not_invisible_or_tiny(player, "player")
	_assert_visual_not_invisible_or_tiny(floor, "floor")

	root.free()


func test_chunk_visual_not_invisible_or_tiny() -> void:
	var packed: PackedScene = load("res://scenes/chunk.tscn") as PackedScene
	if packed == null:
		_fail("adv_visual_chunk_scene_load", "could not load res://scenes/chunk.tscn")
		return

	var root: Node = packed.instantiate()
	if root == null:
		_fail("adv_visual_chunk_scene_instantiate", "instantiate() returned null for chunk.tscn")
		return

	var chunk_body: RigidBody2D = root as RigidBody2D
	if chunk_body == null:
		_fail("adv_visual_chunk_root_type", "chunk.tscn root must be a RigidBody2D")
		root.free()
		return

	_assert_visual_not_invisible_or_tiny(chunk_body, "chunk")

	root.free()


func test_player_visual_zindex_not_behind_floor_visual() -> void:
	var root: Node = _load_main_scene()
	if root == null:
		return

	var player: CharacterBody2D = _find_player(root)
	var floor: StaticBody2D = _find_floor(root)

	if player == null or floor == null:
		_fail("adv_visual_player_or_floor_missing",
			"Player or Floor node missing; cannot assert visual layering")
		root.free()
		return

	var player_visual: Node2D = _find_visual_child_2d(player)
	var floor_visual: Node2D = _find_visual_child_2d(floor)

	if player_visual == null or floor_visual == null:
		_fail("adv_visual_player_or_floor_visual_missing",
			"Player or Floor visual child missing; cannot assert z_index layering")
		root.free()
		return

	var z_ok: bool = player_visual.z_index >= floor_visual.z_index
	_assert_true(z_ok,
		"adv_visual_player_above_floor — player visual z_index is >= floor visual z_index for readability")

	root.free()


# ---------------------------------------------------------------------------
# Camera configuration: defaults, inversion, and basic consistency
# ---------------------------------------------------------------------------

func test_camera_limits_not_inverted_and_not_default_horizontal_box() -> void:
	var root: Node = _load_main_scene()
	if root == null:
		return

	var camera: Camera2D = _find_camera(root)
	if camera == null:
		_fail("adv_camera_exists", "Camera node not found as child of Player in test_movement.tscn")
		root.free()
		return

	if not (camera is CameraFollow):
		_fail("adv_camera_not_camera_follow",
			"Camera node is not using CameraFollow script; cannot assert follow limits for core scene")
		root.free()
		return

	var follow: CameraFollow = camera

	_assert_true(follow.follow_limit_left <= follow.follow_limit_right,
		"adv_camera_limits_horizontal_not_inverted — follow_limit_left <= follow_limit_right")
	_assert_true(follow.follow_limit_top <= follow.follow_limit_bottom,
		"adv_camera_limits_vertical_not_inverted — follow_limit_top <= follow_limit_bottom")

	var defaults_used: bool = (follow.follow_limit_left == -10000000 and follow.follow_limit_right == 10000000)
	_assert_false(defaults_used,
		"adv_camera_limits_horizontal_not_default — core scene overrides default infinite horizontal limits")

	root.free()


# ---------------------------------------------------------------------------
# UI hints: visibility and readability beyond mere presence
# ---------------------------------------------------------------------------

func test_ui_hints_labels_visible_and_with_min_line_height() -> void:
	var root: Node = _load_main_scene()
	if root == null:
		return

	var all_labels: Array = _collect_hint_labels(root)
	if all_labels.is_empty():
		_fail("adv_ui_hints_present_for_visibility_checks",
			"No move/jump/detach labels found for visibility checks")
		root.free()
		return

	for raw_label in all_labels:
		var label := raw_label as Label
		if label == null:
			continue

		_assert_true(label.visible,
			"adv_ui_hint_visible — hint label '%s' is visible" % label.text)

		var line_height: float = label.get_line_height()
		_assert_true(line_height >= 8.0,
			"adv_ui_hint_min_line_height — hint label '%s' has line height >= 8 for readability" % label.text)

	root.free()


func test_ui_hints_positions_outside_central_area_and_not_extreme() -> void:
	var root: Node = _load_main_scene()
	if root == null:
		return

	var all_labels: Array = _collect_hint_labels(root)
	if all_labels.is_empty():
		_fail("adv_ui_hints_present_for_position_checks",
			"No move/jump/detach labels found for position checks")
		root.free()
		return

	var central_bounds: Rect2 = _central_play_area_bounds(root)
	var center: Vector2 = central_bounds.position + central_bounds.size * 0.5

	var all_outside_and_nearby: bool = true
	for raw_label in all_labels:
		var label := raw_label as Label
		if label == null:
			continue

		# Reuse the same contract as the primary suite: hints must be outside
		# the central play area, but we also assert they are not arbitrarily
		# far away (to avoid off-screen placement at default resolutions).
		var pos: Vector2 = label.get_global_transform().origin
		var outside_central: bool = not _point_inside_rect(pos, central_bounds)
		var distance_to_center: float = center.distance_to(pos)
		var not_extreme_distance: bool = distance_to_center <= 2000.0

		all_outside_and_nearby = all_outside_and_nearby and outside_central and not_extreme_distance

	_assert_true(all_outside_and_nearby,
		"adv_ui_hints_outside_central_but_near — all move/jump/detach hints are outside central play area and within a sane distance")

	root.free()


# ---------------------------------------------------------------------------
# Human-playability metadata: ID uniqueness and per-step integrity
# ---------------------------------------------------------------------------

func test_manual_checklist_ids_unique_and_steps_non_empty() -> void:
	var checklist: Array = HumanPlayableCoreTests.HUMAN_PLAYABILITY_CHECKLIST
	if checklist.is_empty():
		_fail("adv_human_playability_metadata_non_empty",
			"HUMAN_PLAYABILITY_CHECKLIST must contain at least one entry")
		return

	var seen_ids := {}
	for entry in checklist:
		if not entry is Dictionary:
			_fail("adv_human_playability_metadata_entry_type",
				"Checklist entry is not a Dictionary")
			continue

		var id_present: bool = entry.has("id")
		var title_present: bool = entry.has("title")
		var steps_present: bool = entry.has("steps") and (entry["steps"] is Array)

		if not (id_present and title_present and steps_present):
			_fail("adv_human_playability_metadata_entry_missing_fields",
				"Checklist entry missing id/title/steps fields")
			continue

		var id_str: String = str(entry["id"])
		var is_unique: bool = not seen_ids.has(id_str)
		_assert_true(is_unique,
			"adv_human_playability_metadata_id_unique — checklist id '%s' is unique" % id_str)
		seen_ids[id_str] = true

		var steps: Array = entry["steps"]
		if steps.is_empty():
			_fail("adv_human_playability_metadata_steps_non_empty",
				"Checklist entry '%s' has no steps" % id_str)
			continue

		for step in steps:
			var step_text: String = str(step).strip_edges()
			_assert_true(step_text.length() > 0,
				"adv_human_playability_metadata_step_non_empty — checklist '%s' has non-empty step text" % id_str)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

func run_all() -> int:
	print("--- test_human_playable_core_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	# Visuals
	test_player_and_floor_visuals_not_invisible_or_tiny()
	test_chunk_visual_not_invisible_or_tiny()
	test_player_visual_zindex_not_behind_floor_visual()

	# Camera configuration
	test_camera_limits_not_inverted_and_not_default_horizontal_box()

	# UI hints
	test_ui_hints_labels_visible_and_with_min_line_height()
	test_ui_hints_positions_outside_central_area_and_not_extreme()

	# Human-playability metadata
	test_manual_checklist_ids_unique_and_steps_non_empty()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count

