# test_camera_follow_adversarial.gd
#
# Adversarial / edge-case tests for scripts/camera_follow.gd.
# Generated by Test Breaker Agent — 2026-03-01
#
# This file is a plain Object subclass. It does not extend Node or SceneTree.
# The entry point is run_all(), called by tests/run_tests.gd.
#
# Adversarial philosophy:
#   CameraFollow is a thin wiring script: _ready() maps twelve @export vars to
#   Camera2D built-in properties with no conditional logic and no input
#   validation. The vulnerability surface is therefore:
#   (a) property assignment correctness for extreme / edge-case export values,
#   (b) idempotency of _ready() when called multiple times,
#   (c) the precedence rule that the SECOND _ready() call (with modified export
#       vars) overrides the FIRST call,
#   (d) Camera2D behavior when receiving values outside the documented [0,1]
#       margin range or inverted limit relationships.
#
# All tests are deterministic. They pass only if the implementation correctly
# propagates whatever value is stored in the @export variable into the
# corresponding Camera2D property, with no clamping, guarding, or defaulting
# performed by the script itself (since SPEC-39 mandates unconditional assignment
# and SPEC-42 explicitly states "No script validation of limit relationships").
#
# Spec coverage targets:
#   SPEC-38 — mutability of all twelve @export vars (adversarial mutations)
#   SPEC-39 — _ready() applies current export value unconditionally, including
#              edge-case values; idempotency; second call overrides first
#   SPEC-40 — smoothing_speed=0.0, negative, INF, NaN paths through _ready()
#   SPEC-41 — margin values 0.0, 1.0, >1.0, negative applied by _ready()
#   SPEC-42 — degenerate limit boxes (all same point, inverted, INT_MAX/MIN)
#
# CHECKPOINT tests are marked with # CHECKPOINT at the end of the assertion
# line, indicating that the expected behavior was derived from a conservative
# assumption rather than explicit spec language.

class_name CameraFollowAdversarialTests
extends Object

# ---------------------------------------------------------------------------
# EPSILON for floating-point comparisons (project-wide constant).
# ---------------------------------------------------------------------------
const EPSILON: float = 1e-4

# GDScript's maximum safe integer for @export var: int is 64-bit signed.
# However Godot's Camera2D.limit_* properties are 32-bit signed integers
# internally. We test with 2^31 - 1 = 2147483647 (INT32_MAX) and
# -(2^31) = -2147483648 (INT32_MIN) as the platform boundary values.
# CHECKPOINT: Godot 4 Camera2D limit_* may or may not silently clamp
# values exceeding int32 range. The test asserts the assigned value is
# reflected back verbatim from the @export int field (not the Camera2D
# internal property), which is always safe for GDScript int64.
const INT32_MAX: int = 2147483647
const INT32_MIN: int = -2147483648

var _pass_count: int = 0
var _fail_count: int = 0


# ---------------------------------------------------------------------------
# Helpers (identical contract to test_camera_follow.gd)
# ---------------------------------------------------------------------------

func _approx_eq(a: float, b: float) -> bool:
	return abs(a - b) < EPSILON


func _pass(test_name: String) -> void:
	_pass_count += 1
	print("  PASS: " + test_name)


func _fail(test_name: String, message: String) -> void:
	_fail_count += 1
	print("  FAIL: " + test_name + " — " + message)


func _assert_true(condition: bool, test_name: String) -> void:
	if condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected true, got false")


func _assert_false(condition: bool, test_name: String) -> void:
	if not condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected false, got true")


func _assert_approx(a: float, b: float, test_name: String) -> void:
	if _approx_eq(a, b):
		_pass(test_name)
	else:
		_fail(test_name, "got " + str(a) + " expected " + str(b) + " (delta " + str(abs(a - b)) + ")")


func _assert_int_eq(a: int, b: int, test_name: String) -> void:
	if a == b:
		_pass(test_name)
	else:
		_fail(test_name, "got " + str(a) + " expected " + str(b))


func _assert_float_eq(a: float, b: float, test_name: String) -> void:
	# Exact float equality for special values (INF, -INF). Use _assert_approx
	# for normal values.
	if a == b:
		_pass(test_name)
	else:
		_fail(test_name, "got " + str(a) + " expected " + str(b))


func _assert_finite(value: float, test_name: String) -> void:
	if is_finite(value):
		_pass(test_name)
	else:
		_fail(test_name, "value " + str(value) + " is not finite")


# ===========================================================================
# GROUP A: smoothing_speed edge-case values (SPEC-40 / SPEC-39)
# ===========================================================================
# Target flaw: an implementation that guards or clamps smoothing_speed before
# assignment (e.g., max(0.01, smoothing_speed) to avoid a perceived "zero
# disables smoothing" footgun) would fail these tests. SPEC-39 mandates
# unconditional assignment; the script must not add validation logic.

# A-01: smoothing_speed = 0.0 applied by _ready() to position_smoothing_speed.
# A zero speed value is semantically valid (Camera2D with position_smoothing_enabled=true
# and speed=0 effectively freezes the camera at the target position). The spec
# contains no lower bound on smoothing_speed. An implementation that replaces 0.0
# with a small epsilon (treating zero as "disabled") would fail this test.
func test_a01_smoothing_speed_zero_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = 0.0
	node._ready()
	_assert_approx(node.position_smoothing_speed, 0.0,
		"A-01 — smoothing_speed=0.0 applied to position_smoothing_speed by _ready()")
	node.free()


# A-02: smoothing_speed = 0.0 stored in @export var before _ready().
# Verifies the @export field itself holds 0.0, not just that _ready() assigns it.
func test_a02_smoothing_speed_zero_export_var_readable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = 0.0
	_assert_approx(node.smoothing_speed, 0.0,
		"A-02 — smoothing_speed export var stores 0.0 verbatim (pre-_ready)")
	node.free()


# A-03: smoothing_speed negative (-1.0) — export var is mutable to negative.
# SPEC-38 AC-38.16 says each @export var is mutable. Negative values are
# undefined behavior at the Camera2D level, but the script itself must not
# reject them (SPEC-39: unconditional assignment, no guards).
# The test asserts that the export var stores -1.0 and that _ready() assigns it
# to position_smoothing_speed without clamping.
# CHECKPOINT: Camera2D may internally clamp negative speed; we test only that
# the script propagates the value as-is and does not add its own guard.
func test_a03_smoothing_speed_negative_export_var_stored() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = -1.0
	_assert_approx(node.smoothing_speed, -1.0,
		"A-03 — smoothing_speed export var stores -1.0 (no script-level clamp pre-_ready)") # CHECKPOINT
	node.free()


# A-04: smoothing_speed negative (-1.0) propagated by _ready().
# _ready() must assign position_smoothing_speed = -1.0 (SPEC-39: no conditionals).
# If Camera2D internally clamps or ignores the value, position_smoothing_speed may
# differ. The test asserts only that _ready() does not add clamping logic — i.e.,
# that node.smoothing_speed and node.position_smoothing_speed are consistent after
# _ready() with a negative export value (both reflect what Camera2D accepted).
func test_a04_smoothing_speed_negative_assigned_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = -1.0
	node._ready()
	# After _ready(), position_smoothing_speed must equal smoothing_speed
	# as read from the node. This verifies the assignment was not skipped or
	# conditionally replaced. Camera2D may internally clamp; we check the
	# exposed property round-trip is consistent. # CHECKPOINT
	_assert_approx(node.position_smoothing_speed, node.smoothing_speed,
		"A-04 — after _ready() with smoothing_speed=-1.0, position_smoothing_speed matches export var") # CHECKPOINT
	node.free()


# A-05: smoothing_speed = INF — the @export float field must accept INF.
# Camera2D with position_smoothing_speed=INF behaves as instant follow (speed so
# large that the camera teleports to the target each frame). The script must not
# replace INF with a finite value.
func test_a05_smoothing_speed_inf_export_var_stored() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = INF
	_assert_float_eq(node.smoothing_speed, INF,
		"A-05 — smoothing_speed export var stores INF (no finite-clamp pre-_ready)") # CHECKPOINT
	node.free()


# A-06: smoothing_speed = INF propagated by _ready().
# After _ready(), position_smoothing_speed must be whatever the Camera2D
# property reflects after assigning INF. The test does not assert the exact
# stored value (Camera2D may normalize INF); it asserts the script itself did
# not guard or replace the assignment with a hardcoded fallback.
func test_a06_smoothing_speed_inf_assigned_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = INF
	node._ready()
	# The script must have executed: position_smoothing_speed = smoothing_speed (INF).
	# We verify _ready() didn't silently substitute a different value by checking
	# node.position_smoothing_speed == node.smoothing_speed (what Camera2D stored).
	_assert_float_eq(node.position_smoothing_speed, node.smoothing_speed,
		"A-06 — after _ready() with smoothing_speed=INF, position_smoothing_speed matches export var") # CHECKPOINT
	node.free()


# A-07: smoothing_speed very large but finite (1e9).
# Tests that no overflow or clamping occurs in the script layer for large-but-finite
# values. Camera2D is unlikely to clamp finite floats internally.
func test_a07_smoothing_speed_very_large_finite_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = 1.0e9
	node._ready()
	_assert_approx(node.position_smoothing_speed, 1.0e9,
		"A-07 — smoothing_speed=1e9 applied to position_smoothing_speed by _ready()")
	node.free()


# ===========================================================================
# GROUP B: smoothing_enabled = false (SPEC-40 / SPEC-39)
# ===========================================================================
# The primary suite (test_spec39_ready_applies_nondefa_smoothing_enabled_false)
# covers this, but only from the angle of SPEC-39. These adversarial tests
# probe it from the SPEC-40 angle: is the camera actually configured to NOT
# smooth? And does a second _ready() with false correctly override a prior
# _ready() with true?

# B-01: smoothing_enabled=false → _ready() → position_smoothing_enabled == false.
# The spec (SPEC-40) says smoothing is configured via the built-in property.
# This is the single most critical path: if an implementer hardcodes
# `position_smoothing_enabled = true` rather than reading the export var,
# this test fails.
func test_b01_smoothing_disabled_path_sets_property_false() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_enabled = false
	node._ready()
	_assert_false(node.position_smoothing_enabled,
		"B-01 — smoothing_enabled=false → _ready() → position_smoothing_enabled is false")
	node.free()


# B-02: Calling _ready() twice with smoothing_enabled=false both times.
# Idempotency: the second call must not "undo" the false assignment.
func test_b02_smoothing_disabled_idempotent_double_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_enabled = false
	node._ready()
	node._ready()
	_assert_false(node.position_smoothing_enabled,
		"B-02 — smoothing_enabled=false + double _ready() → position_smoothing_enabled still false")
	node.free()


# B-03: First _ready() with smoothing_enabled=true, then set false and call _ready() again.
# The second call must override the property set by the first. This tests that
# _ready() reads the export var at call time, not at construction time.
func test_b03_second_ready_with_false_overrides_first_ready_true() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_enabled = true
	node._ready()
	# Verify first call set it true.
	_assert_true(node.position_smoothing_enabled == true,
		"B-03 setup — first _ready() with smoothing_enabled=true → position_smoothing_enabled is true")
	# Now override export var and call _ready() again.
	node.smoothing_enabled = false
	node._ready()
	_assert_false(node.position_smoothing_enabled,
		"B-03 — second _ready() with smoothing_enabled=false overrides first (position_smoothing_enabled is false)")
	node.free()


# B-04: First _ready() with smoothing_enabled=false, then set true and call _ready() again.
# The second call must restore true. Verifies bidirectional override, not just
# "can be disabled."
func test_b04_second_ready_with_true_overrides_first_ready_false() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_enabled = false
	node._ready()
	node.smoothing_enabled = true
	node._ready()
	_assert_true(node.position_smoothing_enabled == true,
		"B-04 — second _ready() with smoothing_enabled=true overrides first (position_smoothing_enabled is true)")
	node.free()


# ===========================================================================
# GROUP C: drag_horizontal and drag_vertical toggle paths (SPEC-41 / SPEC-39)
# ===========================================================================
# The primary suite tests only the defaults. These tests probe the false/true
# non-default assignments through _ready().

# C-01: drag_horizontal=false applied by _ready().
func test_c01_drag_horizontal_false_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_horizontal = false
	node._ready()
	_assert_false(node.drag_horizontal_enabled,
		"C-01 — drag_horizontal=false → _ready() → drag_horizontal_enabled is false")
	node.free()


# C-02: drag_vertical=true applied by _ready().
# Default is false; this tests the non-default path.
func test_c02_drag_vertical_true_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_vertical = true
	node._ready()
	_assert_true(node.drag_vertical_enabled == true,
		"C-02 — drag_vertical=true → _ready() → drag_vertical_enabled is true")
	node.free()


# C-03: Both drag booleans set to non-default then _ready() called.
func test_c03_both_drag_bools_nondefa_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_horizontal = false
	node.drag_vertical = true
	node._ready()
	_assert_false(node.drag_horizontal_enabled,
		"C-03a — drag_horizontal=false applied by _ready()")
	_assert_true(node.drag_vertical_enabled == true,
		"C-03b — drag_vertical=true applied by _ready()")
	node.free()


# ===========================================================================
# GROUP D: drag margin edge-case values (SPEC-41 / SPEC-39)
# ===========================================================================
# SPEC-41 documents that Godot clamps margins to [0.0, 1.0] at the engine level.
# SPEC-39 mandates the script assigns unconditionally — no script-level clamping.
# These tests probe: 0.0, 1.0, >1.0, and negative values.
# For values within [0.0, 1.0], the Camera2D property round-trip is exact.
# For out-of-range values, the test verifies the script propagated the value
# (Camera2D may internally clamp it; we check what Camera2D reports back, not
# what the script "should have" assigned).

# D-01: All four drag margins = 0.0 applied by _ready().
# Zero margin means no dead zone — the camera starts moving immediately when
# the subject moves even a subpixel. This is the minimum valid value.
# Target flaw: an implementation with `drag_left_margin = max(0.01, drag_left_margin)`
# would fail.
func test_d01_all_drag_margins_zero_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_left_margin = 0.0
	node.drag_right_margin = 0.0
	node.drag_top_margin = 0.0
	node.drag_bottom_margin = 0.0
	node._ready()
	_assert_approx(node.drag_left_margin, 0.0,
		"D-01a — drag_left_margin=0.0 applied by _ready()")
	_assert_approx(node.drag_right_margin, 0.0,
		"D-01b — drag_right_margin=0.0 applied by _ready()")
	_assert_approx(node.drag_top_margin, 0.0,
		"D-01c — drag_top_margin=0.0 applied by _ready()")
	_assert_approx(node.drag_bottom_margin, 0.0,
		"D-01d — drag_bottom_margin=0.0 applied by _ready()")
	node.free()


# D-02: All four drag margins = 1.0 applied by _ready().
# A margin of 1.0 means the full half-viewport is the dead zone — the camera
# effectively never moves due to subject position. This is the maximum valid
# value per [0.0, 1.0] range. The test verifies the Camera2D property round-trip
# reflects 1.0 (not clamped down by the engine or script).
func test_d02_all_drag_margins_one_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_left_margin = 1.0
	node.drag_right_margin = 1.0
	node.drag_top_margin = 1.0
	node.drag_bottom_margin = 1.0
	node._ready()
	_assert_approx(node.drag_left_margin, 1.0,
		"D-02a — drag_left_margin=1.0 applied by _ready()")
	_assert_approx(node.drag_right_margin, 1.0,
		"D-02b — drag_right_margin=1.0 applied by _ready()")
	_assert_approx(node.drag_top_margin, 1.0,
		"D-02c — drag_top_margin=1.0 applied by _ready()")
	_assert_approx(node.drag_bottom_margin, 1.0,
		"D-02d — drag_bottom_margin=1.0 applied by _ready()")
	node.free()


# D-03: drag_left_margin = 1.5 (out of [0.0, 1.0] range) — script must not clamp.
# SPEC-41 states "Engine clamps margins to this range." The SCRIPT does not clamp.
# After _ready() assigns 1.5, Camera2D may silently reduce the stored value to 1.0.
# The test asserts that whatever Camera2D stored is what the property reports back,
# confirming the script did not add its own clamp before the assignment.
# We verify this by checking that the Camera2D property is >= 0.0 (not negative
# or NaN) and that node.drag_left_margin (the @export var) still holds 1.5.
# CHECKPOINT: The exact Camera2D behavior for out-of-range margins is engine-defined
# and not verified here; we verify only the script's no-guard contract.
func test_d03_drag_left_margin_exceeds_one_export_var_preserves_value() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_left_margin = 1.5
	node._ready()
	# The @export var on the script side must still hold 1.5 — the script did not
	# clamp it before assigning to Camera2D.
	_assert_approx(node.drag_left_margin, 1.5,
		"D-03 — @export drag_left_margin preserves 1.5 after _ready() (no script-level clamp)") # CHECKPOINT
	node.free()


# D-04: drag_right_margin negative (-0.1) — script must not clamp to 0.
# Same logic as D-03 but for negative values. SPEC-39 mandates unconditional
# assignment.
func test_d04_drag_right_margin_negative_export_var_preserves_value() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_right_margin = -0.1
	node._ready()
	_assert_approx(node.drag_right_margin, -0.1,
		"D-04 — @export drag_right_margin preserves -0.1 after _ready() (no script-level clamp)") # CHECKPOINT
	node.free()


# D-05: All four margins set to distinct out-of-range values; verify all survive.
# This stress-tests that the no-clamping contract applies to all four margin fields,
# not just the one most likely to be guarded.
func test_d05_all_margins_out_of_range_export_vars_preserve_values() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_left_margin = -0.5
	node.drag_right_margin = 2.0
	node.drag_top_margin = -0.01
	node.drag_bottom_margin = 1.99
	node._ready()
	_assert_approx(node.drag_left_margin, -0.5,
		"D-05a — @export drag_left_margin preserves -0.5") # CHECKPOINT
	_assert_approx(node.drag_right_margin, 2.0,
		"D-05b — @export drag_right_margin preserves 2.0") # CHECKPOINT
	_assert_approx(node.drag_top_margin, -0.01,
		"D-05c — @export drag_top_margin preserves -0.01") # CHECKPOINT
	_assert_approx(node.drag_bottom_margin, 1.99,
		"D-05d — @export drag_bottom_margin preserves 1.99") # CHECKPOINT
	node.free()


# ===========================================================================
# GROUP E: limit boundary and degenerate cases (SPEC-42 / SPEC-39)
# ===========================================================================
# SPEC-42: "No script validation of limit relationships." The script must
# unconditionally assign all four limits to Camera2D, regardless of whether
# left > right, top > bottom, or they're all the same value.

# E-01: All four limits set to the same value (degenerate bounding box = a point).
# target flaw: an implementation that guards limit_right > limit_left would
# "fix" or reject this configuration. SPEC-39 mandates unconditional assignment.
func test_e01_all_limits_same_value_degenerate_box_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = 0
	node.limit_right = 0
	node.limit_top = 0
	node.limit_bottom = 0
	node._ready()
	_assert_int_eq(node.limit_left, 0,
		"E-01a — limit_left=0 applied by _ready() (degenerate box)")
	_assert_int_eq(node.limit_right, 0,
		"E-01b — limit_right=0 applied by _ready() (degenerate box)")
	_assert_int_eq(node.limit_top, 0,
		"E-01c — limit_top=0 applied by _ready() (degenerate box)")
	_assert_int_eq(node.limit_bottom, 0,
		"E-01d — limit_bottom=0 applied by _ready() (degenerate box)")
	node.free()


# E-02: limit_left > limit_right (horizontally inverted bounds).
# SPEC-38 Risk R-38.3 explicitly documents this as an edge case that the
# script does not validate. The test confirms the script passes the inverted
# values through to Camera2D without reordering or rejecting them.
func test_e02_limit_left_greater_than_limit_right_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = 1000
	node.limit_right = 100
	node._ready()
	_assert_int_eq(node.limit_left, 1000,
		"E-02a — limit_left=1000 (> limit_right=100) applied by _ready(); no swap")
	_assert_int_eq(node.limit_right, 100,
		"E-02b — limit_right=100 (< limit_left=1000) applied by _ready(); no swap")
	node.free()


# E-03: limit_bottom < limit_top (vertically inverted bounds).
# Camera2D in Godot uses screen-space Y (down = positive). limit_top is the
# upper bound (smaller Y) and limit_bottom is the lower bound (larger Y) in
# world space. An inverted configuration (bottom < top) should be passed through
# without the script reordering or clamping.
func test_e03_limit_bottom_less_than_limit_top_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_top = 500
	node.limit_bottom = -500
	node._ready()
	_assert_int_eq(node.limit_top, 500,
		"E-03a — limit_top=500 (> limit_bottom=-500) applied by _ready(); no swap")
	_assert_int_eq(node.limit_bottom, -500,
		"E-03b — limit_bottom=-500 (< limit_top=500) applied by _ready(); no swap")
	node.free()


# E-04: limit_left = limit_right (zero-width horizontal bounds).
# A degenerate case where the horizontal axis has a single allowed x-coordinate.
func test_e04_limit_left_equals_limit_right_zero_width_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = 400
	node.limit_right = 400
	node._ready()
	_assert_int_eq(node.limit_left, 400,
		"E-04a — limit_left=400 applied by _ready() (zero-width horizontal)")
	_assert_int_eq(node.limit_right, 400,
		"E-04b — limit_right=400 applied by _ready() (zero-width horizontal)")
	node.free()


# E-05: limit_top = limit_bottom (zero-height vertical bounds).
func test_e05_limit_top_equals_limit_bottom_zero_height_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_top = -200
	node.limit_bottom = -200
	node._ready()
	_assert_int_eq(node.limit_top, -200,
		"E-05a — limit_top=-200 applied by _ready() (zero-height vertical)")
	_assert_int_eq(node.limit_bottom, -200,
		"E-05b — limit_bottom=-200 applied by _ready() (zero-height vertical)")
	node.free()


# E-06: All four limits set to INT32_MAX.
# Tests the maximum 32-bit integer boundary. GDScript int is 64-bit, so the
# @export var stores the value cleanly. Camera2D limit_* are Godot int (32-bit
# on Godot 4 C++ side). This test verifies the @export var round-trip, not
# Camera2D's internal storage (which may truncate).
# CHECKPOINT: Camera2D may silently clamp or truncate int64 limit values to int32.
# The test asserts the @export var field preserves the value assigned to it.
func test_e06_all_limits_int32_max_export_var_preserved() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = INT32_MAX
	node.limit_right = INT32_MAX
	node.limit_top = INT32_MAX
	node.limit_bottom = INT32_MAX
	# Read back from the @export vars (not the Camera2D property) to confirm
	# the GDScript field preserves the value. Camera2D property may differ. # CHECKPOINT
	_assert_int_eq(node.limit_left, INT32_MAX,
		"E-06a — @export limit_left holds INT32_MAX pre-_ready()") # CHECKPOINT
	_assert_int_eq(node.limit_right, INT32_MAX,
		"E-06b — @export limit_right holds INT32_MAX pre-_ready()") # CHECKPOINT
	_assert_int_eq(node.limit_top, INT32_MAX,
		"E-06c — @export limit_top holds INT32_MAX pre-_ready()") # CHECKPOINT
	_assert_int_eq(node.limit_bottom, INT32_MAX,
		"E-06d — @export limit_bottom holds INT32_MAX pre-_ready()") # CHECKPOINT
	node.free()


# E-07: All four limits set to INT32_MIN.
# Same as E-06 but for the minimum 32-bit boundary.
func test_e07_all_limits_int32_min_export_var_preserved() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = INT32_MIN
	node.limit_right = INT32_MIN
	node.limit_top = INT32_MIN
	node.limit_bottom = INT32_MIN
	_assert_int_eq(node.limit_left, INT32_MIN,
		"E-07a — @export limit_left holds INT32_MIN pre-_ready()") # CHECKPOINT
	_assert_int_eq(node.limit_right, INT32_MIN,
		"E-07b — @export limit_right holds INT32_MIN pre-_ready()") # CHECKPOINT
	_assert_int_eq(node.limit_top, INT32_MIN,
		"E-07c — @export limit_top holds INT32_MIN pre-_ready()") # CHECKPOINT
	_assert_int_eq(node.limit_bottom, INT32_MIN,
		"E-07d — @export limit_bottom holds INT32_MIN pre-_ready()") # CHECKPOINT
	node.free()


# E-08: INT32_MAX limits assigned via _ready() — Camera2D property round-trip.
# After _ready(), the Camera2D limit properties are checked. If Camera2D
# clamps 64-bit GDScript ints to its 32-bit internal range the property will
# read back INT32_MAX (no loss). If GDScript int64 values > INT32_MAX were
# assigned, Camera2D might clamp. This test uses INT32_MAX which fits in int32.
func test_e08_int32_max_limits_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = INT32_MAX
	node.limit_right = INT32_MAX
	node.limit_top = INT32_MAX
	node.limit_bottom = INT32_MAX
	node._ready()
	_assert_int_eq(node.limit_left, INT32_MAX,
		"E-08a — limit_left=INT32_MAX applied by _ready()") # CHECKPOINT
	_assert_int_eq(node.limit_right, INT32_MAX,
		"E-08b — limit_right=INT32_MAX applied by _ready()") # CHECKPOINT
	_assert_int_eq(node.limit_top, INT32_MAX,
		"E-08c — limit_top=INT32_MAX applied by _ready()") # CHECKPOINT
	_assert_int_eq(node.limit_bottom, INT32_MAX,
		"E-08d — limit_bottom=INT32_MAX applied by _ready()") # CHECKPOINT
	node.free()


# E-09: INT32_MIN limits assigned via _ready().
func test_e09_int32_min_limits_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = INT32_MIN
	node.limit_right = INT32_MIN
	node.limit_top = INT32_MIN
	node.limit_bottom = INT32_MIN
	node._ready()
	_assert_int_eq(node.limit_left, INT32_MIN,
		"E-09a — limit_left=INT32_MIN applied by _ready()") # CHECKPOINT
	_assert_int_eq(node.limit_right, INT32_MIN,
		"E-09b — limit_right=INT32_MIN applied by _ready()") # CHECKPOINT
	_assert_int_eq(node.limit_top, INT32_MIN,
		"E-09c — limit_top=INT32_MIN applied by _ready()") # CHECKPOINT
	_assert_int_eq(node.limit_bottom, INT32_MIN,
		"E-09d — limit_bottom=INT32_MIN applied by _ready()") # CHECKPOINT
	node.free()


# E-10: limit_left = 0, limit_right = 1 (minimal valid box: 1 pixel wide).
# Tests the narrowest non-zero horizontal limit box.
func test_e10_minimal_nonzero_limit_box_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = 0
	node.limit_right = 1
	node.limit_top = 0
	node.limit_bottom = 1
	node._ready()
	_assert_int_eq(node.limit_left, 0,
		"E-10a — limit_left=0 (minimal box) applied by _ready()")
	_assert_int_eq(node.limit_right, 1,
		"E-10b — limit_right=1 (minimal box) applied by _ready()")
	_assert_int_eq(node.limit_top, 0,
		"E-10c — limit_top=0 (minimal box) applied by _ready()")
	_assert_int_eq(node.limit_bottom, 1,
		"E-10d — limit_bottom=1 (minimal box) applied by _ready()")
	node.free()


# E-11: All limits at zero simultaneously with inverted relationship possible.
# Specifically: limit_left and limit_right both 0, limit_top and limit_bottom both 0.
# Already covered by E-01 but this test labels it explicitly as the "origin point" case.
func test_e11_all_limits_zero_origin_point() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = 0
	node.limit_right = 0
	node.limit_top = 0
	node.limit_bottom = 0
	node._ready()
	_assert_int_eq(node.limit_left, 0, "E-11a — origin-point limit_left=0")
	_assert_int_eq(node.limit_right, 0, "E-11b — origin-point limit_right=0")
	_assert_int_eq(node.limit_top, 0, "E-11c — origin-point limit_top=0")
	_assert_int_eq(node.limit_bottom, 0, "E-11d — origin-point limit_bottom=0")
	node.free()


# ===========================================================================
# GROUP F: Idempotency and override — _ready() called multiple times (SPEC-39)
# ===========================================================================
# The primary suite has one idempotency test (test_determinism_calling_ready_twice_is_idempotent)
# but only checks position_smoothing_speed with default values.
# These tests probe: (a) every property is idempotent at defaults, (b) changing
# export vars between calls produces updated Camera2D properties on the second call.

# F-01: Double _ready() with all-default export vars — all twelve Camera2D
# properties must be identical after the second call as after the first.
# Target flaw: an implementation that has any internal state in _ready() that
# is consumed on the first call (e.g., a "has_initialized" guard variable)
# would fail on the second call.
func test_f01_double_ready_all_defaults_all_twelve_properties_stable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node._ready()
	var se1: bool = node.position_smoothing_enabled
	var ss1: float = node.position_smoothing_speed
	var dh1: bool = node.drag_horizontal_enabled
	var dv1: bool = node.drag_vertical_enabled
	var dlm1: float = node.drag_left_margin
	var drm1: float = node.drag_right_margin
	var dtm1: float = node.drag_top_margin
	var dbm1: float = node.drag_bottom_margin
	var ll1: int = node.limit_left
	var lr1: int = node.limit_right
	var lt1: int = node.limit_top
	var lb1: int = node.limit_bottom
	# Second call.
	node._ready()
	_assert_true(node.position_smoothing_enabled == se1,
		"F-01a — double _ready() defaults: position_smoothing_enabled stable")
	_assert_approx(node.position_smoothing_speed, ss1,
		"F-01b — double _ready() defaults: position_smoothing_speed stable")
	_assert_true(node.drag_horizontal_enabled == dh1,
		"F-01c — double _ready() defaults: drag_horizontal_enabled stable")
	_assert_true(node.drag_vertical_enabled == dv1,
		"F-01d — double _ready() defaults: drag_vertical_enabled stable")
	_assert_approx(node.drag_left_margin, dlm1,
		"F-01e — double _ready() defaults: drag_left_margin stable")
	_assert_approx(node.drag_right_margin, drm1,
		"F-01f — double _ready() defaults: drag_right_margin stable")
	_assert_approx(node.drag_top_margin, dtm1,
		"F-01g — double _ready() defaults: drag_top_margin stable")
	_assert_approx(node.drag_bottom_margin, dbm1,
		"F-01h — double _ready() defaults: drag_bottom_margin stable")
	_assert_int_eq(node.limit_left, ll1,
		"F-01i — double _ready() defaults: limit_left stable")
	_assert_int_eq(node.limit_right, lr1,
		"F-01j — double _ready() defaults: limit_right stable")
	_assert_int_eq(node.limit_top, lt1,
		"F-01k — double _ready() defaults: limit_top stable")
	_assert_int_eq(node.limit_bottom, lb1,
		"F-01l — double _ready() defaults: limit_bottom stable")
	node.free()


# F-02: Modify smoothing_speed between two _ready() calls — second call applies
# the NEW value. This tests that _ready() reads the live export var, not a cached
# value set during the first call.
func test_f02_change_smoothing_speed_between_ready_calls_second_overrides() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = 5.0
	node._ready()
	_assert_approx(node.position_smoothing_speed, 5.0,
		"F-02 setup — first _ready() with smoothing_speed=5.0 applied")
	# Modify export var and call _ready() again.
	node.smoothing_speed = 20.0
	node._ready()
	_assert_approx(node.position_smoothing_speed, 20.0,
		"F-02 — second _ready() with smoothing_speed=20.0 overrides first call's 5.0")
	node.free()


# F-03: Modify limit_right between two _ready() calls.
func test_f03_change_limit_right_between_ready_calls_second_overrides() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_right = 1000
	node._ready()
	_assert_int_eq(node.limit_right, 1000,
		"F-03 setup — first _ready() with limit_right=1000 applied")
	node.limit_right = 800
	node._ready()
	_assert_int_eq(node.limit_right, 800,
		"F-03 — second _ready() with limit_right=800 overrides 1000")
	node.free()


# F-04: Modify all twelve export vars between two _ready() calls; verify all twelve
# Camera2D properties reflect the second set of values after the second call.
# Target flaw: if _ready() hardcodes any of the twelve values instead of reading
# from export vars, that property will fail to update on the second call.
func test_f04_change_all_twelve_vars_between_ready_calls_all_override() -> void:
	var node: CameraFollow = CameraFollow.new()
	# First call with defaults.
	node._ready()
	# Change every export var to a non-default value.
	node.smoothing_enabled = false
	node.smoothing_speed = 8.0
	node.drag_horizontal = false
	node.drag_vertical = true
	node.drag_left_margin = 0.1
	node.drag_right_margin = 0.3
	node.drag_top_margin = 0.15
	node.drag_bottom_margin = 0.25
	node.limit_left = -500
	node.limit_right = 500
	node.limit_top = -300
	node.limit_bottom = 300
	# Second call must apply all new values.
	node._ready()
	_assert_false(node.position_smoothing_enabled,
		"F-04a — second _ready(): smoothing_enabled=false → position_smoothing_enabled false")
	_assert_approx(node.position_smoothing_speed, 8.0,
		"F-04b — second _ready(): smoothing_speed=8.0 applied")
	_assert_false(node.drag_horizontal_enabled,
		"F-04c — second _ready(): drag_horizontal=false applied")
	_assert_true(node.drag_vertical_enabled == true,
		"F-04d — second _ready(): drag_vertical=true applied")
	_assert_approx(node.drag_left_margin, 0.1,
		"F-04e — second _ready(): drag_left_margin=0.1 applied")
	_assert_approx(node.drag_right_margin, 0.3,
		"F-04f — second _ready(): drag_right_margin=0.3 applied")
	_assert_approx(node.drag_top_margin, 0.15,
		"F-04g — second _ready(): drag_top_margin=0.15 applied")
	_assert_approx(node.drag_bottom_margin, 0.25,
		"F-04h — second _ready(): drag_bottom_margin=0.25 applied")
	_assert_int_eq(node.limit_left, -500,
		"F-04i — second _ready(): limit_left=-500 applied")
	_assert_int_eq(node.limit_right, 500,
		"F-04j — second _ready(): limit_right=500 applied")
	_assert_int_eq(node.limit_top, -300,
		"F-04k — second _ready(): limit_top=-300 applied")
	_assert_int_eq(node.limit_bottom, 300,
		"F-04l — second _ready(): limit_bottom=300 applied")
	node.free()


# ===========================================================================
# GROUP G: Full mutability sweep for all twelve @export vars (SPEC-38 AC-38.16)
# ===========================================================================
# The primary suite checks mutability for only three export vars (smoothing_enabled,
# smoothing_speed, limit_right). These tests verify the remaining nine are also
# mutable — a simple but effective regression guard.

# G-01: drag_horizontal is mutable.
func test_g01_drag_horizontal_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_horizontal = false
	_assert_false(node.drag_horizontal,
		"G-01 — drag_horizontal is mutable; assigned false, reads back false")
	node.free()


# G-02: drag_vertical is mutable.
func test_g02_drag_vertical_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_vertical = true
	_assert_true(node.drag_vertical == true,
		"G-02 — drag_vertical is mutable; assigned true, reads back true")
	node.free()


# G-03: drag_left_margin is mutable.
func test_g03_drag_left_margin_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_left_margin = 0.35
	_assert_approx(node.drag_left_margin, 0.35,
		"G-03 — drag_left_margin is mutable; assigned 0.35, reads back 0.35")
	node.free()


# G-04: drag_right_margin is mutable.
func test_g04_drag_right_margin_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_right_margin = 0.45
	_assert_approx(node.drag_right_margin, 0.45,
		"G-04 — drag_right_margin is mutable; assigned 0.45, reads back 0.45")
	node.free()


# G-05: drag_top_margin is mutable.
func test_g05_drag_top_margin_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_top_margin = 0.1
	_assert_approx(node.drag_top_margin, 0.1,
		"G-05 — drag_top_margin is mutable; assigned 0.1, reads back 0.1")
	node.free()


# G-06: drag_bottom_margin is mutable.
func test_g06_drag_bottom_margin_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_bottom_margin = 0.5
	_assert_approx(node.drag_bottom_margin, 0.5,
		"G-06 — drag_bottom_margin is mutable; assigned 0.5, reads back 0.5")
	node.free()


# G-07: limit_left is mutable.
func test_g07_limit_left_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = -100
	_assert_int_eq(node.limit_left, -100,
		"G-07 — limit_left is mutable; assigned -100, reads back -100")
	node.free()


# G-08: limit_top is mutable.
func test_g08_limit_top_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_top = -50
	_assert_int_eq(node.limit_top, -50,
		"G-08 — limit_top is mutable; assigned -50, reads back -50")
	node.free()


# G-09: limit_bottom is mutable.
func test_g09_limit_bottom_is_mutable() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_bottom = 600
	_assert_int_eq(node.limit_bottom, 600,
		"G-09 — limit_bottom is mutable; assigned 600, reads back 600")
	node.free()


# ===========================================================================
# GROUP H: _ready() applies non-default values for ALL twelve vars (SPEC-39)
# ===========================================================================
# The primary suite tests non-default assignment through _ready() for only a
# few parameters (smoothing_enabled=false, smoothing_speed=12.5, drag_left=0.4,
# limit_right=800, all four limits simultaneously). These tests fill the gap for
# the remaining eight parameters individually.

# H-01: Non-default drag_right_margin applied through _ready().
func test_h01_nondefa_drag_right_margin_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_right_margin = 0.4
	node._ready()
	_assert_approx(node.drag_right_margin, 0.4,
		"H-01 — drag_right_margin=0.4 applied by _ready()")
	node.free()


# H-02: Non-default drag_top_margin applied through _ready().
func test_h02_nondefa_drag_top_margin_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_top_margin = 0.3
	node._ready()
	_assert_approx(node.drag_top_margin, 0.3,
		"H-02 — drag_top_margin=0.3 applied by _ready()")
	node.free()


# H-03: Non-default drag_bottom_margin applied through _ready().
func test_h03_nondefa_drag_bottom_margin_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.drag_bottom_margin = 0.35
	node._ready()
	_assert_approx(node.drag_bottom_margin, 0.35,
		"H-03 — drag_bottom_margin=0.35 applied by _ready()")
	node.free()


# H-04: Non-default limit_left applied through _ready().
func test_h04_nondefa_limit_left_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_left = -400
	node._ready()
	_assert_int_eq(node.limit_left, -400,
		"H-04 — limit_left=-400 applied by _ready()")
	node.free()


# H-05: Non-default limit_top applied through _ready().
func test_h05_nondefa_limit_top_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_top = -300
	node._ready()
	_assert_int_eq(node.limit_top, -300,
		"H-05 — limit_top=-300 applied by _ready()")
	node.free()


# H-06: Non-default limit_bottom applied through _ready().
func test_h06_nondefa_limit_bottom_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.limit_bottom = 600
	node._ready()
	_assert_int_eq(node.limit_bottom, 600,
		"H-06 — limit_bottom=600 applied by _ready()")
	node.free()


# H-07: Non-default smoothing_speed (very small value near zero) applied by _ready().
# 0.001 is functionally near-zero but technically positive; the script must not
# clamp it to the default 5.0 or to 0.0.
func test_h07_nondefa_smoothing_speed_very_small_positive_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = 0.001
	node._ready()
	_assert_approx(node.position_smoothing_speed, 0.001,
		"H-07 — smoothing_speed=0.001 applied by _ready() (near-zero but positive)")
	node.free()


# ===========================================================================
# GROUP I: Negative smoothing_speed full mutation matrix (SPEC-40 / SPEC-39)
# ===========================================================================
# These tests push deeper into the negative smoothing_speed scenario.

# I-01: smoothing_speed = -INF stored in export var.
func test_i01_smoothing_speed_negative_inf_export_var_stored() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = -INF
	_assert_float_eq(node.smoothing_speed, -INF,
		"I-01 — smoothing_speed=-INF stored in export var pre-_ready()") # CHECKPOINT
	node.free()


# I-02: smoothing_speed = -100.0 — large negative.
func test_i02_smoothing_speed_large_negative_applied_by_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = -100.0
	node._ready()
	# _ready() must have assigned position_smoothing_speed = -100.0 (no guard).
	# Camera2D may internally clamp; we verify the round-trip consistency.
	_assert_approx(node.position_smoothing_speed, node.smoothing_speed,
		"I-02 — smoothing_speed=-100.0: position_smoothing_speed matches export var after _ready()") # CHECKPOINT
	node.free()


# ===========================================================================
# GROUP J: Structural / class integrity under adversarial instantiation
# ===========================================================================
# These tests verify that the class behaves correctly when properties are
# accessed in unusual orders, or when the node is freed before _ready() is called.

# J-01: Instantiate, free without calling _ready() — should not crash.
# Target flaw: a _ready() implementation that allocates resources in _init()
# that require cleanup would leak if _ready() is never called before free().
func test_j01_free_without_calling_ready_does_not_crash() -> void:
	var node: CameraFollow = CameraFollow.new()
	# Set a few properties to ensure the node is not in a trivial default state.
	node.smoothing_speed = 0.0
	node.limit_right = 500
	# Free without _ready() — the test passes if no crash occurs.
	node.free()
	_pass("J-01 — CameraFollow can be freed without calling _ready() (no crash)")


# J-02: Export vars readable immediately after instantiation, before _ready().
# Verifies that the @export defaults are available synchronously after .new().
func test_j02_all_export_vars_readable_pre_ready() -> void:
	var node: CameraFollow = CameraFollow.new()
	# This test will fail if any @export var is not initialized until _ready() runs.
	var _se: bool = node.smoothing_enabled
	var _ss: float = node.smoothing_speed
	var _dh: bool = node.drag_horizontal
	var _dv: bool = node.drag_vertical
	var _dlm: float = node.drag_left_margin
	var _drm: float = node.drag_right_margin
	var _dtm: float = node.drag_top_margin
	var _dbm: float = node.drag_bottom_margin
	var _ll: int = node.limit_left
	var _lr: int = node.limit_right
	var _lt: int = node.limit_top
	var _lb: int = node.limit_bottom
	# If we reach this point, all twelve vars were accessible without crash.
	_pass("J-02 — all twelve @export vars readable pre-_ready() without crash")
	node.free()


# J-03: Two separate instances modified independently do not share state.
# Mutation testing: confirms there is no class-level static state that would
# cause instance A's property changes to leak into instance B.
func test_j03_two_instances_do_not_share_export_var_state() -> void:
	var node_a: CameraFollow = CameraFollow.new()
	var node_b: CameraFollow = CameraFollow.new()
	node_a.smoothing_speed = 1.0
	node_b.smoothing_speed = 9.0
	node_a._ready()
	node_b._ready()
	_assert_approx(node_a.position_smoothing_speed, 1.0,
		"J-03a — instance A: smoothing_speed=1.0 applied independently")
	_assert_approx(node_b.position_smoothing_speed, 9.0,
		"J-03b — instance B: smoothing_speed=9.0 applied independently (no state leakage from A)")
	node_a.free()
	node_b.free()


# J-04: Three _ready() calls — property values match current export vars throughout.
# Stresses the idempotency guarantee beyond two calls.
func test_j04_triple_ready_call_idempotent() -> void:
	var node: CameraFollow = CameraFollow.new()
	node.smoothing_speed = 3.0
	node._ready()
	node._ready()
	node._ready()
	_assert_approx(node.position_smoothing_speed, 3.0,
		"J-04 — three consecutive _ready() calls: position_smoothing_speed stable at 3.0")
	node.free()


# ===========================================================================
# PUBLIC ENTRY POINT
# ===========================================================================

func run_all() -> int:
	print("--- test_camera_follow_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	# GROUP A: smoothing_speed edge-case values
	test_a01_smoothing_speed_zero_applied_by_ready()
	test_a02_smoothing_speed_zero_export_var_readable()
	test_a03_smoothing_speed_negative_export_var_stored()
	test_a04_smoothing_speed_negative_assigned_by_ready()
	test_a05_smoothing_speed_inf_export_var_stored()
	test_a06_smoothing_speed_inf_assigned_by_ready()
	test_a07_smoothing_speed_very_large_finite_applied_by_ready()

	# GROUP B: smoothing_enabled = false path
	test_b01_smoothing_disabled_path_sets_property_false()
	test_b02_smoothing_disabled_idempotent_double_ready()
	test_b03_second_ready_with_false_overrides_first_ready_true()
	test_b04_second_ready_with_true_overrides_first_ready_false()

	# GROUP C: drag_horizontal and drag_vertical toggles
	test_c01_drag_horizontal_false_applied_by_ready()
	test_c02_drag_vertical_true_applied_by_ready()
	test_c03_both_drag_bools_nondefa_applied_by_ready()

	# GROUP D: drag margin edge-case values
	test_d01_all_drag_margins_zero_applied_by_ready()
	test_d02_all_drag_margins_one_applied_by_ready()
	test_d03_drag_left_margin_exceeds_one_export_var_preserves_value()
	test_d04_drag_right_margin_negative_export_var_preserves_value()
	test_d05_all_margins_out_of_range_export_vars_preserve_values()

	# GROUP E: limit boundary and degenerate cases
	test_e01_all_limits_same_value_degenerate_box_applied_by_ready()
	test_e02_limit_left_greater_than_limit_right_applied_by_ready()
	test_e03_limit_bottom_less_than_limit_top_applied_by_ready()
	test_e04_limit_left_equals_limit_right_zero_width_applied_by_ready()
	test_e05_limit_top_equals_limit_bottom_zero_height_applied_by_ready()
	test_e06_all_limits_int32_max_export_var_preserved()
	test_e07_all_limits_int32_min_export_var_preserved()
	test_e08_int32_max_limits_applied_by_ready()
	test_e09_int32_min_limits_applied_by_ready()
	test_e10_minimal_nonzero_limit_box_applied_by_ready()
	test_e11_all_limits_zero_origin_point()

	# GROUP F: Idempotency and override — _ready() called multiple times
	test_f01_double_ready_all_defaults_all_twelve_properties_stable()
	test_f02_change_smoothing_speed_between_ready_calls_second_overrides()
	test_f03_change_limit_right_between_ready_calls_second_overrides()
	test_f04_change_all_twelve_vars_between_ready_calls_all_override()

	# GROUP G: Full mutability sweep for all twelve @export vars
	test_g01_drag_horizontal_is_mutable()
	test_g02_drag_vertical_is_mutable()
	test_g03_drag_left_margin_is_mutable()
	test_g04_drag_right_margin_is_mutable()
	test_g05_drag_top_margin_is_mutable()
	test_g06_drag_bottom_margin_is_mutable()
	test_g07_limit_left_is_mutable()
	test_g08_limit_top_is_mutable()
	test_g09_limit_bottom_is_mutable()

	# GROUP H: _ready() applies non-default values for remaining parameters
	test_h01_nondefa_drag_right_margin_applied_by_ready()
	test_h02_nondefa_drag_top_margin_applied_by_ready()
	test_h03_nondefa_drag_bottom_margin_applied_by_ready()
	test_h04_nondefa_limit_left_applied_by_ready()
	test_h05_nondefa_limit_top_applied_by_ready()
	test_h06_nondefa_limit_bottom_applied_by_ready()
	test_h07_nondefa_smoothing_speed_very_small_positive_applied_by_ready()

	# GROUP I: Negative smoothing_speed mutation matrix
	test_i01_smoothing_speed_negative_inf_export_var_stored()
	test_i02_smoothing_speed_large_negative_applied_by_ready()

	# GROUP J: Structural / class integrity
	test_j01_free_without_calling_ready_does_not_crash()
	test_j02_all_export_vars_readable_pre_ready()
	test_j03_two_instances_do_not_share_export_var_state()
	test_j04_triple_ready_call_idempotent()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count
