# test_wall_cling_simulation_adversarial.gd
#
# Adversarial extension of the wall cling simulation test suite.
# Generated by Test Breaker Agent — 2026-03-01.
#
# This file targets boundary conditions, mutation scenarios, edge-case
# configurations, and spec gaps NOT covered by the 66-test primary suite in
# tests/test_wall_cling_simulation.gd. Every test includes a comment explaining
# the specific vulnerability it probes.
#
# This file does not import or depend on test_wall_cling_simulation.gd.
#
# Spec coverage targeted:
#   SPEC-25 — State immutability for all 6 MovementState fields (velocity.x, velocity.y,
#              is_on_floor, coyote_timer, jump_consumed, is_wall_clinging, cling_timer)
#              under adversarial call patterns
#   SPEC-26 — Config boundary values: cling_gravity_scale<0.0, cling_gravity_scale>1.0,
#              max_cling_time very large (never expires), wall_jump_height<0 (sqrt guard),
#              wall_jump_horizontal_speed=0.0 (vertical-only wall jump)
#   SPEC-27 — Config mutation mid-sim: cling_gravity_scale and max_cling_time changed
#              between consecutive frames
#   SPEC-28 — Diagonal wall_normal_x (±0.707): pressing_toward_wall product < 0.0
#   SPEC-28 — wall_normal_x = NaN: must not propagate NaN into output
#   SPEC-28 — wall_normal_x = +Inf / -Inf: must not propagate Inf into output
#   SPEC-29 — is_on_floor=true AND is_on_wall=true simultaneously (floor priority, SPEC-34)
#   SPEC-29 — cling_timer prior value vastly exceeds max_cling_time (already expired on entry)
#   SPEC-30 — Rapid alternating wall contact: cling_timer resets correctly across transitions
#   SPEC-32 — jump_just_pressed AND is_on_wall on first contact frame (prior.is_wall_clinging=false)
#             does NOT fire wall jump — only cling entry occurs
#   SPEC-33 — wall_jump_horizontal_speed=0.0 produces correct vertical-only wall jump
#   SPEC-33 — wall_jump_height negative: sqrt guard must not produce NaN
#   SPEC-36 — Frame-rate independence: cling_timer very large delta
#
# Checkpoint log (see CHECKPOINTS.md for full text):
#   [M1-003] Test Breaker — TB-WC-001: diagonal wall_normal_x pressing_toward_wall product
#   [M1-003] Test Breaker — TB-WC-002: wall_normal_x NaN propagation
#   [M1-003] Test Breaker — TB-WC-003: cling_gravity_scale negative behavior
#   [M1-003] Test Breaker — TB-WC-004: max_cling_time very large (never expires)
#   [M1-003] Test Breaker — TB-WC-005: is_on_floor AND is_on_wall simultaneously
#   [M1-003] Test Breaker — TB-WC-006: jump_just_pressed on first contact frame (no wall jump)
#   [M1-003] Test Breaker — TB-WC-007: rapid alternating wall contact timer reset
#   [M1-003] Test Breaker — TB-WC-008: wall_jump_horizontal_speed=0.0
#   [M1-003] Test Breaker — TB-WC-009: wall_jump_height negative NaN guard
#   [M1-003] Test Breaker — TB-WC-010: cling_timer prior value vastly exceeds max_cling_time
#   [M1-003] Test Breaker — TB-WC-011: state immutability — all 6 MovementState fields
#   [M1-003] Test Breaker — TB-WC-012: config mutation between frames

class_name WallClingSimulationAdversarialTests
extends Object

const EPSILON: float = 1e-4

var _pass_count: int = 0
var _fail_count: int = 0


# ---------------------------------------------------------------------------
# Helpers (self-contained — does not rely on other test file helpers)
# ---------------------------------------------------------------------------

func _approx_eq(a: float, b: float) -> bool:
	return abs(a - b) < EPSILON


func _pass(test_name: String) -> void:
	_pass_count += 1
	print("  PASS: " + test_name)


func _fail(test_name: String, message: String) -> void:
	_fail_count += 1
	print("  FAIL: " + test_name + " — " + message)


func _assert_true(condition: bool, test_name: String) -> void:
	if condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected true, got false")


func _assert_false(condition: bool, test_name: String) -> void:
	if not condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected false, got true")


func _assert_approx(a: float, b: float, test_name: String) -> void:
	if _approx_eq(a, b):
		_pass(test_name)
	else:
		_fail(test_name, "got " + str(a) + " expected " + str(b) + " (delta " + str(abs(a - b)) + ")")


func _make_state_with(vx: float, vy: float, on_floor: bool) -> MovementSimulation.MovementState:
	var s: MovementSimulation.MovementState = MovementSimulation.MovementState.new()
	s.velocity = Vector2(vx, vy)
	s.is_on_floor = on_floor
	return s


# ===========================================================================
# GROUP 1 — Diagonal wall_normal_x (±0.707, not ±1.0)
#
# Vulnerability: The spec only shows examples with wall_normal_x = ±1.0.
# An implementation that hardcodes ±1.0 comparisons instead of evaluating
# the formula (safe_axis * wall_normal_x) < 0.0 will fail these tests.
# ===========================================================================

# TB-WC-001a: wall_normal_x=+0.707 (diagonal left wall), input_axis=-1.0
# Product = -1.0 * 0.707 = -0.707 < 0.0 → pressing_toward_wall=true → cling eligible
# CHECKPOINT: Assumes SPEC-28 formula is evaluated with arbitrary float wall_normal_x,
# not just the ±1.0 axis-aligned normals shown in spec examples.
func test_diagonal_wall_normal_positive_cling_eligible() -> void:
	# Vulnerability: hardcoded ±1.0 wall normal check would break this.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 0.0
	# is_on_wall=true, wall_normal_x=0.707 (wall to the left, normal points right-ish)
	# input_axis=-1.0 (pressing left into that wall)
	# product = -1.0 * 0.707 = -0.707 < 0.0 → pressing toward wall
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 0.707, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-001a — diagonal wall_normal_x=0.707, input_axis=-1.0: product=-0.707<0 → cling")


# TB-WC-001b: wall_normal_x=-0.707 (diagonal right wall), input_axis=1.0
# Product = 1.0 * -0.707 = -0.707 < 0.0 → pressing_toward_wall=true → cling eligible
func test_diagonal_wall_normal_negative_cling_eligible() -> void:
	# Vulnerability: same as TB-WC-001a — hardcoded ±1.0 check would fail.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 0.0
	# wall_normal_x=-0.707 (wall to the right, normal points left-ish)
	# input_axis=1.0 (pressing right into that wall)
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, true, -0.707, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-001b — diagonal wall_normal_x=-0.707, input_axis=1.0: product=-0.707<0 → cling")


# TB-WC-001c: Diagonal normal, pressing away — product positive → no cling
# wall_normal_x=0.707, input_axis=1.0 → product=0.707 > 0.0 → no cling
func test_diagonal_wall_normal_pressing_away_no_cling() -> void:
	# Vulnerability: an implementation that only checks input_axis direction without
	# multiplying by wall_normal_x would incorrectly grant cling here.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, true, 0.707, false, 0.016)
	_assert_false(result.is_wall_clinging,
		"TB-WC-001c — diagonal wall_normal_x=0.707, input_axis=1.0: product=0.707>0 → no cling")


# TB-WC-001d: Diagonal wall jump — vx = wall_normal_x * wall_jump_horizontal_speed
# wall_normal_x=0.707, wall_jump_horizontal_speed=180.0 → vx=0.707*180=127.26
# CHECKPOINT: Assumes diagonal wall jump horizontal component scales by the float normal value.
func test_diagonal_wall_jump_horizontal_component() -> void:
	# Vulnerability: an implementation that snaps wall_normal_x to ±1.0 for jump
	# would produce ±180.0 instead of the correct scaled value.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, 0.707, false, 0.016)
	var expected_vx: float = 0.707 * 180.0  # = 127.26
	_assert_approx(result.velocity.x, expected_vx,
		"TB-WC-001d — diagonal wall jump: vx = 0.707 * 180.0 = 127.26")


# ===========================================================================
# GROUP 2 — wall_normal_x = NaN and Inf
#
# Vulnerability: An implementation that does not sanitize wall_normal_x will
# propagate NaN or Inf into pressing_toward_wall evaluation, then into
# result.velocity.x on wall jump, producing NaN/Inf output.
# The spec does not explicitly describe NaN/Inf wall normals; the conservative
# assumption is that NaN/Inf must not corrupt simulation output.
# ===========================================================================

# TB-WC-002a: wall_normal_x = NaN, is_on_wall=true → must not produce NaN velocity
# CHECKPOINT: The spec sanitizes input_axis for NaN but does not explicitly state
# wall_normal_x is sanitized. Conservative assumption: NaN wall_normal_x must not
# produce NaN output. The product (safe_axis * NaN) = NaN, which is not < 0.0,
# so cling must be blocked (NaN < 0.0 is false in IEEE-754).
func test_nan_wall_normal_x_no_nan_output() -> void:
	# Vulnerability: if pressing_toward_wall = (axis * NaN) < 0.0 evaluates as false
	# (correct), cling is blocked. But if any downstream code uses wall_normal_x in
	# a formula without checking clinging state, NaN can leak into velocity.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, NAN, false, 0.016)
	_assert_true(not is_nan(result.velocity.x),
		"TB-WC-002a — wall_normal_x=NaN: velocity.x must not be NaN")
	_assert_true(not is_nan(result.velocity.y),
		"TB-WC-002a — wall_normal_x=NaN: velocity.y must not be NaN")
	# NaN * anything = NaN which is not < 0.0 → cling must be blocked
	_assert_false(result.is_wall_clinging,
		"TB-WC-002a — wall_normal_x=NaN: (axis*NaN)<0.0 is false → cling blocked")


# TB-WC-002b: wall_normal_x = +Inf → product = axis * Inf = Inf or 0.0 (if axis=0)
# With axis=-1.0: product = -1.0 * Inf = -Inf < 0.0 → pressing_toward_wall could
# evaluate to true. If cling fires and then wall jump fires with vx=Inf*speed, output
# would be Inf. Must assert finite output.
func test_inf_wall_normal_x_no_inf_output() -> void:
	# Vulnerability: if is_on_wall=true and input_axis=-1.0 and wall_normal_x=+Inf,
	# then (-1.0 * Inf = -Inf) < 0.0 is TRUE → cling may fire. If subsequent wall jump
	# fires using this Inf normal, vx = Inf * speed = Inf. Output must be finite.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, INF, false, 0.016)
	_assert_true(is_finite(result.velocity.x),
		"TB-WC-002b — wall_normal_x=+Inf wall jump: velocity.x must be finite (not Inf)")
	_assert_true(is_finite(result.velocity.y),
		"TB-WC-002b — wall_normal_x=+Inf wall jump: velocity.y must be finite (not Inf)")


# TB-WC-002c: wall_normal_x = -Inf
func test_neg_inf_wall_normal_x_no_inf_output() -> void:
	# Vulnerability: -Inf wall normal in wall jump → vx = -Inf * 180 = -Inf.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -INF, false, 0.016)
	_assert_true(is_finite(result.velocity.x),
		"TB-WC-002c — wall_normal_x=-Inf wall jump: velocity.x must be finite (not -Inf)")
	_assert_true(is_finite(result.velocity.y),
		"TB-WC-002c — wall_normal_x=-Inf wall jump: velocity.y must be finite")


# ===========================================================================
# GROUP 3 — cling_gravity_scale negative or >1.0
#
# Vulnerability: The spec lists cling_gravity_scale=0.0 and cling_gravity_scale=1.0
# as boundary values but does not test negative (anti-gravity cling) or values
# above 1.0 (supergravity cling). An implementation that does not range-check the
# config will apply anti-gravity or > normal gravity while clinging.
# ===========================================================================

# TB-WC-003a: cling_gravity_scale = -0.1 (anti-gravity cling)
# When clinging: gravity contribution = 980 * (-0.1) * 0.016 = -1.568
# Starting vy=0: result.vy = 0.0 + 980.0 * (-0.1) * 0.016 = -1.568 (upward drift)
# CHECKPOINT: Spec says negative cling_gravity_scale is undefined behavior (parallels
# negative jump_height). Conservative assumption: must not produce NaN/Inf. Result
# may be gameplay-incorrect but must be numerically finite. Tests only assert finiteness.
func test_negative_cling_gravity_scale_no_nan_output() -> void:
	# Vulnerability: an implementation that guards cling_gravity_scale against zero
	# but not negative might allow anti-gravity to produce unexpected gameplay states.
	# Finite output is the only hard requirement here.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.cling_gravity_scale = -0.1
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(is_finite(result.velocity.y),
		"TB-WC-003a — cling_gravity_scale=-0.1: velocity.y must be finite (not NaN/Inf)")
	_assert_true(not is_nan(result.velocity.y),
		"TB-WC-003a — cling_gravity_scale=-0.1: velocity.y must not be NaN")


# TB-WC-003b: cling_gravity_scale = 2.0 (double-gravity cling — supergravity)
# vy = 0.0 + 980.0 * 2.0 * 0.016 = 31.36 (double normal gravity while clinging)
# CHECKPOINT: Spec does not define behavior for scale>1.0. This is a valid designer
# misconfiguration. The conservative assumption is that the formula still applies
# literally: gravity * scale * delta. Tests assert the exact formula result.
func test_supergravity_cling_gravity_scale() -> void:
	# Vulnerability: an implementation that clamps cling_gravity_scale to [0,1]
	# silently without the spec requiring it would produce a different value than
	# the formula predicts. This test pins the literal formula behavior.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.cling_gravity_scale = 2.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-003b setup — cling active for supergravity test")
	# cling_gravity_scale=2.0: vy = 0.0 + 980.0 * 2.0 * 0.016 = 31.36
	_assert_approx(result.velocity.y, 31.36,
		"TB-WC-003b — cling_gravity_scale=2.0: vy = 980*2.0*0.016 = 31.36 (not clamped to 1x)")


# TB-WC-003c: cling_gravity_scale = 0.0001 (very small, near-hover but nonzero)
# vy = 0.0 + 980.0 * 0.0001 * 0.016 = 0.001568
# Tests that the formula is applied exactly at very small scales (no premature zero-clamp).
func test_near_zero_cling_gravity_scale_applied_precisely() -> void:
	# Vulnerability: an implementation that uses a threshold comparison
	# (e.g., "if cling_gravity_scale < 0.01: skip gravity") would produce 0.0
	# instead of 0.001568.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.cling_gravity_scale = 0.0001
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-003c setup — cling active for near-zero scale test")
	var expected_vy: float = 980.0 * 0.0001 * 0.016  # = 0.001568
	_assert_approx(result.velocity.y, expected_vy,
		"TB-WC-003c — cling_gravity_scale=0.0001: vy = 980*0.0001*0.016 = 0.001568 exactly")


# ===========================================================================
# GROUP 4 — max_cling_time very large (never expires)
#
# Vulnerability: A very large max_cling_time should allow cling to accumulate
# without ever hitting the timer cap. An implementation that uses a short fixed
# cap or overflows the float comparison would incorrectly block cling.
# ===========================================================================

# TB-WC-004a: max_cling_time=1e10 (effectively infinite), cling_timer=0.0
# After many frames, cling_timer should accumulate without hitting the cap.
# Two consecutive frames: timer should be 0.016 then 0.032.
# CHECKPOINT: Assumes float comparison 0.016 < 1e10 works correctly; it should in IEEE-754.
func test_very_large_max_cling_time_cling_never_expires() -> void:
	# Vulnerability: if the implementation compares using a hardcoded internal cap
	# or truncates max_cling_time, cling would incorrectly expire.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_cling_time = 1.0e10
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 0.0

	# Frame 1
	var state1: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state1.is_wall_clinging,
		"TB-WC-004a frame1 — max_cling_time=1e10: cling active on frame 1 (timer=0.016)")
	_assert_approx(state1.cling_timer, 0.016,
		"TB-WC-004a frame1 — cling_timer = 0.016 after first frame")

	# Frame 2 — build a second prior from frame 1 output
	var prior2: MovementSimulation.MovementState = _make_state_with(state1.velocity.x, state1.velocity.y, false)
	prior2.jump_consumed = false
	prior2.cling_timer = state1.cling_timer
	var state2: MovementSimulation.MovementState = sim.simulate(prior2, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state2.is_wall_clinging,
		"TB-WC-004a frame2 — max_cling_time=1e10: cling still active on frame 2")
	_assert_approx(state2.cling_timer, 0.032,
		"TB-WC-004a frame2 — cling_timer = 0.032 after second frame")


# TB-WC-004b: max_cling_time very large, cling_timer starts at 999.0
# 999.0 < 1e10 → still eligible
func test_very_large_max_cling_time_large_prior_timer_still_eligible() -> void:
	# Vulnerability: if a float precision issue causes 999.0 < 1e10 to evaluate
	# incorrectly, or if there is an unexpected hardcoded internal limit.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_cling_time = 1.0e10
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 999.0  # large but still well below 1e10
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-004b — max_cling_time=1e10, prior timer=999.0: still eligible (999<1e10)")
	_assert_approx(result.cling_timer, 999.016,
		"TB-WC-004b — cling_timer = 999.0 + 0.016 = 999.016")


# ===========================================================================
# GROUP 5 — Simultaneous is_on_floor=true AND is_on_wall=true (corner case)
#
# SPEC-34: when floor and wall contact are simultaneous, floor takes priority.
# is_on_floor=true blocks cling eligibility (SPEC-29 condition 2).
# Vulnerability: an implementation that checks is_on_wall first before is_on_floor
# could incorrectly enable cling on a grounded frame.
# ===========================================================================

# TB-WC-005a: is_on_floor=true, is_on_wall=true, pressing toward wall → floor wins: no cling
# CHECKPOINT: This is documented as SPEC-34 priority. The is_on_floor condition check
# must appear before or combined with the is_on_wall check in the eligibility gate.
func test_floor_and_wall_simultaneously_floor_takes_priority() -> void:
	# Vulnerability: if cling eligibility checks is_on_wall first and applies cling,
	# then coyote timer would interact incorrectly, and the player would
	# incorrectly be flagged as clinging while grounded.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)  # on floor
	prior.jump_consumed = false
	prior.cling_timer = 0.0
	# is_on_wall=true, pressing toward wall, but is_on_floor=true → not eligible
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(result.is_wall_clinging,
		"TB-WC-005a — floor+wall simultaneously: floor takes priority → no cling (SPEC-34)")
	_assert_approx(result.cling_timer, 0.0,
		"TB-WC-005a — floor+wall simultaneously: cling_timer resets to 0.0 when not eligible")


# TB-WC-005b: On floor + wall → regular jump still fires normally (not wall jump)
# prior.is_wall_clinging=true (was clinging), now on floor, jump_just_pressed=true
# Regular jump must fire because floor takes precedence.
func test_floor_and_wall_simultaneously_regular_jump_fires() -> void:
	# Vulnerability: an implementation that evaluates wall_jump_eligible before
	# checking the floor path could fire wall jump when grounded.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)  # on floor
	prior.is_wall_clinging = true  # was clinging, now touching floor
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	var regular_jump_vy: float = -sqrt(2.0 * 980.0 * 120.0) + 980.0 * 0.016
	var wall_jump_vy: float = -sqrt(2.0 * 980.0 * 100.0) + 980.0 * 0.016
	_assert_approx(result.velocity.y, regular_jump_vy,
		"TB-WC-005b — floor+wall: regular jump fires (jump_height=120), not wall jump (height=100)")
	# The two heights differ, so if wall jump fired the assertion above fails distinctly.
	_assert_true(abs(result.velocity.y - wall_jump_vy) > EPSILON,
		"TB-WC-005b — floor+wall: result.vy differs from wall jump vy (floor took priority)")


# TB-WC-005c: On floor + wall: coyote timer carries the floor reset normally
# Even though is_on_wall=true, the coyote timer resets to coyote_time because floor=true.
func test_floor_and_wall_simultaneously_coyote_timer_resets() -> void:
	# Vulnerability: if wall cling logic intercepts the coyote timer update,
	# it could incorrectly set it to a value other than coyote_time.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, true)  # on floor
	prior.coyote_timer = 0.0
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_approx(result.coyote_timer, sim.coyote_time,
		"TB-WC-005c — floor+wall: coyote_timer resets to coyote_time=0.1 (floor logic unaffected)")


# ===========================================================================
# GROUP 6 — jump_just_pressed on first contact frame (prior.is_wall_clinging=false)
#
# SPEC-32: wall jump reads prior_state.is_wall_clinging, not current frame eligibility.
# First contact frame: prior.is_wall_clinging=false → wall jump must NOT fire.
# Only cling entry should occur on this frame.
# Vulnerability: an implementation that checks result.is_wall_clinging (current frame)
# instead of prior_state.is_wall_clinging would fire wall jump on the very first frame
# of contact, bypassing the "at least one confirmed cling frame" requirement.
# ===========================================================================

# TB-WC-006a: First contact frame — jump_just_pressed=true, prior.is_wall_clinging=false
# Wall jump must not fire. result.is_wall_clinging should be true (cling entered).
# result.velocity.y should be cling_gravity (not wall jump impulse).
func test_first_contact_frame_no_wall_jump_only_cling_entry() -> void:
	# Vulnerability: checking result.is_wall_clinging for wall jump eligibility
	# instead of prior_state.is_wall_clinging would cause wall jump on first frame.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = false  # first contact — no cling yet
	prior.jump_consumed = false
	# All cling conditions met this frame (axis=-1, normal=1.0, on wall, not on floor,
	# not consumed, timer=0.0 < max), AND jump_just_pressed=true.
	# Wall jump must NOT fire (prior.is_wall_clinging=false fails condition).
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, true, true, 1.0, false, 0.016)
	var wall_jump_vy: float = -sqrt(2.0 * 980.0 * 100.0) + 980.0 * 0.016
	# vy must NOT be the wall jump impulse
	_assert_true(abs(result.velocity.y - wall_jump_vy) > EPSILON,
		"TB-WC-006a — first contact, jump_just_pressed=true: wall jump must NOT fire")
	# jump_consumed must NOT be set by a wall jump
	_assert_false(result.jump_consumed,
		"TB-WC-006a — first contact, jump_just_pressed=true: jump_consumed stays false (no wall jump)")
	# Cling should now be active (first frame established)
	_assert_true(result.is_wall_clinging,
		"TB-WC-006a — first contact: cling is established on this frame (result.is_wall_clinging=true)")


# TB-WC-006b: Second frame after first contact — prior.is_wall_clinging=true
# Now jump_just_pressed=true → wall jump fires on frame 2.
# This verifies the two-frame pattern: frame1=cling entry, frame2=wall jump.
func test_second_contact_frame_wall_jump_fires() -> void:
	# Vulnerability: same as TB-WC-006a, but also tests that wall jump fires on the
	# correct (second) frame. An implementation that delays wall jump by an extra
	# frame would fail this paired with TB-WC-006a.
	var sim: MovementSimulation = MovementSimulation.new()
	# Prior state represents the result of frame 1 (cling established)
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true  # established on frame 1
	prior.cling_timer = 0.016  # one frame accumulated
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, 1.0, false, 0.016)
	var expected_vy: float = -sqrt(2.0 * 980.0 * 100.0) + 980.0 * 0.016
	_assert_approx(result.velocity.y, expected_vy,
		"TB-WC-006b — second frame (prior.is_wall_clinging=true): wall jump fires correctly")
	_assert_true(result.jump_consumed,
		"TB-WC-006b — second frame: jump_consumed=true after wall jump")
	_assert_false(result.is_wall_clinging,
		"TB-WC-006b — second frame: is_wall_clinging=false after wall jump")


# ===========================================================================
# GROUP 7 — Rapid alternating wall contact: cling_timer reset behavior
#
# Vulnerability: If the implementation accumulates cling_timer without resetting
# when the player briefly leaves the wall and returns, the timer could carry
# forward stale accumulated time and incorrectly expire cling sooner.
# SPEC-30: timer resets to 0.0 immediately when not eligible. On re-contact,
# it should start fresh from 0.0 + delta.
# ===========================================================================

# TB-WC-007a: Cling, leave wall, return to wall — timer starts fresh from 0.0
# Frame 1: clinging, timer accumulates to 0.8
# Frame 2: not on wall (leaves wall), timer resets to 0.0
# Frame 3: returns to wall, timer should start fresh from 0.016 (not 0.816)
func test_cling_leave_wall_return_timer_resets_fresh() -> void:
	# Vulnerability: an implementation that accumulates the timer without checking
	# the reset condition would carry 0.8 forward and produce 0.816 on re-contact.
	var sim: MovementSimulation = MovementSimulation.new()

	# Frame 1: clinging with accumulated timer 0.8
	var prior1: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior1.jump_consumed = false
	prior1.cling_timer = 0.8
	var state1: MovementSimulation.MovementState = sim.simulate(prior1, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state1.is_wall_clinging,
		"TB-WC-007a frame1 — clinging with prior timer=0.8 → still eligible")
	_assert_approx(state1.cling_timer, 0.816,
		"TB-WC-007a frame1 — timer = 0.8 + 0.016 = 0.816")

	# Frame 2: not on wall (is_on_wall=false) → timer resets to 0.0
	var prior2: MovementSimulation.MovementState = _make_state_with(state1.velocity.x, state1.velocity.y, false)
	prior2.is_wall_clinging = state1.is_wall_clinging
	prior2.cling_timer = state1.cling_timer  # = 0.816
	prior2.jump_consumed = false
	var state2: MovementSimulation.MovementState = sim.simulate(prior2, -1.0, false, false, false, 1.0, false, 0.016)
	_assert_false(state2.is_wall_clinging,
		"TB-WC-007a frame2 — not on wall → cling exits")
	_assert_approx(state2.cling_timer, 0.0,
		"TB-WC-007a frame2 — timer resets to 0.0 when not on wall")

	# Frame 3: returns to wall → timer must start fresh from 0.0 + delta = 0.016
	var prior3: MovementSimulation.MovementState = _make_state_with(state2.velocity.x, state2.velocity.y, false)
	prior3.is_wall_clinging = state2.is_wall_clinging  # = false
	prior3.cling_timer = state2.cling_timer  # = 0.0 (reset)
	prior3.jump_consumed = false
	var state3: MovementSimulation.MovementState = sim.simulate(prior3, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state3.is_wall_clinging,
		"TB-WC-007a frame3 — returned to wall: cling re-enters")
	_assert_approx(state3.cling_timer, 0.016,
		"TB-WC-007a frame3 — timer starts fresh from 0.0: 0.0 + 0.016 = 0.016 (not 0.832)")


# TB-WC-007b: Cling expires, player leaves wall, returns — timer starts fresh
# This tests that an expired timer (1.5) is not carried as stale state.
# If the implementation checks timer only at cling entry (not reset on exit),
# returning to wall with a stale timer=1.5 would immediately block cling.
func test_cling_expires_leaves_returns_timer_resets() -> void:
	# Vulnerability: stale timer not cleared on non-cling frames would mean
	# returning to wall after expiry immediately fails the timer check.
	var sim: MovementSimulation = MovementSimulation.new()

	# Simulate: prior had timer=1.5 (expired), left wall, now timer should be 0.0
	var prior_off_wall: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior_off_wall.cling_timer = 1.5  # was expired
	prior_off_wall.is_wall_clinging = false  # expired and left wall
	prior_off_wall.jump_consumed = false
	# Frame off wall: timer resets to 0.0
	var state_off: MovementSimulation.MovementState = sim.simulate(prior_off_wall, 0.0, false, false, false, 1.0, false, 0.016)
	_assert_approx(state_off.cling_timer, 0.0,
		"TB-WC-007b off-wall — expired timer 1.5 resets to 0.0 when not on wall")

	# Return to wall: timer=0.0 < max_cling_time=1.5 → eligible again
	var prior_return: MovementSimulation.MovementState = _make_state_with(state_off.velocity.x, state_off.velocity.y, false)
	prior_return.cling_timer = state_off.cling_timer  # = 0.0
	prior_return.is_wall_clinging = false
	prior_return.jump_consumed = false
	var state_return: MovementSimulation.MovementState = sim.simulate(prior_return, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state_return.is_wall_clinging,
		"TB-WC-007b return — after expiry+leave+return: fresh timer=0.0 < 1.5 → cling re-enters")
	_assert_approx(state_return.cling_timer, 0.016,
		"TB-WC-007b return — timer = 0.0 + 0.016 = 0.016 (fresh, not stale 1.5)")


# ===========================================================================
# GROUP 8 — wall_jump_horizontal_speed = 0.0 (vertical-only wall jump)
#
# Vulnerability: An implementation that guards against zero speed (e.g., skips
# horizontal assignment or adds a minimum) would produce non-zero vx.
# SPEC-33: vx = wall_normal_x * wall_jump_horizontal_speed, so 0 speed → vx=0.0.
# ===========================================================================

# TB-WC-008a: wall_jump_horizontal_speed=0.0 → vx=0.0 on wall jump
# CHECKPOINT: Spec does not restrict wall_jump_horizontal_speed to nonzero values.
# Zero is a valid configuration for a straight-up wall jump.
func test_zero_wall_jump_horizontal_speed_vx_zero() -> void:
	# Vulnerability: if the implementation uses horizontal speed as a divisor
	# anywhere, or has a "minimum speed" guard, this would produce non-zero vx.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.wall_jump_horizontal_speed = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	_assert_approx(result.velocity.x, 0.0,
		"TB-WC-008a — wall_jump_horizontal_speed=0.0: vx = -1.0 * 0.0 = 0.0 (vertical-only jump)")
	# Vertical component must still apply correctly
	var expected_vy: float = -sqrt(2.0 * 980.0 * 100.0) + 980.0 * 0.016
	_assert_approx(result.velocity.y, expected_vy,
		"TB-WC-008a — wall_jump_horizontal_speed=0.0: vy still applies full vertical impulse")
	_assert_true(result.jump_consumed,
		"TB-WC-008a — wall_jump_horizontal_speed=0.0: jump_consumed=true (wall jump fired)")


# TB-WC-008b: wall_jump_horizontal_speed=0.0 — prior vx=100.0 is cleared (step 7 skipped)
# Step 7 (horizontal formula) must be skipped on wall jump frame.
# With speed=0.0 and prior vx=100.0, if step 7 runs, result.vx would be ~80.8 (friction).
# If step 7 is correctly skipped and vx = wall_normal_x * 0.0 = 0.0, result.vx = 0.0.
func test_zero_wall_jump_speed_prior_vx_cleared_by_wall_jump() -> void:
	# Vulnerability: if step 7 is not skipped on wall jump frame, prior vx=100.0
	# would bleed into result.vx even with zero jump speed.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.wall_jump_horizontal_speed = 0.0
	var prior: MovementSimulation.MovementState = _make_state_with(100.0, 0.0, false)  # prior vx=100
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	# Wall jump fires → step 7 skipped → vx = 0.0 (not ~80.8 from friction formula)
	_assert_approx(result.velocity.x, 0.0,
		"TB-WC-008b — zero speed wall jump: step 7 skipped, prior vx=100 cleared, result.vx=0.0")


# ===========================================================================
# GROUP 9 — wall_jump_height negative (sqrt guard)
#
# Vulnerability: -sqrt(2 * gravity * negative_height) = -sqrt(negative) = NaN in GDScript.
# The spec guards jump_height with "if jump_height > 0.0 else 0.0" (SPEC-16 note).
# The wall_jump_height must be guarded analogously. Without the guard, a negative
# wall_jump_height produces NaN velocity.
# ===========================================================================

# TB-WC-009a: wall_jump_height = -50.0 → sqrt guard must fire → vy must not be NaN
# CHECKPOINT: SPEC-26 states negative wall_jump_height is undefined behavior.
# The conservative assumption is that the implementation applies the same sqrt guard
# used for jump_height (see AC-18.5 in movement_simulation.gd: safe_jump_height=0 if negative).
# If the guard is missing for wall_jump_height, -sqrt(-98000) = NaN.
func test_negative_wall_jump_height_no_nan() -> void:
	# Vulnerability: missing sqrt guard on wall_jump_height. If jump_height has
	# the guard but wall_jump_height does not, this test catches the asymmetry.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.wall_jump_height = -50.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	_assert_true(not is_nan(result.velocity.y),
		"TB-WC-009a — wall_jump_height=-50.0: velocity.y must not be NaN (sqrt guard required)")
	_assert_true(is_finite(result.velocity.y),
		"TB-WC-009a — wall_jump_height=-50.0: velocity.y must be finite")
	_assert_true(result.jump_consumed,
		"TB-WC-009a — wall_jump_height=-50.0: jump_consumed=true even for zero-height wall jump")


# TB-WC-009b: wall_jump_height = -1.0 (just barely negative)
# The guard maps negative to 0.0 → vy = -sqrt(0.0) + gravity*delta = gravity*delta = 15.68
func test_negative_wall_jump_height_produces_zero_impulse() -> void:
	# Vulnerability: without the guard, vy = NaN (no upward impulse at all).
	# With the guard, vy = 0.0 + 980.0 * 0.016 = 15.68 (pure gravity, no upward push).
	var sim: MovementSimulation = MovementSimulation.new()
	sim.wall_jump_height = -1.0
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	# With guard: safe_wall_jump_height=0.0 → vy = -sqrt(0) + 980*0.016 = 0 + 15.68 = 15.68
	# jump_pressed=true means jump cut does not apply (vy=15.68 > jump_cut_velocity=-200)
	_assert_approx(result.velocity.y, 15.68,
		"TB-WC-009b — wall_jump_height=-1.0: guard fires, vy = 0 + 980*0.016 = 15.68")


# ===========================================================================
# GROUP 10 — Very large cling_timer prior value that already exceeds max_cling_time
#
# SPEC-29: cling_timer < max_cling_time is evaluated against prior_state.cling_timer.
# If prior_state.cling_timer is already vastly above max_cling_time, cling is
# immediately blocked without any grace period.
# Vulnerability: an implementation that only checks the timer on the first contact
# frame, or that resets the timer before checking eligibility, could incorrectly
# grant cling when the prior timer is already expired.
# ===========================================================================

# TB-WC-010a: prior.cling_timer=100.0, max_cling_time=1.5 → 100.0 < 1.5 is false → blocked
func test_prior_cling_timer_vastly_exceeds_max_immediately_blocked() -> void:
	# Vulnerability: if the implementation resets cling_timer=0.0 before the
	# eligibility check (instead of after), this scenario would incorrectly pass.
	var sim: MovementSimulation = MovementSimulation.new()
	# max_cling_time stays at default 1.5
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 100.0  # vastly exceeds max_cling_time=1.5
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(result.is_wall_clinging,
		"TB-WC-010a — prior.cling_timer=100.0 > max_cling_time=1.5: immediately blocked (not eligible)")
	_assert_approx(result.cling_timer, 0.0,
		"TB-WC-010a — prior.cling_timer=100.0: timer resets to 0.0 on non-eligible frame")


# TB-WC-010b: prior.cling_timer = max_cling_time + tiny_epsilon — just over boundary
# Prior timer = 1.5 + 0.0001 > 1.5 → not eligible
func test_prior_cling_timer_just_over_max_blocked() -> void:
	# Vulnerability: an off-by-one in the strict < comparison (using <= instead)
	# would incorrectly allow cling when timer is exactly at max.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 1.5 + 0.0001  # just above max_cling_time=1.5
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(result.is_wall_clinging,
		"TB-WC-010b — prior.cling_timer=1.5001 > max=1.5: blocked (strict < boundary)")


# TB-WC-010c: prior.cling_timer = max_cling_time - tiny_epsilon — just under boundary
# Prior timer = 1.5 - 0.0001 < 1.5 → still eligible (last microsecond frame)
func test_prior_cling_timer_just_under_max_still_eligible() -> void:
	# Vulnerability: if the implementation uses a <= 0.0 check on remaining time
	# (remaining = max - timer) instead of strict < comparison on timer directly,
	# floating point could push this over.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 1.5 - 0.0001  # just below max_cling_time=1.5
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-010c — prior.cling_timer=1.4999 < max=1.5: still eligible (strict < passes)")


# ===========================================================================
# GROUP 11 — State immutability for all 6 MovementState fields under wall cling
#
# The primary suite checks is_wall_clinging, cling_timer, and velocity partially.
# This group completes coverage by verifying velocity.x, is_on_floor, coyote_timer,
# and jump_consumed are also not mutated under adversarial wall cling scenarios.
# ===========================================================================

# TB-WC-011a: prior_state.velocity.x not mutated by a clinging simulate() call
func test_prior_state_velocity_x_not_mutated_by_wall_cling() -> void:
	# Vulnerability: if the step 7 horizontal formula writes to prior_state.velocity.x
	# by reference rather than to result.velocity.x, prior state would be corrupted.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(75.0, 20.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 0.0
	var _result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_approx(prior.velocity.x, 75.0,
		"TB-WC-011a — prior_state.velocity.x not mutated by cling simulate() (stays 75.0)")


# TB-WC-011b: prior_state.velocity.y not mutated on wall jump frame
func test_prior_state_velocity_y_not_mutated_on_wall_jump_frame() -> void:
	# Vulnerability: if the wall jump impulse assignment targets prior_state instead
	# of result, prior_state.velocity.y would be overwritten to the impulse value.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 30.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	_assert_approx(prior.velocity.y, 30.0,
		"TB-WC-011b — prior_state.velocity.y not mutated on wall jump frame (stays 30.0)")


# TB-WC-011c: prior_state.is_on_floor not mutated by wall cling simulate()
func test_prior_state_is_on_floor_not_mutated_by_wall_cling() -> void:
	# Vulnerability: if is_on_floor pass-through (step 10) writes to prior_state
	# instead of result, this test catches the bug.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)  # floor=false
	prior.jump_consumed = false
	var _result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(prior.is_on_floor,
		"TB-WC-011c — prior_state.is_on_floor not mutated by wall cling (stays false)")


# TB-WC-011d: prior_state.coyote_timer not mutated by wall cling simulate()
func test_prior_state_coyote_timer_not_mutated_by_wall_cling() -> void:
	# Vulnerability: if the coyote timer update (step 4) writes to prior_state
	# instead of result, this test catches the bug.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.coyote_timer = 0.05
	prior.jump_consumed = false
	prior.cling_timer = 0.0
	var _result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_approx(prior.coyote_timer, 0.05,
		"TB-WC-011d — prior_state.coyote_timer not mutated by wall cling (stays 0.05)")


# TB-WC-011e: prior_state.jump_consumed not mutated on wall jump frame
func test_prior_state_jump_consumed_not_mutated_on_wall_jump() -> void:
	# Vulnerability: wall jump sets result.jump_consumed=true. If the implementation
	# sets prior_state.jump_consumed instead of result.jump_consumed, prior is corrupted.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.is_wall_clinging = true
	prior.jump_consumed = false
	var _result: MovementSimulation.MovementState = sim.simulate(prior, 0.0, true, true, true, -1.0, false, 0.016)
	_assert_false(prior.jump_consumed,
		"TB-WC-011e — prior_state.jump_consumed not mutated on wall jump (stays false)")


# TB-WC-011f: All 6 new/relevant fields unchanged in one sweep — comprehensive immutability
# is_wall_clinging, cling_timer, velocity.x, velocity.y, jump_consumed, is_on_floor
func test_prior_state_all_fields_immutable_comprehensive() -> void:
	# This is the comprehensive sweep test. If any field is mutated, the specific
	# assertion tells the implementer exactly which field was corrupted.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(50.0, 25.0, false)
	prior.is_wall_clinging = true
	prior.cling_timer = 0.4
	prior.jump_consumed = false
	prior.coyote_timer = 0.05
	prior.is_on_floor = false
	var _result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	# All fields must be unchanged
	_assert_approx(prior.velocity.x, 50.0,
		"TB-WC-011f — comprehensive: prior.velocity.x not mutated (stays 50.0)")
	_assert_approx(prior.velocity.y, 25.0,
		"TB-WC-011f — comprehensive: prior.velocity.y not mutated (stays 25.0)")
	_assert_false(prior.is_on_floor,
		"TB-WC-011f — comprehensive: prior.is_on_floor not mutated (stays false)")
	_assert_approx(prior.coyote_timer, 0.05,
		"TB-WC-011f — comprehensive: prior.coyote_timer not mutated (stays 0.05)")
	_assert_false(prior.jump_consumed,
		"TB-WC-011f — comprehensive: prior.jump_consumed not mutated (stays false)")
	_assert_true(prior.is_wall_clinging,
		"TB-WC-011f — comprehensive: prior.is_wall_clinging not mutated (stays true)")
	_assert_approx(prior.cling_timer, 0.4,
		"TB-WC-011f — comprehensive: prior.cling_timer not mutated (stays 0.4)")


# ===========================================================================
# GROUP 12 — Config mutation between frames
#
# Vulnerability: If the simulation caches config values at construction time
# (e.g., captures cling_gravity_scale in a local during _init), mutations
# between frames will silently be ignored.
# ===========================================================================

# TB-WC-012a: cling_gravity_scale changes between frame 1 and frame 2
# Frame 1: scale=0.1 → vy contribution = 980*0.1*0.016 = 1.568
# Frame 2 (same sim, scale changed to 0.5): vy contribution = 980*0.5*0.016 = 7.84
# CHECKPOINT: Assumes config properties are read fresh each simulate() call.
func test_cling_gravity_scale_mutation_between_frames_takes_effect() -> void:
	# Vulnerability: if simulate() reads cling_gravity_scale from a cached local
	# set at init time, the frame-2 result would still use 0.1.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.cling_gravity_scale = 0.1

	# Frame 1 with scale=0.1
	var prior1: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior1.jump_consumed = false
	prior1.cling_timer = 0.0
	var state1: MovementSimulation.MovementState = sim.simulate(prior1, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_approx(state1.velocity.y, 980.0 * 0.1 * 0.016,
		"TB-WC-012a frame1 — scale=0.1: vy = 980*0.1*0.016 = 1.568")

	# Mutate config between frames
	sim.cling_gravity_scale = 0.5

	# Frame 2 with scale=0.5 (using state1 as prior, already clinging)
	var prior2: MovementSimulation.MovementState = _make_state_with(state1.velocity.x, 0.0, false)
	prior2.is_wall_clinging = state1.is_wall_clinging
	prior2.cling_timer = state1.cling_timer
	prior2.jump_consumed = false
	var state2: MovementSimulation.MovementState = sim.simulate(prior2, -1.0, false, false, true, 1.0, false, 0.016)
	# With scale now 0.5: vy = 0.0 + 980*0.5*0.016 = 7.84
	_assert_approx(state2.velocity.y, 980.0 * 0.5 * 0.016,
		"TB-WC-012a frame2 — scale mutated to 0.5: vy = 980*0.5*0.016 = 7.84 (not 1.568)")


# TB-WC-012b: max_cling_time changes between frames to expire an active cling
# Frame 1: max_cling_time=1.5, prior.cling_timer=1.4 → eligible
# Between frames: max_cling_time reduced to 1.0
# Frame 2: prior.cling_timer=1.416 (1.4+0.016) → 1.416 > 1.0 → not eligible
# CHECKPOINT: Assumes max_cling_time is read fresh each simulate() call.
func test_max_cling_time_mutation_between_frames_expires_cling() -> void:
	# Vulnerability: if max_cling_time is cached at first use, reducing it between
	# frames would not take effect and the player stays clinging past the new cap.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_cling_time = 1.5

	# Frame 1: timer=1.4, max=1.5 → eligible
	var prior1: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior1.jump_consumed = false
	prior1.cling_timer = 1.4
	var state1: MovementSimulation.MovementState = sim.simulate(prior1, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state1.is_wall_clinging,
		"TB-WC-012b frame1 — timer=1.4 < max=1.5: cling active")
	_assert_approx(state1.cling_timer, 1.416,
		"TB-WC-012b frame1 — timer = 1.4 + 0.016 = 1.416")

	# Reduce max_cling_time so the accumulated timer now exceeds it
	sim.max_cling_time = 1.0

	# Frame 2: prior.cling_timer=1.416 > max_cling_time=1.0 → not eligible
	var prior2: MovementSimulation.MovementState = _make_state_with(state1.velocity.x, state1.velocity.y, false)
	prior2.is_wall_clinging = state1.is_wall_clinging
	prior2.cling_timer = state1.cling_timer  # = 1.416
	prior2.jump_consumed = false
	var state2: MovementSimulation.MovementState = sim.simulate(prior2, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(state2.is_wall_clinging,
		"TB-WC-012b frame2 — max_cling_time reduced to 1.0: timer=1.416 > 1.0 → cling expired")
	_assert_approx(state2.cling_timer, 0.0,
		"TB-WC-012b frame2 — cling expired: timer resets to 0.0")


# TB-WC-012c: max_cling_time mutation — extending the cap re-enables cling on an expired timer
# Frame 1: max_cling_time=0.5, prior.cling_timer=0.6 → expired
# Between frames: max_cling_time extended to 2.0
# Frame 2 (off wall → timer=0.0 → return): with timer=0.0 and max=2.0 → eligible
func test_max_cling_time_mutation_extending_cap_enables_cling() -> void:
	# Vulnerability: if max_cling_time is cached before the extension,
	# cling would remain blocked even after extending the cap.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_cling_time = 0.5

	# Simulate an off-wall frame to reset timer to 0.0 (timer=0.6 was expired)
	var prior_off: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior_off.cling_timer = 0.6  # was expired under max=0.5
	prior_off.jump_consumed = false
	var state_off: MovementSimulation.MovementState = sim.simulate(prior_off, 0.0, false, false, false, 1.0, false, 0.016)
	_assert_approx(state_off.cling_timer, 0.0,
		"TB-WC-012c off-wall — timer resets to 0.0")

	# Now extend the cap
	sim.max_cling_time = 2.0

	# Return to wall: timer=0.0 < max=2.0 → eligible
	var prior_return: MovementSimulation.MovementState = _make_state_with(0.0, state_off.velocity.y, false)
	prior_return.cling_timer = state_off.cling_timer  # = 0.0
	prior_return.jump_consumed = false
	prior_return.is_wall_clinging = false
	var state_return: MovementSimulation.MovementState = sim.simulate(prior_return, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_true(state_return.is_wall_clinging,
		"TB-WC-012c — max_cling_time extended to 2.0: timer=0.0 < 2.0 → cling eligible")


# ===========================================================================
# GROUP 13 — Additional boundary combinations not in primary suite
# ===========================================================================

# TB-WC-013a: cling_timer exactly equal to max_cling_time (not just 1.5 == 1.5)
# Test with a custom max_cling_time=0.5, prior.cling_timer=0.5 → 0.5 < 0.5 is false
# Ensures the strict < boundary holds for non-default values of max_cling_time.
func test_cling_timer_equals_custom_max_cling_time_blocked() -> void:
	# Vulnerability: if the implementation uses <= instead of < in the timer check,
	# this test fails only for non-default values if the default 1.5 was accidentally
	# hardcoded as a pass condition.
	var sim: MovementSimulation = MovementSimulation.new()
	sim.max_cling_time = 0.5
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 0.5  # exactly equal to custom max
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(result.is_wall_clinging,
		"TB-WC-013a — custom max_cling_time=0.5, timer=0.5: 0.5<0.5 is false → blocked")


# TB-WC-013b: wall_normal_x = 0.0001 (almost zero, but positive)
# Input_axis=-1.0: product = -1.0 * 0.0001 = -0.0001 < 0.0 → TRUE → pressing toward wall
# An implementation that treats any near-zero normal as zero would block this incorrectly.
func test_near_zero_positive_wall_normal_x_still_clings() -> void:
	# Vulnerability: if the implementation checks |wall_normal_x| > threshold before
	# using it, a very small but positive normal would incorrectly block cling.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 0.0001, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-013b — wall_normal_x=0.0001, axis=-1.0: product=-0.0001<0 → pressing toward wall → cling")


# TB-WC-013c: wall_normal_x = -0.0001 (almost zero negative)
# input_axis=1.0: product = 1.0 * -0.0001 = -0.0001 < 0.0 → TRUE → pressing toward wall
func test_near_zero_negative_wall_normal_x_still_clings() -> void:
	# Vulnerability: same as TB-WC-013b but for negative near-zero wall normal.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	var result: MovementSimulation.MovementState = sim.simulate(prior, 1.0, false, false, true, -0.0001, false, 0.016)
	_assert_true(result.is_wall_clinging,
		"TB-WC-013c — wall_normal_x=-0.0001, axis=1.0: product=-0.0001<0 → pressing toward wall → cling")


# TB-WC-013d: very large delta — cling_timer increments by the clamped large delta
# delta=10.0 (simulating a 10-second hitch): cling_timer = prior + 10.0
# With prior.cling_timer=0.0 and max_cling_time=1.5: timer would become 10.0 > 1.5
# But eligibility is checked on prior.cling_timer (0.0 < 1.5 → eligible this frame).
# result.cling_timer should be 0.0 + 10.0 = 10.0 (even though it now exceeds max).
# On the NEXT frame with prior.cling_timer=10.0 → not eligible.
func test_very_large_delta_cling_timer_increments_correctly() -> void:
	# Vulnerability: an implementation that clamps the accumulated timer to max_cling_time
	# would produce 1.5 instead of 10.0. But the timer is raw accumulation; eligibility
	# check is a separate gate. The timer should accumulate honestly.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 0.0
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 10.0)
	# This frame: prior.cling_timer=0.0 < 1.5 → eligible (cling fires this frame)
	_assert_true(result.is_wall_clinging,
		"TB-WC-013d — large delta=10.0: eligible this frame (prior timer=0.0 < 1.5)")
	# Timer accumulates by full large delta
	_assert_approx(result.cling_timer, 10.0,
		"TB-WC-013d — large delta=10.0: cling_timer = 0.0 + 10.0 = 10.0 (not clamped to 1.5)")


# TB-WC-013e: very large delta, second frame — prior.cling_timer=10.0 → expired immediately
func test_very_large_delta_second_frame_immediately_expired() -> void:
	# Vulnerability: if the timer was incorrectly clamped to 1.5 in TB-WC-013d,
	# this test would see 1.5 < 1.5 = false (still would block, passing coincidentally).
	# The pair of tests is meaningful: 013d checks accumulation, 013e checks the next frame.
	var sim: MovementSimulation = MovementSimulation.new()
	var prior: MovementSimulation.MovementState = _make_state_with(0.0, 0.0, false)
	prior.jump_consumed = false
	prior.cling_timer = 10.0  # accumulated from a large-delta frame
	var result: MovementSimulation.MovementState = sim.simulate(prior, -1.0, false, false, true, 1.0, false, 0.016)
	_assert_false(result.is_wall_clinging,
		"TB-WC-013e — prior.cling_timer=10.0 > max=1.5: immediately expired on next frame")


# ===========================================================================
# Public entry point
# ===========================================================================

func run_all() -> int:
	print("--- test_wall_cling_simulation_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	# GROUP 1 — Diagonal wall_normal_x (±0.707)
	test_diagonal_wall_normal_positive_cling_eligible()
	test_diagonal_wall_normal_negative_cling_eligible()
	test_diagonal_wall_normal_pressing_away_no_cling()
	test_diagonal_wall_jump_horizontal_component()

	# GROUP 2 — NaN and Inf wall_normal_x
	test_nan_wall_normal_x_no_nan_output()
	test_inf_wall_normal_x_no_inf_output()
	test_neg_inf_wall_normal_x_no_inf_output()

	# GROUP 3 — cling_gravity_scale negative or >1.0
	test_negative_cling_gravity_scale_no_nan_output()
	test_supergravity_cling_gravity_scale()
	test_near_zero_cling_gravity_scale_applied_precisely()

	# GROUP 4 — max_cling_time very large (never expires)
	test_very_large_max_cling_time_cling_never_expires()
	test_very_large_max_cling_time_large_prior_timer_still_eligible()

	# GROUP 5 — Simultaneous is_on_floor + is_on_wall (floor priority, SPEC-34)
	test_floor_and_wall_simultaneously_floor_takes_priority()
	test_floor_and_wall_simultaneously_regular_jump_fires()
	test_floor_and_wall_simultaneously_coyote_timer_resets()

	# GROUP 6 — jump_just_pressed on first contact frame (no wall jump)
	test_first_contact_frame_no_wall_jump_only_cling_entry()
	test_second_contact_frame_wall_jump_fires()

	# GROUP 7 — Rapid alternating wall contact (timer resets)
	test_cling_leave_wall_return_timer_resets_fresh()
	test_cling_expires_leaves_returns_timer_resets()

	# GROUP 8 — wall_jump_horizontal_speed=0.0 (vertical-only wall jump)
	test_zero_wall_jump_horizontal_speed_vx_zero()
	test_zero_wall_jump_speed_prior_vx_cleared_by_wall_jump()

	# GROUP 9 — wall_jump_height negative (sqrt guard)
	test_negative_wall_jump_height_no_nan()
	test_negative_wall_jump_height_produces_zero_impulse()

	# GROUP 10 — Very large cling_timer prior value already exceeds max
	test_prior_cling_timer_vastly_exceeds_max_immediately_blocked()
	test_prior_cling_timer_just_over_max_blocked()
	test_prior_cling_timer_just_under_max_still_eligible()

	# GROUP 11 — State immutability for all 6 MovementState fields
	test_prior_state_velocity_x_not_mutated_by_wall_cling()
	test_prior_state_velocity_y_not_mutated_on_wall_jump_frame()
	test_prior_state_is_on_floor_not_mutated_by_wall_cling()
	test_prior_state_coyote_timer_not_mutated_by_wall_cling()
	test_prior_state_jump_consumed_not_mutated_on_wall_jump()
	test_prior_state_all_fields_immutable_comprehensive()

	# GROUP 12 — Config mutation between frames
	test_cling_gravity_scale_mutation_between_frames_takes_effect()
	test_max_cling_time_mutation_between_frames_expires_cling()
	test_max_cling_time_mutation_extending_cap_enables_cling()

	# GROUP 13 — Additional boundary combinations
	test_cling_timer_equals_custom_max_cling_time_blocked()
	test_near_zero_positive_wall_normal_x_still_clings()
	test_near_zero_negative_wall_normal_x_still_clings()
	test_very_large_delta_cling_timer_increments_correctly()
	test_very_large_delta_second_frame_immediately_expired()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count
