#
# test_hp_and_chunk_hud_adversarial.gd
#
# Adversarial / edge-case tests for the HP and chunk HUD slice.
# Generated by Test Breaker Agent — 2026-03-04
#
# Scope:
#   - Stronger monotonicity checks for HP bar across multiple HP levels.
#   - Stability and determinism of HUD under repeated _process() calls.
#   - Detach/recall-style HP + chunk state sequences and exact chunk label text.
#   - Scene-level HUD CanvasLayer identity assertions for core vs. infection scenes.
#
# All tests are deterministic and purely structural/behavioral at the HUD layer.
# They do not change simulation formulas; they only verify how existing UI
# scripts reflect PlayerController._current_state fields and scene wiring.
#

class_name HpAndChunkHudAdversarialTests
extends Object

const EPSILON: float = 1e-4

var _pass_count: int = 0
var _fail_count: int = 0


# ---------------------------------------------------------------------------
# Helpers (mirroring contracts from test_hp_and_chunk_hud.gd)
# ---------------------------------------------------------------------------

func _approx_eq(a: float, b: float) -> bool:
	return abs(a - b) < EPSILON


func _pass(test_name: String) -> void:
	_pass_count += 1
	print("  PASS: " + test_name)


func _fail(test_name: String, message: String) -> void:
	_fail_count += 1
	print("  FAIL: " + test_name + " — " + message)


func _assert_true(condition: bool, test_name: String) -> void:
	if condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected true, got false")


func _assert_false(condition: bool, test_name: String) -> void:
	if not condition:
		_pass(test_name)
	else:
		_fail(test_name, "expected false, got true")


func _assert_approx(a: float, b: float, test_name: String) -> void:
	if _approx_eq(a, b):
		_pass(test_name)
	else:
		_fail(test_name, "got " + str(a) + " expected " + str(b) + " (delta " + str(abs(a - b)) + ")")


func _load_core_scene() -> Node:
	var packed: PackedScene = load("res://scenes/levels/test_movement.tscn") as PackedScene
	if packed == null:
		_fail("adv_hud_core_scene_load", "could not load res://scenes/levels/test_movement.tscn")
		return null
	var inst: Node = packed.instantiate()
	if inst == null:
		_fail("adv_hud_core_scene_instantiate", "instantiate() returned null for test_movement.tscn")
		return null
	return inst


func _load_infection_scene() -> Node:
	var packed: PackedScene = load("res://scenes/levels/test_infection_loop.tscn") as PackedScene
	if packed == null:
		_fail("adv_hud_infection_scene_load", "could not load res://scenes/levels/test_infection_loop.tscn")
		return null
	var inst: Node = packed.instantiate()
	if inst == null:
		_fail("adv_hud_infection_scene_instantiate", "instantiate() returned null for test_infection_loop.tscn")
		return null
	return inst


func _find_player(root: Node) -> PlayerController:
	if root == null:
		return null
	var player: PlayerController = root.get_node_or_null("Player") as PlayerController
	return player


func _find_hud_layer_with_hp(root: Node) -> CanvasLayer:
	if root == null:
		return null
	for candidate in root.find_children("*", "CanvasLayer", true, false):
		var layer := candidate as CanvasLayer
		if layer == null:
			continue
		var hp_label: Label = layer.get_node_or_null("HPLabel") as Label
		if hp_label == null:
			var matches: Array = layer.find_children("HPLabel", "Label", true, false)
			if matches.size() > 0:
				hp_label = matches[0] as Label
		if hp_label != null:
			return layer
	return null


func _get_hp_label(hud: CanvasLayer) -> Label:
	if hud == null:
		return null
	var label: Label = hud.get_node_or_null("HPLabel") as Label
	if label != null:
		return label
	var matches: Array = hud.find_children("HPLabel", "Label", true, false)
	if matches.size() > 0:
		return matches[0] as Label
	return null


func _get_chunk_label(hud: CanvasLayer) -> Label:
	if hud == null:
		return null
	var label: Label = hud.get_node_or_null("ChunkStatusLabel") as Label
	if label != null:
		return label
	var matches: Array = hud.find_children("ChunkStatusLabel", "Label", true, false)
	if matches.size() > 0:
		return matches[0] as Label
	return null


func _get_hp_bar(hud: CanvasLayer) -> Range:
	if hud == null:
		return null
	var bar_node: Node = hud.get_node_or_null("HPBar")
	if bar_node != null and bar_node is Range:
		return bar_node as Range

	for child in hud.find_children("*", "", true, false):
		var range_node := child as Range
		if range_node != null:
			return range_node
	return null


func _label_contains_number(label: Label, value: float) -> bool:
	if label == null:
		return false
	var text_lower: String = label.text.to_lower()
	var expected_int_text: String = str(int(round(value)))
	return expected_int_text in text_lower


func _configure_player_hp_and_chunk(player: PlayerController, hp_value: float, has_chunk: bool) -> void:
	if player == null:
		return
	player._current_state.current_hp = hp_value
	player._current_state.has_chunk = has_chunk


func _attach_player_to_hud_if_supported(hud: CanvasLayer, player: PlayerController) -> void:
	if hud == null or player == null:
		return
	if "_player" in hud:
		hud._player = player


func _prepare_scene_for_hud(load_scene_func: Callable, scene_name: String) -> Dictionary:
	var root: Node = load_scene_func.call() as Node
	if root == null:
		return {}

	var player: PlayerController = _find_player(root)
	if player == null:
		_fail(scene_name + "_adv_hud_player_exists", "Player node is not a PlayerController in " + scene_name + " scene")
		root.free()
		return {}

	player._ready()

	var hud: CanvasLayer = _find_hud_layer_with_hp(root)
	if hud == null:
		_fail(scene_name + "_adv_hud_layer_missing", "HUD CanvasLayer with HPLabel not found; cannot run adversarial HUD tests")
		root.free()
		return {}

	_attach_player_to_hud_if_supported(hud, player)

	var hp_label: Label = _get_hp_label(hud)
	var chunk_label: Label = _get_chunk_label(hud)
	var hp_bar: Range = _get_hp_bar(hud)

	if hp_label == null or chunk_label == null or hp_bar == null:
		_fail(scene_name + "_adv_hud_elements_missing",
			"HPLabel, ChunkStatusLabel, and HP bar must all exist to run adversarial HUD tests")
		root.free()
		return {}

	return {
		"root": root,
		"player": player,
		"hud": hud,
		"hp_label": hp_label,
		"chunk_label": chunk_label,
		"hp_bar": hp_bar,
	}


# ---------------------------------------------------------------------------
# GROUP A: HP bar monotonicity and numeric label coverage
# ---------------------------------------------------------------------------

func _assert_monotonic_hp_bar_three_points(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var hp_bar: Range = ctx["hp_bar"]

	var hp_values: Array = [100.0, 50.0, 0.0]
	var bar_values: Array[float] = []
	var all_labels_ok: bool = true

	for hp in hp_values:
		_configure_player_hp_and_chunk(player, hp, true)
		hud._process(0.016)

		bar_values.append(float(hp_bar.value))
		if not _label_contains_number(hp_label, hp):
			all_labels_ok = false

	_assert_true(all_labels_ok,
		scene_name + "_adv_hud_hp_label_covers_100_50_0 — HP label text contains 100, 50, and 0 for representative HP values")

	if bar_values.size() == 3:
		var full: float = bar_values[0]
		var mid: float = bar_values[1]
		var zero: float = bar_values[2]

		var strictly_monotonic: bool = (
			full > mid + EPSILON
			and mid > zero + EPSILON
		)
		_assert_true(strictly_monotonic,
			scene_name + "_adv_hud_hp_bar_strictly_decreases_100_50_0 — HP bar value strictly decreases as HP decreases from 100→50→0")

	root.free()


func test_core_hud_hp_bar_and_label_monotonic_three_points() -> void:
	_assert_monotonic_hp_bar_three_points(_load_core_scene, "core")


func test_infection_hud_hp_bar_and_label_monotonic_three_points() -> void:
	_assert_monotonic_hp_bar_three_points(_load_infection_scene, "infection")


# ---------------------------------------------------------------------------
# GROUP B: Stability and determinism under repeated _process() calls
# ---------------------------------------------------------------------------

func _assert_hud_stable_for_constant_hp(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var hp_bar: Range = ctx["hp_bar"]

	_configure_player_hp_and_chunk(player, 73.0, true)
	hud._process(0.016)

	var initial_label_text: String = hp_label.text
	var initial_bar_value: float = hp_bar.value

	for _i in range(10):
		hud._process(0.016)

	var final_label_text: String = hp_label.text
	var final_bar_value: float = hp_bar.value

	_assert_true(initial_label_text == final_label_text,
		scene_name + "_adv_hud_label_stable_under_constant_hp — HP label text remains stable over repeated _process() calls at fixed HP")
	_assert_approx(initial_bar_value, final_bar_value,
		scene_name + "_adv_hud_bar_stable_under_constant_hp — HP bar value remains stable over repeated _process() calls at fixed HP")

	root.free()


func test_core_hud_stable_under_constant_hp() -> void:
	_assert_hud_stable_for_constant_hp(_load_core_scene, "core")


func test_infection_hud_stable_under_constant_hp() -> void:
	_assert_hud_stable_for_constant_hp(_load_infection_scene, "infection")


# ---------------------------------------------------------------------------
# GROUP C: Detach / recall-style HP and chunk state sequences
# ---------------------------------------------------------------------------

func _assert_detach_and_recall_style_sequence(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var chunk_label: Label = ctx["chunk_label"]
	var hp_bar: Range = ctx["hp_bar"]

	# Baseline: full HP, chunk attached.
	_configure_player_hp_and_chunk(player, 100.0, true)
	hud._process(0.016)
	var bar_full: float = hp_bar.value

	# Simulate detach: reduced HP, chunk detached.
	_configure_player_hp_and_chunk(player, 70.0, false)
	hud._process(0.016)
	var bar_detached: float = hp_bar.value
	var chunk_text_detached: String = chunk_label.text

	_assert_true(_label_contains_number(hp_label, 70.0),
		scene_name + "_adv_hud_hp_label_shows_detach_hp — HP label text updates to show reduced HP after detach-style state")
	_assert_true(chunk_text_detached == "Chunk: Detached",
		scene_name + "_adv_hud_chunk_label_exact_detached_text — ChunkStatusLabel shows exact 'Chunk: Detached' text when has_chunk=false") # CHECKPOINT

	# Simulate recall: higher HP than detached, chunk reattached.
	_configure_player_hp_and_chunk(player, 85.0, true)
	hud._process(0.016)
	var bar_recalled: float = hp_bar.value
	var chunk_text_recalled: String = chunk_label.text

	_assert_true(_label_contains_number(hp_label, 85.0),
		scene_name + "_adv_hud_hp_label_shows_recall_hp — HP label text updates to show restored HP after recall-style state")
	_assert_true(chunk_text_recalled == "Chunk: Attached",
		scene_name + "_adv_hud_chunk_label_exact_attached_text — ChunkStatusLabel shows exact 'Chunk: Attached' text when has_chunk=true") # CHECKPOINT

	# HP bar must move down on detach and then partially back up on recall,
	# without exceeding the original full-HP bar value.
	var bar_sequence_ok: bool = (
		bar_full > bar_detached + EPSILON
		and bar_recalled > bar_detached + EPSILON
		and bar_full >= bar_recalled - EPSILON
	)
	_assert_true(bar_sequence_ok,
		scene_name + "_adv_hud_hp_bar_sequence_detach_recall — HP bar decreases on detach and increases again on recall without overshooting baseline")

	root.free()


func test_core_hud_detach_and_recall_style_sequence() -> void:
	_assert_detach_and_recall_style_sequence(_load_core_scene, "core")


func test_infection_hud_detach_and_recall_style_sequence() -> void:
	_assert_detach_and_recall_style_sequence(_load_infection_scene, "infection")


# ---------------------------------------------------------------------------
# GROUP D: HUD CanvasLayer identity per scene
# ---------------------------------------------------------------------------

func test_core_hud_canvas_layer_is_ui_canvas_layer() -> void:
	var root: Node = _load_core_scene()
	if root == null:
		return

	var hud: CanvasLayer = _find_hud_layer_with_hp(root)
	var ui_layer: CanvasLayer = root.get_node_or_null("UI") as CanvasLayer

	var is_expected_layer: bool = (hud != null and ui_layer != null and hud == ui_layer)
	_assert_true(is_expected_layer,
		"core_adv_hud_canvas_layer_identity — core HUD with HP elements lives on the shared UI CanvasLayer") # CHECKPOINT

	root.free()


func test_infection_hud_canvas_layer_is_infection_ui() -> void:
	var root: Node = _load_infection_scene()
	if root == null:
		return

	var hud: CanvasLayer = _find_hud_layer_with_hp(root)
	var infection_ui: CanvasLayer = root.get_node_or_null("InfectionUI") as CanvasLayer

	var is_expected_layer: bool = (hud != null and infection_ui != null and hud == infection_ui)
	_assert_true(is_expected_layer,
		"infection_adv_hud_canvas_layer_identity — infection HUD with HP elements lives on the InfectionUI CanvasLayer") # CHECKPOINT

	root.free()


# ---------------------------------------------------------------------------
# GROUP E: Boundary — HP zero, negative, above initial max
# ---------------------------------------------------------------------------

func _assert_hud_boundary_hp_zero(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var hp_bar: Range = ctx["hp_bar"]

	# First observed HP is 0 → implementation uses max(0, 1.0) = 1.0 for effective max. # CHECKPOINT
	_configure_player_hp_and_chunk(player, 0.0, true)
	hud._process(0.016)

	_assert_true(_label_contains_number(hp_label, 0.0),
		scene_name + "_adv_hud_hp_zero_label — HP label shows 0 when current_hp is 0")
	var bar_at_min: bool = hp_bar.value <= 0.0 + EPSILON
	_assert_true(bar_at_min,
		scene_name + "_adv_hud_hp_zero_bar — HP bar value is at min (0) when current_hp is 0")

	root.free()


func test_core_hud_boundary_hp_zero() -> void:
	_assert_hud_boundary_hp_zero(_load_core_scene, "core")


func test_infection_hud_boundary_hp_zero() -> void:
	_assert_hud_boundary_hp_zero(_load_infection_scene, "infection")


func _assert_hud_boundary_hp_negative(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var hp_bar: Range = ctx["hp_bar"]

	# Negative HP: bar is clamped to 0; label shows actual value per implementation. # CHECKPOINT
	_configure_player_hp_and_chunk(player, -10.0, false)
	hud._process(0.016)

	var bar_clamped: bool = hp_bar.value <= 0.0 + EPSILON
	_assert_true(bar_clamped,
		scene_name + "_adv_hud_hp_negative_bar_clamped — HP bar value is clamped to 0 when current_hp is negative")
	# Label shows int(round(-10)) = -10
	var label_ok: bool = "-10" in hp_label.text
	_assert_true(label_ok,
		scene_name + "_adv_hud_hp_negative_label — HP label reflects negative current_hp value when bar is clamped")

	root.free()


func test_core_hud_boundary_hp_negative() -> void:
	_assert_hud_boundary_hp_negative(_load_core_scene, "core")


func test_infection_hud_boundary_hp_negative() -> void:
	_assert_hud_boundary_hp_negative(_load_infection_scene, "infection")


func _assert_hud_boundary_hp_above_initial_max(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var hp_bar: Range = ctx["hp_bar"]

	# Establish initial max with 100, then set HP above it (e.g. recall restore above initial).
	_configure_player_hp_and_chunk(player, 100.0, true)
	hud._process(0.016)
	var max_after_100: float = hp_bar.max_value

	_configure_player_hp_and_chunk(player, 150.0, true)
	hud._process(0.016)

	# Bar value must not exceed effective max (clamped); label may show 150 / 100. # CHECKPOINT
	var bar_not_above_max: bool = hp_bar.value <= hp_bar.max_value + EPSILON
	_assert_true(bar_not_above_max,
		scene_name + "_adv_hud_hp_above_max_bar_clamped — HP bar value does not exceed max when current_hp > initial max")
	_assert_true(_label_contains_number(hp_label, 150.0),
		scene_name + "_adv_hud_hp_above_max_label — HP label shows actual current_hp (150) when above inferred max")
	_assert_true(max_after_100 >= 99.0,
		scene_name + "_adv_hud_initial_max_stable — Inferred max remains stable when HP later exceeds it")

	root.free()


func test_core_hud_boundary_hp_above_initial_max() -> void:
	_assert_hud_boundary_hp_above_initial_max(_load_core_scene, "core")


func test_infection_hud_boundary_hp_above_initial_max() -> void:
	_assert_hud_boundary_hp_above_initial_max(_load_infection_scene, "infection")


# ---------------------------------------------------------------------------
# GROUP F: Null safety — _player null does not crash _process
# ---------------------------------------------------------------------------

func _assert_hud_safe_when_player_null(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var hud: CanvasLayer = ctx["hud"]

	# Clear player reference; next _process must not crash.
	hud._player = null
	hud._process(0.016)
	hud._process(0.0)

	_assert_true(true,
		scene_name + "_adv_hud_process_safe_when_player_null — _process() does not crash when _player is null")

	root.free()


func test_core_hud_safe_when_player_null() -> void:
	_assert_hud_safe_when_player_null(_load_core_scene, "core")


func test_infection_hud_safe_when_player_null() -> void:
	_assert_hud_safe_when_player_null(_load_infection_scene, "infection")


# ---------------------------------------------------------------------------
# GROUP G: Order dependency — rapid chunk state toggles
# ---------------------------------------------------------------------------

func _assert_hud_rapid_chunk_toggle(load_scene_func: Callable, scene_name: String) -> void:
	var ctx: Dictionary = _prepare_scene_for_hud(load_scene_func, scene_name)
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var chunk_label: Label = ctx["chunk_label"]

	# Toggle has_chunk true → false → true → false; final state must show Detached.
	_configure_player_hp_and_chunk(player, 50.0, true)
	hud._process(0.016)
	_configure_player_hp_and_chunk(player, 50.0, false)
	hud._process(0.016)
	_configure_player_hp_and_chunk(player, 50.0, true)
	hud._process(0.016)
	_configure_player_hp_and_chunk(player, 50.0, false)
	hud._process(0.016)

	_assert_true("detached" in chunk_label.text.to_lower(),
		scene_name + "_adv_hud_rapid_chunk_toggle_final — Chunk label shows Detached after rapid attach/detach sequence")

	root.free()


func test_core_hud_rapid_chunk_toggle() -> void:
	_assert_hud_rapid_chunk_toggle(_load_core_scene, "core")


func test_infection_hud_rapid_chunk_toggle() -> void:
	_assert_hud_rapid_chunk_toggle(_load_infection_scene, "infection")


# ---------------------------------------------------------------------------
# GROUP H: Determinism — same state yields same display semantics across scenes
# ---------------------------------------------------------------------------

func test_hud_determinism_same_state_both_scenes() -> void:
	var core_ctx: Dictionary = _prepare_scene_for_hud(_load_core_scene, "core")
	var inf_ctx: Dictionary = _prepare_scene_for_hud(_load_infection_scene, "infection")
	if core_ctx.is_empty() or inf_ctx.is_empty():
		return

	var core_player: PlayerController = core_ctx["player"]
	var core_hud: CanvasLayer = core_ctx["hud"]
	var core_hp_label: Label = core_ctx["hp_label"]
	var core_chunk_label: Label = core_ctx["chunk_label"]

	var inf_player: PlayerController = inf_ctx["player"]
	var inf_hud: CanvasLayer = inf_ctx["hud"]
	var inf_hp_label: Label = inf_ctx["hp_label"]
	var inf_chunk_label: Label = inf_ctx["chunk_label"]

	_configure_player_hp_and_chunk(core_player, 73.0, true)
	_configure_player_hp_and_chunk(inf_player, 73.0, true)
	core_hud._process(0.016)
	inf_hud._process(0.016)

	# Same script (infection_ui.gd) → same format; labels must match.
	_assert_true(core_hp_label.text == inf_hp_label.text,
		"adv_hud_determinism_hp_label — Same HP state produces identical HP label text in core and infection scenes")
	_assert_true(core_chunk_label.text == inf_chunk_label.text,
		"adv_hud_determinism_chunk_label — Same chunk state produces identical chunk label text in core and infection scenes")

	core_ctx["root"].free()
	inf_ctx["root"].free()


# ---------------------------------------------------------------------------
# GROUP I: Stress — repeated instantiate/free then one full behavior run
# ---------------------------------------------------------------------------

func test_hud_stress_repeated_instantiate_free_then_behavior() -> void:
	for _i in range(5):
		var root: Node = _load_core_scene()
		if root != null:
			root.free()

	# After 5 instantiate/free cycles, one full behavior run must still pass (no leak/crash).
	var ctx: Dictionary = _prepare_scene_for_hud(_load_core_scene, "core")
	if ctx.is_empty():
		return

	var root: Node = ctx["root"]
	var player: PlayerController = ctx["player"]
	var hud: CanvasLayer = ctx["hud"]
	var hp_label: Label = ctx["hp_label"]
	var chunk_label: Label = ctx["chunk_label"]

	_configure_player_hp_and_chunk(player, 100.0, true)
	hud._process(0.016)
	_assert_true(_label_contains_number(hp_label, 100.0),
		"adv_hud_stress_hp_after_cycles — HP label correct after repeated scene load/free")
	_assert_true("attached" in chunk_label.text.to_lower(),
		"adv_hud_stress_chunk_after_cycles — Chunk label correct after repeated scene load/free")

	root.free()


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

func run_all() -> int:
	print("--- test_hp_and_chunk_hud_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	# Group A: HP bar + label monotonicity
	test_core_hud_hp_bar_and_label_monotonic_three_points()
	test_infection_hud_hp_bar_and_label_monotonic_three_points()

	# Group B: Stability and determinism under repeated _process()
	test_core_hud_stable_under_constant_hp()
	test_infection_hud_stable_under_constant_hp()

	# Group C: Detach/recall-style HP + chunk state sequences
	test_core_hud_detach_and_recall_style_sequence()
	test_infection_hud_detach_and_recall_style_sequence()

	# Group D: HUD CanvasLayer identity per scene
	test_core_hud_canvas_layer_is_ui_canvas_layer()
	test_infection_hud_canvas_layer_is_infection_ui()

	# Group E: Boundary — HP zero, negative, above initial max
	test_core_hud_boundary_hp_zero()
	test_infection_hud_boundary_hp_zero()
	test_core_hud_boundary_hp_negative()
	test_infection_hud_boundary_hp_negative()
	test_core_hud_boundary_hp_above_initial_max()
	test_infection_hud_boundary_hp_above_initial_max()

	# Group F: Null safety
	test_core_hud_safe_when_player_null()
	test_infection_hud_safe_when_player_null()

	# Group G: Order dependency — rapid chunk toggles
	test_core_hud_rapid_chunk_toggle()
	test_infection_hud_rapid_chunk_toggle()

	# Group H: Determinism
	test_hud_determinism_same_state_both_scenes()

	# Group I: Stress
	test_hud_stress_repeated_instantiate_free_then_behavior()

	print("")
	print("  Results (adversarial HUD): " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count

