// AUTO-GENERATED by scripts/sync-api-types.sh — do not edit
// Regenerate: npm run sync-api-types
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read File */
        get: operations["read_file_api_files__file_path__get"];
        /** Write File */
        put: operations["write_file_api_files__file_path__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Stream */
        get: operations["run_stream_api_run_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Complete
         * @description Agent-oriented completion: one JSON with bounded logs (GET /api/run/complete).
         */
        get: operations["run_complete_api_run_complete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill Process */
        post: operations["kill_process_api_run_kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Status */
        get: operations["run_status_api_run_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/textures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Texture Assets
         * @description Return list of available pre-supplied texture assets with URLs.
         */
        get: operations["get_texture_assets_api_assets_textures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/textures/file/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Texture File
         * @description Serve a texture file by relative path from resources/textures/.
         */
        get: operations["serve_texture_file_api_assets_textures_file__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Asset */
        get: operations["serve_asset_api_assets__asset_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/enemies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Enemies
         * @description Enemy list + procedural build controls from ``asset_generation/python`` (introspects enemy ClassVars).
         */
        get: operations["get_enemies_api_meta_enemies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/animations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Animations
         * @description Return animation export names from canonical config module.
         */
        get: operations["get_animations_api_meta_animations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/load_existing/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Load Existing Candidates */
        get: operations["get_load_existing_candidates_api_registry_model_load_existing_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/load_existing/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Load Existing */
        post: operations["open_load_existing_api_registry_model_load_existing_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Registry */
        get: operations["get_model_registry_api_registry_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/enemies/{family}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Enemy Version Endpoint */
        delete: operations["delete_enemy_version_endpoint_api_registry_model_enemies__family__versions__version_id__delete"];
        options?: never;
        head?: never;
        /** Patch Enemy Version Endpoint */
        patch: operations["patch_enemy_version_endpoint_api_registry_model_enemies__family__versions__version_id__patch"];
        trace?: never;
    };
    "/api/registry/model/player_active_visual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Player Active Visual Endpoint */
        delete: operations["delete_player_active_visual_endpoint_api_registry_model_player_active_visual_delete"];
        options?: never;
        head?: never;
        /** Patch Player Active Visual Endpoint */
        patch: operations["patch_player_active_visual_endpoint_api_registry_model_player_active_visual_patch"];
        trace?: never;
    };
    "/api/registry/model/enemies/{family}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enemy Slots Endpoint */
        get: operations["get_enemy_slots_endpoint_api_registry_model_enemies__family__slots_get"];
        /** Put Enemy Slots Endpoint */
        put: operations["put_enemy_slots_endpoint_api_registry_model_enemies__family__slots_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/enemies/{family}/sync_animated_exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Sync Animated Exports Endpoint
         * @description Register on-disk ``animated_exports/{family}_animated_*.glb`` files missing from the manifest.
         */
        post: operations["post_sync_animated_exports_endpoint_api_registry_model_enemies__family__sync_animated_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/player/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Slots Endpoint */
        get: operations["get_player_slots_endpoint_api_registry_model_player_slots_get"];
        /** Put Player Slots Endpoint */
        put: operations["put_player_slots_endpoint_api_registry_model_player_slots_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/player/sync_player_exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Sync Player Exports Endpoint
         * @description Register on-disk ``player_exports/*.glb`` files missing from the manifest.
         */
        post: operations["post_sync_player_exports_endpoint_api_registry_model_player_sync_player_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/model/spawn_eligible/{family}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Spawn Eligible
         * @description Consumer-facing view: paths eligible for default spawn pool (MRVC-4).
         */
        get: operations["get_spawn_eligible_api_registry_model_spawn_eligible__family__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoolControlResponse */
        BoolControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bool";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Default */
            default: boolean;
        };
        /**
         * EnemyMetaRowResponse
         * @description Enemy slug and display label.
         */
        EnemyMetaRowResponse: {
            /**
             * Slug
             * @description Enemy family slug.
             */
            slug: string;
            /**
             * Label
             * @description Human-readable enemy label.
             */
            label: string;
        };
        /** EnemySlotsPut */
        EnemySlotsPut: {
            /**
             * Version Ids
             * @description Ordered slot IDs for a family.
             */
            version_ids?: string[];
        };
        /** EnemyVersionDeleteRequest */
        EnemyVersionDeleteRequest: {
            /**
             * Delete Files
             * @default false
             */
            delete_files: boolean;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /** Confirm Text */
            confirm_text?: string | null;
            /** Target Path */
            target_path?: string | null;
        };
        /** EnemyVersionPatch */
        EnemyVersionPatch: {
            /**
             * Draft
             * @description Draft flag; draft entries are not spawn-eligible.
             */
            draft?: boolean | null;
            /**
             * In Use
             * @description In-use (spawn pool) flag; ignored if draft.
             */
            in_use?: boolean | null;
            /**
             * Name
             * @description Optional display name; omit for no change, null or empty string clears.
             */
            name?: string | null;
            /**
             * Tags
             * @description Full tag list for the version; family slug is always injected on save.
             */
            tags?: string[] | null;
        };
        /**
         * FamilyBlockResponse
         * @description Enemy or player family block with versions and optional slot order.
         */
        FamilyBlockResponse: {
            /**
             * Versions
             * @description Version rows for this family.
             */
            versions?: components["schemas"]["VersionRowResponse"][];
            /**
             * Slots
             * @description Ordered slot version ids; empty when the family has no slot assignments.
             */
            slots?: string[];
        };
        /** FileWrite */
        FileWrite: {
            /** Content */
            content: string;
        };
        /** FillPickerControlResponse */
        FillPickerControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fill_picker";
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** FloatControlResponse */
        FloatControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "float";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Step */
            step: number;
            /** Default */
            default: number;
            /** Unit */
            unit?: string | null;
            /** Hint */
            hint?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe for the asset editor API.
         */
        HealthResponse: {
            /**
             * Status
             * @description Health status; only ok is defined.
             * @constant
             */
            status: "ok";
        };
        /** IntControlResponse */
        IntControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "int";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Default */
            default: number;
        };
        /** LoadExistingOpenRequest */
        LoadExistingOpenRequest: {
            /**
             * Kind
             * @description One of enemy|player|path for constrained load-open.
             */
            kind: string;
            /** Family */
            family?: string | null;
            /** Version Id */
            version_id?: string | null;
            /** Path */
            path?: string | null;
        };
        /**
         * MetaEnemiesResponse
         * @description Enemy catalog and procedural build controls.
         */
        MetaEnemiesResponse: {
            /**
             * Enemies
             * @description Enemy slug/label rows.
             */
            enemies: components["schemas"]["EnemyMetaRowResponse"][];
            /**
             * Animated Build Controls
             * @description Build control definitions keyed by enemy slug.
             */
            animated_build_controls?: {
                [key: string]: (components["schemas"]["IntControlResponse"] | components["schemas"]["SelectControlResponse"] | components["schemas"]["FloatControlResponse"] | components["schemas"]["StrControlResponse"] | components["schemas"]["SelectStrControlResponse"] | components["schemas"]["BoolControlResponse"] | components["schemas"]["FillPickerControlResponse"])[];
            };
            /**
             * Meta Backend
             * @description Whether Python introspection succeeded.
             * @enum {string}
             */
            meta_backend: "ok" | "fallback";
            /**
             * Meta Error
             * @description Error detail when meta_backend is fallback.
             */
            meta_error?: string | null;
        };
        /**
         * ModelRegistryResponse
         * @description Effective model registry manifest (MRVC).
         */
        ModelRegistryResponse: {
            /**
             * Schema Version
             * @description Manifest schema version (>= 1).
             */
            schema_version: number;
            /**
             * Enemies
             * @description Enemy families keyed by slug.
             */
            enemies: {
                [key: string]: components["schemas"]["FamilyBlockResponse"];
            };
            /** @description Player family block when present. */
            player?: components["schemas"]["FamilyBlockResponse"] | null;
            /** @description Active player visual row or null. */
            player_active_visual?: components["schemas"]["PlayerActiveVisualResponse"] | null;
        };
        /** PlayerActiveVisualDeleteRequest */
        PlayerActiveVisualDeleteRequest: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /**
         * PlayerActiveVisualResponse
         * @description Player active visual selection row.
         */
        PlayerActiveVisualResponse: {
            /**
             * Path
             * @description Allowlisted path to the active player visual GLB.
             */
            path: string;
            /**
             * Draft
             * @description Draft flag for the active visual.
             */
            draft: boolean;
        };
        /** PlayerVisualPatch */
        PlayerVisualPatch: {
            /** Draft */
            draft?: boolean | null;
            /**
             * Path
             * @description Allowlisted path under python_root.
             */
            path?: string | null;
        };
        /** SelectControlResponse */
        SelectControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "select";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Options */
            options: number[];
            /** Default */
            default: number;
        };
        /** SelectStrControlResponse */
        SelectStrControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "select_str";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Options */
            options: string[];
            /** Default */
            default: string;
            /** Segmented */
            segmented?: boolean | null;
            /** Hint */
            hint?: string | null;
        };
        /** StrControlResponse */
        StrControlResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "str";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Default */
            default: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionRowResponse
         * @description One version row under a family block.
         */
        VersionRowResponse: {
            /**
             * Id
             * @description Stable version identifier within the family.
             */
            id: string;
            /**
             * Path
             * @description Registry-relative GLB path under an allowlisted prefix.
             */
            path: string;
            /**
             * Draft
             * @description Draft flag; draft rows are not spawn-eligible.
             */
            draft: boolean;
            /**
             * In Use
             * @description In-use flag for spawn pool eligibility.
             */
            in_use: boolean;
            /**
             * Name
             * @description Optional display name (max 128 chars).
             */
            name?: string | null;
            /**
             * Tags
             * @description Normalized tags; first entry is always the model family slug.
             */
            tags?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_files_api_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_file_api_files__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_file_api_files__file_path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_api_run_stream_get: {
        parameters: {
            query: {
                cmd: string;
                enemy?: string | null;
                count?: number | null;
                description?: string | null;
                difficulty?: string | null;
                finish?: string | null;
                hex_color?: string | null;
                build_options?: string | null;
                output_draft?: boolean;
                replace_variant_index?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_complete_api_run_complete_get: {
        parameters: {
            query: {
                /** @description Pipeline command (same allowlist as /stream). */
                cmd: string;
                enemy?: string | null;
                count?: number | null;
                description?: string | null;
                difficulty?: string | null;
                finish?: string | null;
                hex_color?: string | null;
                build_options?: string | null;
                output_draft?: boolean;
                replace_variant_index?: number | null;
                /** @description Max milliseconds to wait for the subprocess to exit. Default and cap from server settings. */
                max_wait_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_process_api_run_kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_status_api_run_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_assets_api_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_texture_assets_api_assets_textures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_texture_file_api_assets_textures_file__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_asset_api_assets__asset_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enemies_api_meta_enemies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaEnemiesResponse"];
                };
            };
        };
    };
    get_animations_api_meta_animations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    get_load_existing_candidates_api_registry_model_load_existing_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    open_load_existing_api_registry_model_load_existing_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadExistingOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_registry_api_registry_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRegistryResponse"];
                };
            };
        };
    };
    delete_enemy_version_endpoint_api_registry_model_enemies__family__versions__version_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnemyVersionDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_enemy_version_endpoint_api_registry_model_enemies__family__versions__version_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnemyVersionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_active_visual_endpoint_api_registry_model_player_active_visual_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerActiveVisualDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_player_active_visual_endpoint_api_registry_model_player_active_visual_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerVisualPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enemy_slots_endpoint_api_registry_model_enemies__family__slots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_enemy_slots_endpoint_api_registry_model_enemies__family__slots_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnemySlotsPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sync_animated_exports_endpoint_api_registry_model_enemies__family__sync_animated_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_slots_endpoint_api_registry_model_player_slots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_player_slots_endpoint_api_registry_model_player_slots_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnemySlotsPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sync_player_exports_endpoint_api_registry_model_player_sync_player_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_spawn_eligible_api_registry_model_spawn_eligible__family__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
