#!/usr/bin/env bash
# Sync FastAPI OpenAPI document → src/api.types.ts (M902-24).
set -euo pipefail

# Non-interactive defaults for lefthook / agent runs (npx install prompts, git, etc.).
export CI="${CI:-1}"
export GIT_TERMINAL_PROMPT=0
export NPM_CONFIG_YES="${NPM_CONFIG_YES:-true}"

die() {
  echo "$1" >&2
  exit "${2:-1}"
}

on_err() {
  die "unexpected error at line ${BASH_LINENO[0]}" 1
}
trap on_err ERR

write_output_file() {
  local src_tmp="$1"
  local dest="$2"
  set +e
  {
    printf '%s\n' "// AUTO-GENERATED by scripts/sync-api-types.sh — do not edit"
    printf '%s\n' "// Regenerate: npm run sync-api-types"
    cat "$src_tmp"
  } >"$dest"
  local write_rc=$?
  set -e
  if [[ "$write_rc" -ne 0 ]] || [[ ! -s "$dest" ]]; then
    die "generation failed: could not write ${dest}" 5
  fi
}

FRONTEND_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$FRONTEND_ROOT"

if [[ ! -f package.json ]]; then
  die "missing package.json in frontend root" 2
fi

if ! command -v curl >/dev/null 2>&1; then
  die "curl not found on PATH" 2
fi
if ! command -v node >/dev/null 2>&1; then
  die "node not found on PATH" 2
fi
if ! command -v npx >/dev/null 2>&1; then
  die "npx not found on PATH" 2
fi

BLOBERT_OPENAPI_URL="${BLOBERT_OPENAPI_URL:-http://127.0.0.1:8000/openapi.json}"
CACHE_PATH="${BLOBERT_OPENAPI_CACHE:-scripts/fixtures/openapi.cached.json}"
OUTPUT_PATH="${BLOBERT_OPENAPI_OUTPUT:-src/api.types.ts}"
SKIP_FETCH="${BLOBERT_SYNC_SKIP_FETCH:-}"

validate_openapi_json() {
  local spec_file="$1"
  node -e '
const fs = require("fs");
const p = process.argv[1];
let raw = fs.readFileSync(p, "utf8").trim();
if (!raw) process.exit(1);
let data;
try {
  data = JSON.parse(raw);
} catch {
  process.exit(1);
}
if (!data || typeof data !== "object" || Array.isArray(data)) process.exit(1);
const ver = data.openapi;
if (typeof ver !== "string" || !/^3\./.test(ver)) process.exit(1);
process.exit(0);
' "$spec_file"
}

write_cache_from_file() {
  local src="$1"
  mkdir -p "$(dirname "$CACHE_PATH")"
  node -e '
const fs = require("fs");
const src = process.argv[1];
const dest = process.argv[2];
const data = JSON.parse(fs.readFileSync(src, "utf8"));
fs.writeFileSync(dest, JSON.stringify(data));
' "$src" "$CACHE_PATH"
}

SPEC_INPUT=""
FETCH_TMP=""
USED_CACHE_FALLBACK=0

if [[ "$SKIP_FETCH" == "1" ]]; then
  if [[ ! -f "$CACHE_PATH" ]]; then
    die "fetch failed: no cache at ${CACHE_PATH}" 3
  fi
  if ! validate_openapi_json "$CACHE_PATH"; then
    die "invalid cache at ${CACHE_PATH}" 4
  fi
  SPEC_INPUT="$CACHE_PATH"
else
  FETCH_TMP="$(mktemp)"
  FETCH_OK=0
  if curl --fail --show-error --silent --max-time 5 -o "$FETCH_TMP" "$BLOBERT_OPENAPI_URL"; then
    if validate_openapi_json "$FETCH_TMP"; then
      write_cache_from_file "$FETCH_TMP"
      SPEC_INPUT="$FETCH_TMP"
      FETCH_OK=1
    fi
  fi
  if [[ "$FETCH_OK" -eq 0 ]]; then
    if [[ -f "$CACHE_PATH" ]] && validate_openapi_json "$CACHE_PATH"; then
      echo "using cached OpenAPI spec (${CACHE_PATH}) after fetch failed" >&2
      SPEC_INPUT="$CACHE_PATH"
      USED_CACHE_FALLBACK=1
    elif [[ -f "$CACHE_PATH" ]]; then
      rm -f "$FETCH_TMP"
      die "invalid cache at ${CACHE_PATH}" 4
    else
      rm -f "$FETCH_TMP"
      die "fetch failed and no cache at ${CACHE_PATH}" 3
    fi
  fi
fi

GEN_TMP="$(mktemp)"
OUT_TMP="$(mktemp)"
cleanup() {
  rm -f "$FETCH_TMP" "$GEN_TMP" "$OUT_TMP" 2>/dev/null || true
}
trap cleanup EXIT

mkdir -p "$(dirname "$OUTPUT_PATH")" 2>/dev/null || true

trap - ERR
set +e
npx --yes openapi-typescript@7.13.0 "$SPEC_INPUT" -o "$OUT_TMP" 2>"$GEN_TMP"
gen_rc=$?
set -e
trap on_err ERR

if [[ "$gen_rc" -ne 0 ]]; then
  cat "$GEN_TMP" >&2 || true
  die "generation failed: openapi-typescript exited non-zero" 5
fi

if [[ ! -s "$OUT_TMP" ]]; then
  die "generation failed: output file empty" 5
fi

trap - ERR
write_output_file "$OUT_TMP" "$OUTPUT_PATH"
trap on_err ERR

exit 0
