#
# test_player_physics_frame_order_adversarial.gd
#
# Adversarial extension of PlayerController3D physics frame order tests (M11-02).
# Spec edge cases EC-2, EC-10, EC-11, EC-12, PFO-5, PFO-7 boundaries.
# Ticket: project_board/11_milestone_11_base_mutation_attacks/in_progress/02_physics_frame_order.md
# Spec: project_board/specs/player_physics_frame_order_spec.md
#
# Generated by Test Breaker Agent — 2026-05-23.
#

class_name PlayerPhysicsFrameOrderAdversarialTests
extends "res://tests/scripts/player/test_player_physics_frame_order.gd"

const BUFFER_EXPIRE_FRAMES: int = 7
const VY_ZERO_EPS: float = 0.02
const DOUBLE_JUMP_VY_WINDOW: float = 0.08


# ---------------------------------------------------------------------------
# Adversarial helpers
# ---------------------------------------------------------------------------

func _require_jump_buffer_export(player: CharacterBody3D, test_name: String) -> bool:
	if not ("jump_buffer_time" in player):
		_fail_missing_api(test_name, "jump_buffer_time export missing")
		return false
	return true


func _require_mask_accessor(player: CharacterBody3D, test_name: String) -> bool:
	if not player.has_method("get_one_way_collision_mask"):
		_fail_missing_api(test_name, "get_one_way_collision_mask() missing")
		return false
	return true


func _airborne_frames_with_buffer_set(player: CharacterBody3D, air_frames: int) -> bool:
	_press_jump_once()
	for _i in range(3):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
		if not player.is_on_floor():
			break
	if player.is_on_floor():
		return false
	_press_jump_once()
	for _i in range(air_frames):
		if player.is_on_floor():
			player.global_position.y += 0.4
			player.velocity = Vector3(0.0, -0.35, 0.0)
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
	return not player.is_on_floor()


func _count_upward_spikes(player: CharacterBody3D, frame_budget: int) -> int:
	var spikes: int = 0
	var was_low: bool = true
	for _i in range(frame_budget):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
		var vy: float = _player_vy(player)
		if was_low and vy > UPWARD_VY_EPS:
			spikes += 1
			was_low = false
		elif vy < VY_ZERO_EPS:
			was_low = true
	return spikes


# ---------------------------------------------------------------------------
# EC-2 / PFO-3 — Jump buffer expiry at 0.1s boundary
# ---------------------------------------------------------------------------

func test_tb_pfo_001_buffer_expired_before_landing_no_buffered_jump() -> void:
	# VULNERABILITY: Off-by-one on timer decrement lets buffer survive past jump_buffer_time.
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_001", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_001"):
		_teardown_sandbox(harness)
		return
	_apply_player_props(player, {"jump_buffer_time": JUMP_BUFFER_DEFAULT})
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_001", "player did not settle")
		return
	_press_jump_once()
	for _i in range(3):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
	if not _airborne_frames_with_buffer_set(player, BUFFER_EXPIRE_FRAMES):
		_teardown_sandbox(harness)
		_fail("tb_pfo_001", "could not keep player airborne through buffer window")
		return
	var saw_upward_on_landing: bool = false
	for _i in range(50):
		_release_all_input()
		var was_airborne: bool = not player.is_on_floor()
		_step_player(player, PHYSICS_STEP)
		if player.is_on_floor() and was_airborne and _player_vy(player) > UPWARD_VY_EPS:
			saw_upward_on_landing = true
			break
	_assert_false(
		saw_upward_on_landing,
		"tb_pfo_001_no_buffered_jump_after_0_1s_airborne_expiry"
	)
	_teardown_sandbox(harness)


func test_tb_pfo_002_buffer_still_valid_one_frame_before_expiry() -> void:
	# VULNERABILITY: Expiring buffer one frame early breaks EC-1 polish at t≈0.1s.
	# CHECKPOINT: Uses short fall so landing occurs on frame 6 after air-press (5 decrement steps).
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_002", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_002"):
		_teardown_sandbox(harness)
		return
	_apply_player_props(player, {"jump_buffer_time": JUMP_BUFFER_DEFAULT})
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_002", "player did not settle")
		return
	if not _begin_short_fall(player):
		_teardown_sandbox(harness)
		_fail("tb_pfo_002", "short fall setup failed")
		return
	_arm_jump_buffer_after_coyote(player)
	_hold_airborne_until_buffer_landing_window(player)
	var saw_upward_on_landing: bool = false
	for _i in range(45):
		_release_all_input()
		var was_airborne: bool = not player.is_on_floor()
		_step_player(player, PHYSICS_STEP)
		if player.is_on_floor() and was_airborne and _player_vy(player) > UPWARD_VY_EPS:
			saw_upward_on_landing = true
			break
	_assert_true(
		saw_upward_on_landing,
		"tb_pfo_002_buffered_jump_still_valid_just_before_0_1s_expiry"
	)
	_teardown_sandbox(harness)


func test_tb_pfo_003_negative_jump_buffer_time_treated_as_disabled() -> void:
	# VULNERABILITY: Negative export may wrap timer or enable spurious buffer (PFO-3 undefined → 0).
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_003", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_003"):
		_teardown_sandbox(harness)
		return
	_apply_player_props(player, {"jump_buffer_time": -0.05})
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_003", "player did not settle")
		return
	if not _begin_short_fall(player):
		_teardown_sandbox(harness)
		_fail("tb_pfo_003", "short fall setup failed")
		return
	_press_jump_once()
	var saw_upward_on_landing: bool = false
	for _i in range(45):
		_release_all_input()
		var was_airborne: bool = not player.is_on_floor()
		_step_player(player, PHYSICS_STEP)
		if player.is_on_floor() and was_airborne and _player_vy(player) > UPWARD_VY_EPS:
			saw_upward_on_landing = true
			break
	_assert_false(
		saw_upward_on_landing,
		"tb_pfo_003_negative_buffer_time_disables_landing_buffer"
	)
	_teardown_sandbox(harness)


# ---------------------------------------------------------------------------
# EC-10 — enemy_movement_root suppresses buffer accumulation
# ---------------------------------------------------------------------------

func test_tb_pfo_004_enemy_root_blocks_buffer_on_landing() -> void:
	# VULNERABILITY: Step 0 suppression skipped — buffer set while rooted, fires after root ends.
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_004", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_004"):
		_teardown_sandbox(harness)
		return
	if not player.has_method("apply_enemy_movement_root"):
		_teardown_sandbox(harness)
		_fail_missing_api("tb_pfo_004", "apply_enemy_movement_root() missing")
		return
	_apply_player_props(player, {"jump_buffer_time": JUMP_BUFFER_DEFAULT})
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_004", "player did not settle")
		return
	if not _begin_short_fall(player):
		_teardown_sandbox(harness)
		_fail("tb_pfo_004", "short fall setup failed")
		return
	player.call("apply_enemy_movement_root", 1.0)
	_press_jump_once()
	for _i in range(4):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
	var saw_upward_on_landing: bool = false
	for _i in range(45):
		_release_all_input()
		var was_airborne: bool = not player.is_on_floor()
		_step_player(player, PHYSICS_STEP)
		if player.is_on_floor() and was_airborne and _player_vy(player) > UPWARD_VY_EPS:
			saw_upward_on_landing = true
			break
	_assert_false(
		saw_upward_on_landing,
		"tb_pfo_004_enemy_root_suppresses_buffered_jump_on_landing"
	)
	_teardown_sandbox(harness)


# ---------------------------------------------------------------------------
# PFO-4 / EC-4 — Coyote boundary and buffer interaction
# ---------------------------------------------------------------------------

func test_tb_pfo_005_coyote_jump_denied_after_window_expires() -> void:
	# VULNERABILITY: Coyote timer not decremented in sim or stale prior is_on_floor grants free jump.
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_005", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	_apply_player_props(player, {"coyote_time": COYOTE_TIME_DEFAULT})
	if not _settle_on_floor(player, LEDGE_SPAWN):
		_teardown_sandbox(harness)
		_fail("tb_pfo_005", "player did not settle")
		return
	var left_ledge: bool = false
	for _i in range(100):
		_hold_axis(1.0)
		_step_player(player, PHYSICS_STEP)
		if not player.is_on_floor():
			left_ledge = true
			for _j in range(COYOTE_EXPIRE_FRAMES):
				_release_all_input()
				_step_player(player, PHYSICS_STEP)
			_press_jump_once()
			_step_player(player, PHYSICS_STEP)
			break
	if not left_ledge:
		_teardown_sandbox(harness)
		_fail("tb_pfo_005", "player never left ledge")
		return
	_assert_false(
		_player_vy(player) > UPWARD_VY_EPS,
		"tb_pfo_005_no_coyote_jump_after_0_1s_airborne"
	)
	_teardown_sandbox(harness)


func test_tb_pfo_006_coyote_jump_does_not_double_with_buffer_on_landing() -> void:
	# VULNERABILITY: Coyote jump consumes sim but buffer still fires on landing (EC-11).
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_006", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_006"):
		_teardown_sandbox(harness)
		return
	_apply_player_props(
		player,
		{"coyote_time": COYOTE_TIME_DEFAULT, "jump_buffer_time": JUMP_BUFFER_DEFAULT}
	)
	if not _settle_on_floor(player, LEDGE_SPAWN):
		_teardown_sandbox(harness)
		_fail("tb_pfo_006", "player did not settle")
		return
	var coyote_fired: bool = false
	for _i in range(100):
		_hold_axis(1.0)
		_step_player(player, PHYSICS_STEP)
		if not player.is_on_floor():
			_press_jump_once()
			_step_player(player, PHYSICS_STEP)
			if _player_vy(player) > UPWARD_VY_EPS:
				coyote_fired = true
			break
	if not coyote_fired:
		_teardown_sandbox(harness)
		_fail("tb_pfo_006", "coyote jump did not fire in setup")
		return
	var upward_spikes: int = _count_upward_spikes(player, 120)
	_assert_eq_int(
		1,
		upward_spikes,
		"tb_pfo_006_single_upward_impulse_coyote_plus_landing_no_double"
	)
	_teardown_sandbox(harness)


# ---------------------------------------------------------------------------
# EC-11 / PFO-5 — Double jump via buffer
# ---------------------------------------------------------------------------

func test_tb_pfo_007_double_air_press_buffered_landing_single_jump() -> void:
	# VULNERABILITY: Each air-press resets buffer timer → multiple jumps on landing.
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_007", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_007"):
		_teardown_sandbox(harness)
		return
	_apply_player_props(player, {"jump_buffer_time": JUMP_BUFFER_DEFAULT})
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_007", "player did not settle")
		return
	if not _begin_short_fall(player):
		_teardown_sandbox(harness)
		_fail("tb_pfo_007", "short fall setup failed")
		return
	_arm_jump_buffer_after_coyote(player)
	for _i in range(2):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
	_arm_jump_buffer_while_airborne(player)
	_hold_airborne_until_buffer_landing_window(player)
	var upward_spikes: int = 0
	for _i in range(50):
		_release_all_input()
		var was_airborne: bool = not player.is_on_floor()
		_step_player(player, PHYSICS_STEP)
		if player.is_on_floor() and was_airborne and _player_vy(player) > UPWARD_VY_EPS:
			upward_spikes += 1
		elif upward_spikes > 0 and _player_vy(player) < VY_ZERO_EPS:
			break
	_assert_eq_int(
		1,
		upward_spikes,
		"tb_pfo_007_double_air_press_yields_one_buffered_landing_jump"
	)
	_teardown_sandbox(harness)


func test_tb_pfo_008_grounded_single_press_single_upward_spike() -> void:
	# VULNERABILITY: Raw press + buffer consume same frame → twin impulses (PFO-5.4).
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_008", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_jump_buffer_export(player, "tb_pfo_008"):
		_teardown_sandbox(harness)
		return
	_apply_player_props(player, {"jump_buffer_time": JUMP_BUFFER_DEFAULT})
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_008", "player did not settle")
		return
	_press_jump_once()
	var spikes: int = _count_upward_spikes(player, 24)
	_assert_eq_int(
		1,
		spikes,
		"tb_pfo_008_grounded_press_single_jump_impulse"
	)
	_teardown_sandbox(harness)


# ---------------------------------------------------------------------------
# PFO-7 / EC-5, EC-6 — Mask at vy==0 and sustained ascending rule
# ---------------------------------------------------------------------------

func test_tb_pfo_009_mask_ground_only_every_frame_while_vy_positive() -> void:
	# VULNERABILITY: Mask updated only on jump frame, not every ascending tick (EC-12 partial).
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_009", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_mask_accessor(player, "tb_pfo_009"):
		_teardown_sandbox(harness)
		return
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_009", "player did not settle")
		return
	_press_jump_once()
	var rising_frames_checked: int = 0
	for _i in range(40):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
		var vy: float = _player_vy(player)
		if vy > VY_ZERO_EPS:
			rising_frames_checked += 1
			var mask: int = int(player.call("get_one_way_collision_mask"))
			_assert_eq_int(
				GROUND_MASK,
				mask,
				"tb_pfo_009_mask_ground_only_while_vy_positive_frame_" + str(rising_frames_checked)
			)
		elif rising_frames_checked > 0:
			break
	_assert_true(
		rising_frames_checked >= 3,
		"tb_pfo_009_observed_multiple_ascending_frames"
	)
	_teardown_sandbox(harness)


func test_tb_pfo_010_mask_includes_one_way_at_apex_when_vy_zero_or_negative() -> void:
	# VULNERABILITY: Strict vy>0 rule mis-classifies apex (vy==0) → drops one-way while on platform.
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_010", "sandbox harness unavailable")
		return
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_mask_accessor(player, "tb_pfo_010"):
		_teardown_sandbox(harness)
		return
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_010", "player did not settle")
		return
	_press_jump_once()
	var saw_apex_mask: bool = false
	for _i in range(80):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
		var vy: float = _player_vy(player)
		if vy <= VY_ZERO_EPS and player.is_on_floor():
			var mask: int = int(player.call("get_one_way_collision_mask"))
			_assert_eq_int(
				FULL_GROUND_MASK,
				mask,
				"tb_pfo_010_mask_full_when_vy_zero_on_floor"
			)
			saw_apex_mask = true
			break
	if not saw_apex_mask:
		_fail("tb_pfo_010", "never observed vy<=0 on floor after jump for apex mask check")
	_teardown_sandbox(harness)


func test_tb_pfo_011_mask_full_while_falling_toward_one_way() -> void:
	# VULNERABILITY: Mask still ground-only during descent → miss one-way landing (EC-8).
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_011", "sandbox harness unavailable")
		return
	var root: Node3D = harness["root"] as Node3D
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_mask_accessor(player, "tb_pfo_011"):
		_teardown_sandbox(harness)
		return
	var platform_y: float = 2.0
	_add_static_box(root, "OneWayPlatform", 2, Vector3(0.0, platform_y, 0.0), Vector3(8.0, 0.25, 10.0))
	player.position = Vector3(0.0, platform_y + 1.2, 0.0)
	player.velocity = Vector3.ZERO
	var saw_falling_full_mask: bool = false
	for _i in range(90):
		_release_all_input()
		_step_player(player, PHYSICS_STEP)
		var vy: float = _player_vy(player)
		if vy < -VY_ZERO_EPS and not player.is_on_floor():
			var mask: int = int(player.call("get_one_way_collision_mask"))
			if mask == FULL_GROUND_MASK:
				saw_falling_full_mask = true
			_assert_eq_int(
				FULL_GROUND_MASK,
				mask,
				"tb_pfo_011_mask_includes_one_way_while_falling_before_land"
			)
			break
	_assert_true(
		saw_falling_full_mask,
		"tb_pfo_011_observed_falling_phase_before_one_way_land"
	)
	_teardown_sandbox(harness)


# ---------------------------------------------------------------------------
# EC-12 — Reorder regression: mask before move_and_slide (behavioral)
# ---------------------------------------------------------------------------

func test_tb_pfo_012_ascending_through_one_way_never_blocked_mid_rise() -> void:
	# VULNERABILITY: Mask applied after move_and_slide — upward velocity stalls at platform lip.
	var harness: Dictionary = _load_sandbox_harness()
	if harness.is_empty():
		_fail("tb_pfo_012", "sandbox harness unavailable")
		return
	var root: Node3D = harness["root"] as Node3D
	var player: CharacterBody3D = harness["player"] as CharacterBody3D
	if not _require_mask_accessor(player, "tb_pfo_012"):
		_teardown_sandbox(harness)
		return
	var platform_y: float = 1.85
	_add_static_box(root, "OneWayPlatform", 2, Vector3(0.0, platform_y, 0.0), Vector3(6.0, 0.25, 10.0))
	if not _settle_on_floor(player, Vector3(0.0, 1.0, 0.0)):
		_teardown_sandbox(harness)
		_fail("tb_pfo_012", "player did not settle")
		return
	_apply_player_props(player, {"jump_height": 220.0})
	var platform_top: float = platform_y + 0.125
	Input.action_press("jump")
	var stall_frames: int = 0
	var passed_through: bool = false
	for _i in range(150):
		Input.action_release("move_left")
		Input.action_release("move_right")
		var y_before: float = player.global_position.y
		_step_player_preserve_jump(player, PHYSICS_STEP)
		if player.global_position.y > platform_top + POS_EPS:
			passed_through = true
			break
		if _player_vy(player) > VY_ZERO_EPS and absf(player.global_position.y - y_before) < 1e-4:
			stall_frames += 1
	Input.action_release("jump")
	_assert_true(
		passed_through,
		"tb_pfo_012_player_passes_through_one_way_while_ascending"
	)
	_assert_true(
		stall_frames < 3,
		"tb_pfo_012_no_sustained_stall_below_one_way_during_ascent"
	)
	_teardown_sandbox(harness)


func run_all() -> int:
	print("--- test_player_physics_frame_order_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	test_tb_pfo_001_buffer_expired_before_landing_no_buffered_jump()
	test_tb_pfo_002_buffer_still_valid_one_frame_before_expiry()
	test_tb_pfo_003_negative_jump_buffer_time_treated_as_disabled()
	test_tb_pfo_004_enemy_root_blocks_buffer_on_landing()
	test_tb_pfo_005_coyote_jump_denied_after_window_expires()
	test_tb_pfo_006_coyote_jump_does_not_double_with_buffer_on_landing()
	test_tb_pfo_007_double_air_press_buffered_landing_single_jump()
	test_tb_pfo_008_grounded_single_press_single_upward_spike()
	test_tb_pfo_009_mask_ground_only_every_frame_while_vy_positive()
	test_tb_pfo_010_mask_includes_one_way_at_apex_when_vy_zero_or_negative()
	test_tb_pfo_011_mask_full_while_falling_toward_one_way()
	test_tb_pfo_012_ascending_through_one_way_never_blocked_mid_rise()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count
