#
# test_player_state_machine_adversarial.gd
#
# Adversarial extension of PlayerStateMachine unit tests (M11-01).
# Spec edge cases EC-1..EC-10 plus mutation, stress, and naming-isolation probes.
# Ticket: project_board/11_milestone_11_base_mutation_attacks/backlog/01_player_state_machine.md
# Spec: project_board/specs/player_state_machine_spec.md
#
# Generated by Test Breaker Agent — 2026-05-23.
#

class_name PlayerStateMachineAdversarialTests
extends "res://tests/scripts/player/test_player_state_machine.gd"


const MIN_FLOAT_FROM_JUMP_SEC: float = 0.05
const VERTICAL_JUMP_EPSILON: float = 0.01

const ALL_STATES: Array[int] = [
	STATE_IDLE,
	STATE_WALK,
	STATE_JUMP,
	STATE_FALL,
	STATE_FLOAT,
	STATE_WALL_CLING,
	STATE_ABSORB,
	STATE_MUTATE,
	STATE_HURT,
	STATE_DEAD,
]


# ---------------------------------------------------------------------------
# Adversarial helpers (reuse primary suite factories)
# ---------------------------------------------------------------------------

func _require_machine(test_name: String) -> Object:
	var machine: Object = _make_machine()
	if machine == null:
		_fail_missing_module(test_name)
		return null
	if not _has_fsm_api(machine):
		_fail(test_name + "_api", "PlayerStateMachine missing required FSM API")
		return null
	return machine


func _require_ctx(test_name: String) -> Object:
	var ctx: Object = _ctx_floor_idle()
	if ctx == null:
		_fail_missing_module(test_name)
		return null
	return ctx


# ---------------------------------------------------------------------------
# EC-1 — DEAD terminal until reset()
# ---------------------------------------------------------------------------

func test_ec1_dead_blocks_all_non_dead_transitions() -> void:
	var machine: Object = _require_machine("ec1_dead_blocks")
	if machine == null:
		return
	machine.transition(STATE_DEAD)
	for target in ALL_STATES:
		if target == STATE_DEAD:
			continue
		var ok: bool = machine.transition(target)
		_assert_false(
			ok,
			"ec1_dead_to_" + str(target) + "_denied — G-DEAD blocks transition from DEAD"
		)
		_assert_eq_int(
			STATE_DEAD,
			_state_of(machine),
			"ec1_dead_persists_after_" + str(target) + " — state stays DEAD"
		)


func test_ec1_dead_same_state_noop_allowed() -> void:
	var machine: Object = _require_machine("ec1_dead_noop")
	if machine == null:
		return
	machine.transition(STATE_DEAD)
	machine.update(0.02)
	var before_timer: float = _timer_of(machine)
	var ok: bool = machine.transition(STATE_DEAD)
	_assert_true(ok, "ec1_dead_to_dead_noop — same-state DEAD→DEAD returns true")
	_assert_eq_int(STATE_DEAD, _state_of(machine), "ec1_dead_noop_state")
	_assert_approx(
		before_timer,
		_timer_of(machine),
		"ec1_dead_noop_timer — same-state does not reset timer"
	)


func test_ec1_reset_required_to_leave_dead() -> void:
	var machine: Object = _require_machine("ec1_reset_required")
	if machine == null:
		return
	machine.transition(STATE_DEAD)
	machine.reset()
	_assert_eq_int(STATE_IDLE, _state_of(machine), "ec1_reset_leaves_dead — reset() → IDLE")
	var ok: bool = machine.transition(STATE_WALK)
	_assert_true(ok, "ec1_walk_after_reset — transitions allowed after reset()")


# ---------------------------------------------------------------------------
# EC-2 — double notify_damage_taken() same frame
# ---------------------------------------------------------------------------

func test_ec2_double_notify_before_sync_second_hurt_denied() -> void:
	var machine: Object = _require_machine("ec2_double_notify")
	var ctx: Object = _require_ctx("ec2_double_notify_ctx")
	if machine == null or ctx == null:
		return
	machine.notify_damage_taken()
	machine.notify_damage_taken()
	machine.sync_from_context(ctx)
	_assert_eq_int(STATE_HURT, _state_of(machine), "ec2_first_sync_hurt — first notify yields HURT")
	_assert_false(
		machine.can_transition_to(STATE_HURT),
		"ec2_second_hurt_denied — G-HURT blocks re-entry while HURT"
	)


func test_ec2_double_notify_while_hurt_transition_fails() -> void:
	var machine: Object = _require_machine("ec2_hurt_transition_fail")
	var ctx: Object = _require_ctx("ec2_hurt_transition_fail_ctx")
	if machine == null or ctx == null:
		return
	machine.notify_damage_taken()
	machine.sync_from_context(ctx)
	machine.notify_damage_taken()
	var ok: bool = machine.transition(STATE_HURT)
	_assert_false(ok, "ec2_transition_hurt_while_hurt — explicit HURT re-entry denied")
	_assert_eq_int(STATE_HURT, _state_of(machine), "ec2_stays_hurt — state unchanged")


# ---------------------------------------------------------------------------
# EC-3 — DEAD overrides mid-air kinematic derivation
# ---------------------------------------------------------------------------

func test_ec3_dead_overrides_jump_mid_air() -> void:
	var machine: Object = _require_machine("ec3_dead_jump")
	var ctx: Object = _require_ctx("ec3_dead_jump_ctx")
	if machine == null or ctx == null:
		return
	machine.transition(STATE_JUMP)
	ctx.is_on_floor = false
	ctx.vertical_velocity = 2.0
	ctx.current_hp = 0.0
	ctx.min_hp = 0.0
	var derived: int = int(machine.compute_derived_state(ctx))
	_assert_eq_int(STATE_DEAD, derived, "ec3_dead_over_jump — DEAD priority over JUMP signals")
	machine.sync_from_context(ctx)
	_assert_eq_int(STATE_DEAD, _state_of(machine), "ec3_sync_dead_from_jump — sync applies DEAD")


func test_ec3_dead_overrides_fall_mid_air() -> void:
	var machine: Object = _require_machine("ec3_dead_fall")
	var ctx: Object = _require_ctx("ec3_dead_fall_ctx")
	if machine == null or ctx == null:
		return
	machine.transition(STATE_FALL)
	ctx.is_on_floor = false
	ctx.vertical_velocity = -3.0
	ctx.current_hp = 0.0
	ctx.min_hp = 0.0
	_assert_eq_int(
		STATE_DEAD,
		int(machine.compute_derived_state(ctx)),
		"ec3_dead_over_fall — DEAD priority over FALL signals"
	)


# ---------------------------------------------------------------------------
# EC-4 — ABSORB wins over MUTATE
# ---------------------------------------------------------------------------

func test_ec4_absorb_beats_mutate_on_floor_and_air() -> void:
	var machine: Object = _require_machine("ec4_absorb_priority")
	var ctx: Object = _require_ctx("ec4_absorb_priority_ctx")
	if machine == null or ctx == null:
		return
	ctx.is_any_chunk_stuck = true
	ctx.is_mutation_active = true
	_assert_eq_int(
		STATE_ABSORB,
		int(machine.compute_derived_state(ctx)),
		"ec4_absorb_on_floor — ABSORB > MUTATE on ground"
	)
	ctx.is_on_floor = false
	ctx.vertical_velocity = -1.0
	_assert_eq_int(
		STATE_ABSORB,
		int(machine.compute_derived_state(ctx)),
		"ec4_absorb_in_air — ABSORB > MUTATE mid-air"
	)


func test_ec4_mutate_only_when_no_chunk_stuck() -> void:
	var machine: Object = _require_machine("ec4_mutate_only")
	var ctx: Object = _require_ctx("ec4_mutate_only_ctx")
	if machine == null or ctx == null:
		return
	ctx.is_mutation_active = true
	ctx.is_any_chunk_stuck = false
	_assert_eq_int(
		STATE_MUTATE,
		int(machine.compute_derived_state(ctx)),
		"ec4_mutate_without_stuck — MUTATE when chunk not stuck"
	)


# ---------------------------------------------------------------------------
# EC-5 — landing without cling derives ground state
# ---------------------------------------------------------------------------

func test_ec5_landing_without_cling_derives_ground_state() -> void:
	var machine: Object = _require_machine("ec5_landing_idle")
	var ctx: Object = _require_ctx("ec5_landing_idle_ctx")
	if machine == null or ctx == null:
		return
	ctx.is_on_floor = true
	ctx.is_wall_clinging = false
	ctx.horizontal_speed = 0.0
	_assert_eq_int(
		STATE_IDLE,
		int(machine.compute_derived_state(ctx)),
		"ec5_floor_idle — cling off + floor → IDLE"
	)
	ctx.horizontal_speed = 0.2
	_assert_eq_int(
		STATE_WALK,
		int(machine.compute_derived_state(ctx)),
		"ec5_floor_walk — cling off + floor + speed → WALK"
	)


func test_ec5_cling_active_takes_precedence_over_floor() -> void:
	var machine: Object = _require_machine("ec5_cling_over_floor")
	var ctx: Object = _require_ctx("ec5_cling_over_floor_ctx")
	if machine == null or ctx == null:
		return
	ctx.is_on_floor = true
	ctx.is_wall_clinging = true
	_assert_eq_int(
		STATE_WALL_CLING,
		int(machine.compute_derived_state(ctx)),
		"ec5_cling_on_floor — cling flag yields WALL_CLING when true"
	)


# ---------------------------------------------------------------------------
# EC-6 — same-state transition is no-op; timer not reset
# ---------------------------------------------------------------------------

func test_ec6_same_state_noop_all_states() -> void:
	var machine: Object = _require_machine("ec6_same_state")
	if machine == null:
		return
	for state in ALL_STATES:
		machine.reset()
		if state != STATE_IDLE:
			machine.transition(state)
		machine.update(0.03)
		var before_timer: float = _timer_of(machine)
		var ok: bool = machine.transition(state)
		_assert_true(
			ok,
			"ec6_same_state_ok_" + str(state) + " — same-state transition returns true"
		)
		machine.update(0.01)
		_assert_approx(
			before_timer + 0.01,
			_timer_of(machine),
			"ec6_timer_not_reset_" + str(state) + " — timer continues after same-state no-op"
		)


# ---------------------------------------------------------------------------
# EC-7 — update(0.0) is no-op
# ---------------------------------------------------------------------------

func test_ec7_update_zero_delta_repeated() -> void:
	var machine: Object = _require_machine("ec7_update_zero")
	if machine == null:
		return
	machine.update(0.07)
	for i in 10:
		machine.update(0.0)
	_assert_approx(0.07, _timer_of(machine), "ec7_zero_delta_repeated — update(0.0) x10 is no-op")


# ---------------------------------------------------------------------------
# EC-8 — reset() from DEAD clears timer and hurt latch
# ---------------------------------------------------------------------------

func test_ec8_reset_from_dead_clears_hurt_latch() -> void:
	var machine: Object = _require_machine("ec8_reset_hurt_latch")
	var ctx: Object = _require_ctx("ec8_reset_hurt_latch_ctx")
	if machine == null or ctx == null:
		return
	machine.notify_damage_taken()
	machine.sync_from_context(ctx)
	machine.transition(STATE_DEAD)
	machine.reset()
	_assert_eq_int(STATE_IDLE, _state_of(machine), "ec8_reset_idle")
	_assert_approx(0.0, _timer_of(machine), "ec8_reset_timer_zero")
	machine.notify_damage_taken()
	machine.sync_from_context(ctx)
	_assert_eq_int(
		STATE_HURT,
		_state_of(machine),
		"ec8_hurt_after_reset — notify_damage works after reset() clears latch"
	)


# ---------------------------------------------------------------------------
# EC-9 — explicit FLOAT from IDLE denied
# ---------------------------------------------------------------------------

func test_ec9_float_from_idle_denied() -> void:
	var machine: Object = _require_machine("ec9_float_idle")
	if machine == null:
		return
	_assert_false(
		machine.can_transition_to(STATE_FLOAT),
		"ec9_can_float_from_idle — G-FLOAT denies FLOAT from IDLE"
	)
	var ok: bool = machine.transition(STATE_FLOAT)
	_assert_false(ok, "ec9_transition_float_from_idle — transition(FLOAT) from IDLE fails")
	_assert_eq_int(STATE_IDLE, _state_of(machine), "ec9_idle_persists")


func test_ec9_float_from_walk_and_absorb_denied() -> void:
	var machine: Object = _require_machine("ec9_float_groundish")
	if machine == null:
		return
	for state in [STATE_WALK, STATE_ABSORB, STATE_MUTATE, STATE_HURT]:
		machine.reset()
		machine.transition(state)
		_assert_false(
			machine.can_transition_to(STATE_FLOAT),
			"ec9_float_denied_from_" + str(state) + " — G-FLOAT blocks FLOAT"
		)


# ---------------------------------------------------------------------------
# EC-10 — HURT flash when hp > min_hp; DEAD only at/below min
# ---------------------------------------------------------------------------

func test_ec10_hurt_not_dead_when_hp_above_min() -> void:
	var machine: Object = _require_machine("ec10_hurt_not_dead")
	var ctx: Object = _require_ctx("ec10_hurt_not_dead_ctx")
	if machine == null or ctx == null:
		return
	ctx.current_hp = 1.0
	ctx.min_hp = 0.0
	machine.notify_damage_taken()
	machine.sync_from_context(ctx)
	_assert_eq_int(STATE_HURT, _state_of(machine), "ec10_hurt_flash — HURT when hp>min_hp")
	_assert_false(_state_of(machine) == STATE_DEAD, "ec10_not_dead — DEAD not entered")


func test_ec10_dead_only_when_hp_at_or_below_min() -> void:
	var machine: Object = _require_machine("ec10_dead_at_zero")
	var ctx: Object = _require_ctx("ec10_dead_at_zero_ctx")
	if machine == null or ctx == null:
		return
	ctx.current_hp = 0.0
	ctx.min_hp = 0.0
	machine.sync_from_context(ctx)
	_assert_eq_int(STATE_DEAD, _state_of(machine), "ec10_dead_at_zero_hp")


# ---------------------------------------------------------------------------
# ADV-001 — MovementState naming isolation (NFR-6)
# ---------------------------------------------------------------------------

func test_adv_movement_state_class_distinct_from_player_state_enum() -> void:
	var fsm_script: GDScript = _load_fsm_script()
	if fsm_script == null:
		_fail_missing_module("adv_naming_fsm")
		return
	var sim_script: GDScript = load("res://scripts/movement/movement_simulation.gd") as GDScript
	_assert_true(sim_script != null, "adv_sim_script_loads — MovementSimulation script exists")
	_assert_eq_string(
		"PlayerStateMachine",
		fsm_script.get_global_name(),
		"adv_fsm_class_name — gameplay FSM is PlayerStateMachine"
	)
	_assert_eq_string(
		"MovementSimulation",
		sim_script.get_global_name(),
		"adv_sim_class_name — kinematic layer is MovementSimulation"
	)
	var sim_constants: Dictionary = sim_script.get_script_constant_map()
	for key in sim_constants.keys():
		_assert_false(
			str(key) == "PlayerState",
			"adv_sim_no_player_state_enum — MovementSimulation must not define PlayerState enum"
		)


func test_adv_player_state_enum_count_and_values() -> void:
	var fsm_script: GDScript = _load_fsm_script()
	if fsm_script == null:
		_fail_missing_module("adv_enum_shape")
		return
	var enum_dict: Dictionary = fsm_script.get_script_constant_map()
	var player_enum: Dictionary = {}
	for key in enum_dict.keys():
		if str(key) == "PlayerState" and enum_dict[key] is Dictionary:
			player_enum = enum_dict[key]
			break
	if player_enum.is_empty():
		_fail("adv_enum_shape", "PlayerState enum not found on PlayerStateMachine script")
		return
	_assert_eq_int(EXPECTED_STATE_COUNT, player_enum.size(), "adv_enum_ten_members")
	_assert_true(player_enum.has("DEAD"), "adv_enum_has_dead")
	_assert_false(player_enum.has("CHARGE_UP"), "adv_enum_no_attack_states")


# ---------------------------------------------------------------------------
# ADV-002 — FLOAT-from-JUMP epsilon boundary (PSM-6)
# ---------------------------------------------------------------------------

func test_adv_float_from_jump_blocked_at_epsilon_below_min() -> void:
	var machine: Object = _require_machine("adv_float_epsilon_below")
	if machine == null:
		return
	machine.transition(STATE_JUMP)
	machine.update(MIN_FLOAT_FROM_JUMP_SEC - 0.000001)
	var ok: bool = machine.transition(STATE_FLOAT)
	_assert_false(
		ok,
		"adv_float_epsilon_below — transition(FLOAT) denied just below MIN_FLOAT_FROM_JUMP_SEC"
	)


func test_adv_float_from_jump_allowed_at_exact_min() -> void:
	var machine: Object = _require_machine("adv_float_epsilon_at")
	if machine == null:
		return
	machine.transition(STATE_JUMP)
	machine.update(MIN_FLOAT_FROM_JUMP_SEC)
	var ok: bool = machine.transition(STATE_FLOAT)
	_assert_true(
		ok,
		"adv_float_epsilon_at — transition(FLOAT) allowed at exactly MIN_FLOAT_FROM_JUMP_SEC"
	)


func test_adv_float_from_fall_allowed() -> void:
	var machine: Object = _require_machine("adv_float_from_fall")
	if machine == null:
		return
	machine.transition(STATE_FALL)
	_assert_true(
		machine.can_transition_to(STATE_FLOAT),
		"adv_float_from_fall_can — G-FLOAT allows FLOAT from FALL"
	)
	var ok: bool = machine.transition(STATE_FLOAT)
	_assert_true(ok, "adv_float_from_fall_transition — transition(FLOAT) from FALL succeeds")


# ---------------------------------------------------------------------------
# ADV-003 — negative delta clamped; jump epsilon boundary in derivation
# ---------------------------------------------------------------------------

func test_adv_negative_delta_does_not_decrease_timer() -> void:
	var machine: Object = _require_machine("adv_negative_delta")
	if machine == null:
		return
	machine.update(0.05)
	machine.update(-0.5)
	_assert_approx(0.05, _timer_of(machine), "adv_negative_delta_clamped — update(-0.5) is no-op per maxf(0,delta)")


func test_adv_jump_epsilon_boundary_in_derivation() -> void:
	var machine: Object = _require_machine("adv_jump_epsilon")
	var ctx: Object = _require_ctx("adv_jump_epsilon_ctx")
	if machine == null or ctx == null:
		return
	ctx.is_on_floor = false
	ctx.vertical_velocity = VERTICAL_JUMP_EPSILON
	_assert_eq_int(
		STATE_JUMP,
		int(machine.compute_derived_state(ctx)),
		"adv_jump_at_epsilon — vy==VERTICAL_JUMP_EPSILON → JUMP"
	)
	ctx.vertical_velocity = VERTICAL_JUMP_EPSILON - 0.001
	_assert_eq_int(
		STATE_FALL,
		int(machine.compute_derived_state(ctx)),
		"adv_fall_below_epsilon — vy below epsilon → FALL"
	)


# ---------------------------------------------------------------------------
# ADV-004 — HURT exits next frame when MIN_HURT_SEC==0 (AC-PSM-8.3)
# ---------------------------------------------------------------------------

func test_adv_hurt_exits_next_sync_without_new_damage() -> void:
	var machine: Object = _require_machine("adv_hurt_exit")
	var ctx: Object = _require_ctx("adv_hurt_exit_ctx")
	if machine == null or ctx == null:
		return
	machine.notify_damage_taken()
	machine.sync_from_context(ctx)
	_assert_eq_int(STATE_HURT, _state_of(machine), "adv_hurt_exit_precondition — sync enters HURT")
	machine.sync_from_context(ctx)
	_assert_eq_int(
		STATE_IDLE,
		_state_of(machine),
		"adv_hurt_exit_next_sync — second sync without damage returns to IDLE (MIN_HURT_SEC==0)"
	)


# ---------------------------------------------------------------------------
# ADV-005 — can_transition_to matches transition for denied pairs
# ---------------------------------------------------------------------------

func test_adv_can_transition_matches_transition_denials() -> void:
	var machine: Object = _require_machine("adv_guard_consistency")
	if machine == null:
		return
	machine.transition(STATE_DEAD)
	for target in ALL_STATES:
		if target == STATE_DEAD:
			continue
		var can: bool = machine.can_transition_to(target)
		var ok: bool = machine.transition(target)
		_assert_true(
			can == ok,
			"adv_guard_match_dead_" + str(target) + " — can_transition_to matches transition() from DEAD"
		)
	machine.reset()
	machine.transition(STATE_HURT)
	for target in ALL_STATES:
		if target == STATE_HURT:
			continue
		var probe: Object = _make_machine()
		if probe == null:
			_fail_missing_module("adv_guard_hurt_probe")
			return
		probe.transition(STATE_HURT)
		var can_h: bool = probe.can_transition_to(target)
		var ok_h: bool = probe.transition(target)
		_assert_true(
			can_h == ok_h,
			"adv_guard_match_hurt_" + str(target) + " — can_transition_to matches transition() from HURT"
		)


# ---------------------------------------------------------------------------
# ADV-006 — DEAD stress loop; instance isolation
# ---------------------------------------------------------------------------

func test_adv_dead_stress_never_leaves_without_reset() -> void:
	var machine: Object = _require_machine("adv_dead_stress")
	if machine == null:
		return
	machine.transition(STATE_DEAD)
	for i in 100:
		for target in ALL_STATES:
			if target == STATE_DEAD:
				continue
			machine.transition(target)
		_assert_eq_int(
			STATE_DEAD,
			_state_of(machine),
			"adv_dead_stress_iter_" + str(i) + " — DEAD persists under repeated transition attempts"
		)


func test_adv_many_instances_are_isolated() -> void:
	var machines: Array = []
	for i in 20:
		var m: Object = _require_machine("adv_isolation_" + str(i))
		if m == null:
			return
		machines.append(m)
	for i in machines.size():
		var m: Object = machines[i]
		if i % 2 == 0:
			m.transition(STATE_JUMP)
		else:
			m.transition(STATE_HURT)
			m.notify_damage_taken()
			m.sync_from_context(_ctx_floor_idle())
	for i in machines.size() / 2:
		machines[i].reset()
	for i in machines.size():
		var m: Object = machines[i]
		if i < machines.size() / 2:
			_assert_eq_int(STATE_IDLE, _state_of(m), "adv_isolation_reset_" + str(i) + " — reset half stay IDLE")
		elif i % 2 == 0:
			_assert_eq_int(STATE_JUMP, _state_of(m), "adv_isolation_jump_" + str(i) + " — unreset JUMP persists")
		else:
			_assert_eq_int(STATE_HURT, _state_of(m), "adv_isolation_hurt_" + str(i) + " — unreset HURT persists")


# ---------------------------------------------------------------------------
# ADV-007 — sync_from_context death path; denied transition preserves state
# ---------------------------------------------------------------------------

func test_adv_sync_death_via_derivation() -> void:
	var machine: Object = _require_machine("adv_sync_death")
	var ctx: Object = _require_ctx("adv_sync_death_ctx")
	if machine == null or ctx == null:
		return
	ctx.current_hp = 0.0
	ctx.min_hp = 0.0
	machine.sync_from_context(ctx)
	_assert_eq_int(STATE_DEAD, _state_of(machine), "adv_sync_death — sync applies DEAD from ctx")


func test_adv_denied_float_from_jump_preserves_state_and_timer() -> void:
	var machine: Object = _require_machine("adv_denied_timer")
	if machine == null:
		return
	machine.transition(STATE_JUMP)
	machine.update(0.02)
	var before_state: int = _state_of(machine)
	var before_timer: float = _timer_of(machine)
	var ok: bool = machine.transition(STATE_FLOAT)
	_assert_false(ok, "adv_jump_float_early — FLOAT denied before min duration")
	_assert_eq_int(before_state, _state_of(machine), "adv_denied_state_preserved")
	_assert_approx(before_timer, _timer_of(machine), "adv_denied_timer_preserved")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

func run_all() -> int:
	print("--- test_player_state_machine_adversarial.gd ---")
	_pass_count = 0
	_fail_count = 0

	test_ec1_dead_blocks_all_non_dead_transitions()
	test_ec1_dead_same_state_noop_allowed()
	test_ec1_reset_required_to_leave_dead()

	test_ec2_double_notify_before_sync_second_hurt_denied()
	test_ec2_double_notify_while_hurt_transition_fails()

	test_ec3_dead_overrides_jump_mid_air()
	test_ec3_dead_overrides_fall_mid_air()

	test_ec4_absorb_beats_mutate_on_floor_and_air()
	test_ec4_mutate_only_when_no_chunk_stuck()

	test_ec5_landing_without_cling_derives_ground_state()
	test_ec5_cling_active_takes_precedence_over_floor()

	test_ec6_same_state_noop_all_states()
	test_ec7_update_zero_delta_repeated()
	test_ec8_reset_from_dead_clears_hurt_latch()

	test_ec9_float_from_idle_denied()
	test_ec9_float_from_walk_and_absorb_denied()

	test_ec10_hurt_not_dead_when_hp_above_min()
	test_ec10_dead_only_when_hp_at_or_below_min()

	test_adv_movement_state_class_distinct_from_player_state_enum()
	test_adv_player_state_enum_count_and_values()
	test_adv_float_from_jump_blocked_at_epsilon_below_min()
	test_adv_float_from_jump_allowed_at_exact_min()
	test_adv_float_from_fall_allowed()
	test_adv_negative_delta_does_not_decrease_timer()
	test_adv_jump_epsilon_boundary_in_derivation()
	test_adv_hurt_exits_next_sync_without_new_damage()
	test_adv_can_transition_matches_transition_denials()
	test_adv_dead_stress_never_leaves_without_reset()
	test_adv_many_instances_are_isolated()
	test_adv_sync_death_via_derivation()
	test_adv_denied_float_from_jump_preserves_state_and_timer()

	print("")
	print("  Results: " + str(_pass_count) + " passed, " + str(_fail_count) + " failed")
	return _fail_count

